---
permalink: try/task_use_demonode.html 
sidebar: sidebar 
keywords: element demo node, virtual machine, element software, element api, vmware deployment 
summary: Le nœud de démonstration Element est une machine virtuelle VMware du logiciel Element, qui permet de démontrer facilement la plupart des fonctionnalités clés de stockage des produits NetApp HCI et SolidFire. 
---
= Essayez les fonctionnalités de stockage à l'aide du nœud de démonstration Element
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
https://mysupport.netapp.com/site/tools/tool-eula/element-demonode/download["Nœud de démonstration Element"^] Est une version VMware Virtual machine (VM) du logiciel Element, qui permet de démontrer facilement de nombreuses fonctionnalités clés de stockage des produits NetApp HCI et SolidFire. Le nœud de démonstration permet aux développeurs de coder par rapport à l'API Element sans matériel physique. Il est fourni sous forme de fichier OVA pour un déploiement VMware facile.



== Fonctionnalités prises en charge :

Le nœud de démonstration d'Element n'est destiné qu'à être utilisé comme outil de démonstration et de développement. Avant d'utiliser le nœud de démonstration, tenez compte des limitations fonctionnelles suivantes :

* Le nœud de démonstration Element ne prend pas en charge la mise en cluster. Elle fonctionne comme un cluster à un seul nœud uniquement.
* Elle ne prend pas en charge les mises à niveau d'Element. Pour effectuer une démonstration de la plus récente version d'Element, nous vous recommandons d'installer une nouvelle VM de nœud de démonstration.
* Son objectif n'est pas de démontrer la performance du stockage. Les performances observées sur le nœud de démonstration n'indiquent aucunement la performance des clusters physiques.
* Vous ne pouvez pas ajouter de nœuds de démonstration aux clusters NetApp HCI ou SolidFire.
* Les VLAN VRF ne sont pas pris en charge (les VLAN balisés standard sont pris en charge)
* Le service de tranche multi-disques (MDSS) n'est pas pris en charge.
* Le nœud de démonstration Element n'est pris en charge qu'avec les datastores VMFS. Les VVol ne sont pas pris en charge.
* La fonctionnalité de configuration et de surveillance basée sur le matériel ne fonctionne pas avec le nœud de démonstration.
* Elle prend en charge un maximum de 10 snapshots par volume.
* Elle prend en charge un maximum de 20 comptes par nœud/cluster.
* Il prend en charge un maximum de 100 volumes par compte.
* Il prend en charge un maximum de 200 vvols par compte.
* Elle prend en charge une taille de volume maximale de 100 Gio.
* Elle prend en charge un cluster limité à 3000 000 IOPS.



NOTE: Toutes les autres limites du logiciel Element s'appliquent. Pour plus de détails, reportez-vous aux dernières notes de version du logiciel Element.



== Exigences liées aux VM

* Capacité totale de 240 Go (la taille et le nombre de disques virtuels de la machine virtuelle ne peuvent pas être modifiés. Tout stockage supplémentaire présenté via l'hyperviseur est ignoré par le système d'exploitation invité.)
* Disque racine de 60 Go
* Mise à zéro avec/Eager (un disque de métadonnées de 30 Go ou trois disques de blocs de 50 Go) ou mise à zéro avec provisionnement fin/mise en service (*recommandé*) (un disque de métadonnées de 30 Go ou trois disques de bloc de 50 Go)
* Deux CPU virtuels (entièrement réservés)
* 16 Go de RAM (entièrement réservé)
* Adaptateur HBA unique pour tous les disques, LSI Logic parallèle
* Deux cartes vNIC, vmxnet3 (une gestion, un stockage)




== Configuration requise pour l'hôte

* ESXI 6.0 ou 6.5 pour le nœud de démonstration Element 11.7 VM
* ESXi 6.5 pour le nœud de démonstration Element 12.0 et 12.2 machines virtuelles
* ESXi 6.7 et 7.0 pour les nœuds de démonstration Element 12.3 et 12.5 machines virtuelles
* Architecture Intel® 64 bits multicœur




== Téléchargez le nœud de démonstration Element

Le logiciel Element Demo Node est un ensemble de fichiers VMware qui ont été emballés dans un fichier .ova.



== Installez le nœud de démonstration Element sur VMware ESXi

L'installation d'Element Demo Node sur VMware ESXi implique les tâches suivantes :

* <<Configurez les interfaces réseau>>
* <<Enregistrez le nœud de démonstration sur un serveur ESXi>>
* <<Démarrez le nœud de démonstration sur un serveur ESXi>>




=== Configurez les interfaces réseau

Le nœud de démonstration Element requiert deux réseaux de machines virtuelles distincts. L'une concerne le trafic de stockage et l'autre le trafic de gestion. Vous devez configurer le réseau de stockage pour prendre en charge les trames Jumbo.



=== Enregistrez le nœud de démonstration sur un serveur ESXi

Pour enregistrer Element Demo Node sur un serveur ESXi, vous devez déployer le fichier .ova du nœud de démonstration à l'aide de vSphere client.

.Étapes
. Connectez-vous au client vSphere et sélectionnez l'hôte ESXi dans le panneau d'inventaire.
. Sélectionnez *fichier* > *déployer le modèle OVF*.
+
L'assistant de déploiement de modèle OVF est lancé.

. Sur la page *Sélectionner le modèle*, accédez au fichier OVA que vous avez téléchargé et sélectionnez *Ouvrir*.
. Sélectionnez *Suivant*.
. Sur la page *Nom et emplacement*, spécifiez un nom et un emplacement pour le modèle déployé, puis sélectionnez *Suivant*.
. Sur la page *Sélectionner une ressource*, naviguez jusqu'à l'emplacement où vous souhaitez exécuter le modèle, puis sélectionnez *Suivant*.
. Vérifiez les détails et sélectionnez *Suivant*.
. Sur la page Sélectionner le stockage, sélectionnez l'emplacement de stockage des fichiers de la machine virtuelle, puis sélectionnez *Suivant*.
. Sur la page *Select Networks*, mappez le réseau utilisé dans le fichier OVA aux deux réseaux de machines virtuelles distincts de votre inventaire et sélectionnez *Next*.
. Sur la page *prêt à terminer*, vérifiez les détails de la machine virtuelle que vous créez, puis sélectionnez *Terminer*.



NOTE: Le déploiement d'un nœud de démonstration peut prendre quelques minutes.



=== Démarrez le nœud de démonstration sur un serveur ESXi

Vous devez démarrer la VM du nœud de démonstration pour accéder à Element via la console VMware ESXi.

.Étapes
. Dans vSphere client, sélectionnez la machine virtuelle du nœud de démonstration que vous avez créée.
. Sélectionnez l'onglet *Résumé* pour afficher les détails de cette machine virtuelle.
. Sélectionnez *Power On* pour démarrer la VM.
. Sélectionnez *lancer la console Web*.
. Utilisez la TUI pour configurer le nœud de démonstration. Pour plus d'informations, voir link:../setup/concept_setup_configure_a_storage_node.html["Configurez un nœud de stockage"^].




== Comment obtenir de l'aide

Le nœud de démonstration Element est disponible pour les bénévoles de meilleurs efforts. Pour obtenir de l'aide, publiez vos questions sur le https://community.netapp.com/t5/Simulator-Discussions/bd-p/simulator-discussions["Forum des nœuds de démo Element"^].



== Trouvez plus d'informations

https://mysupport.netapp.com/site/tools/tool-eula/element-demonode/download["Page de téléchargement du nœud de démonstration Element (connexion requise)"^]
