---
sidebar: sidebar 
permalink: upgrade/concept_element_upgrade_overview.html 
summary: Après le déploiement, vous pouvez maintenir votre système de stockage SolidFire Element à jour en mettant à niveau tous les composants de stockage NetApp. 
keywords: netapp, solidfire upgrade, vcp upgrade, element upgrade, vsphere upgrade 
---
= Présentation de la séquence de mise à niveau
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Grâce à la mise à niveau séquentielle de tous les composants de stockage NetApp, vous pouvez maintenir votre système de stockage SolidFire Element à jour après le déploiement.

Parmi ces composants : services de gestion, NetApp Hybrid Cloud Control, logiciel Element, nœud de gestion et (selon votre installation) le plug-in Element pour vCenter Server.

[NOTE]
====
* Depuis le 2023 novembre, vous ne pouvez pas démarrer de mise à niveau de composant avec NetApp Hybrid Cloud Control ou l'API REST, car les certificats de clé de signature (privé et public) ont expiré le 5 novembre 2023. Pour contourner ce problème, vous pouvez link:task_hcc_upgrade_management_node.html["mise à niveau du nœud de gestion sans déplacement des données"]passer à la version 12.8 avant d'utiliser le logiciel NetApp de contrôle du cloud hybride ou l'API REST pour mettre à niveau les services de gestion, le logiciel Element et le firmware de stockage.
+
Si vous déployez un nouveau nœud de gestion avec la version 12.8, vous pouvez utiliser le contrôle du cloud hybride NetApp ou l'API REST pour effectuer les mises à niveau des composants dans l'ordre indiqué dans la <<sys_upgrade,séquence de mise à niveau du système>>.

* Les nœuds suivants ne sont pas pris en charge. Si vous tentez de mettre à niveau l'un de ces nœuds vers une version d'élément non prise en charge, une erreur s'affiche indiquant que le nœud n'est pas pris en charge par l'élément 12.x :
+
** À partir des nœuds de stockage Element 12.8, SF4805, SF9605, SF19210 et SF38410.
** À partir des nœuds de stockage Element 12.7, SF2405 et SF9608, ainsi que des nœuds FC FC0025 et SF-FCN-01.


* Depuis Element 12.5, NetApp HealthTools n'est plus pris en charge pour les mises à niveau du logiciel Element. Si vous exécutez Element 11.0 ou 11.1, vous devez d'abord https://docs.netapp.com/us-en/element-software-123/upgrade/task_hcc_upgrade_element_software.html#upgrade-element-software-at-connected-sites-using-healthtools["Effectuez la mise à niveau vers Element 12.3 à l'aide de HealthTools"^] Puis mettez à niveau vers Element 12.5 ou version ultérieure avec NetApp Hybrid Cloud Control.


====
Le <<sys_upgrade,séquence de mise à niveau du système>> Nous décrivons dans les tâches nécessaires à la mise à niveau d'un système de stockage 100 % Flash SolidFire. Idéalement, ces procédures sont exécutées dans le cadre d'une séquence de mise à niveau plus importante et non isolément. Si une mise à niveau ou une mise à jour basée sur les composants est nécessaire, reportez-vous aux conditions préalables requises pour vous assurer que des complexités supplémentaires sont traitées.

Le link:task_sf_upgrade_all_vsphere.html["Séquence de mise à niveau de vSphere"] L'ajout du contenu du plug-in Element pour vCenter Server décrit les étapes supplémentaires requises pour la préinstallation et la post-mise à niveau pour vCenter Server.

.Avant de commencer
* Vous exécutez le nœud de gestion 11.3 ou version ultérieure. Les dernières versions du nœud de gestion disposent d'une architecture modulaire qui fournit des services individuels.
+

TIP: Pour vérifier la version, connectez-vous à votre nœud de gestion et consultez le numéro de version d'élément dans la bannière de connexion. Si vous n'avez pas 11.3, voir link:task_hcc_upgrade_management_node.html["Mettez à niveau le nœud de gestion"].

* Vous avez mis à niveau vos services de gestion vers au moins la version 2.1.326.
+
Les mises à niveau utilisant NetApp Hybrid Cloud Control ne sont pas disponibles dans les versions précédentes de Service bundle.

* Vous avez vérifié que l'heure du système sur tous les nœuds est synchronisée et que le protocole NTP est correctement configuré pour le cluster de stockage et les nœuds. Chaque nœud doit être configuré avec un serveur de noms DNS dans l'interface utilisateur Web par nœud (`https://[IP address]:442`) sans erreurs de cluster non résolues liées à l'inclinaison temporelle.
* Vous avez prévu suffisamment de temps pour votre link:task_hcc_upgrade_element_software.html#element-upgrade-time["Logiciel Element"] et link:task_hcc_upgrade_storage_firmware.html#storage-firmware-upgrade["micrologiciel de stockage"] mises à niveau. Lorsque vous effectuez une mise à niveau vers Element 12.5 ou une version ultérieure, le processus de mise à niveau varie en fonction de la version du logiciel Element et des mises à jour du firmware.




== [[sys_upgrade]]séquence de mise à niveau du système

Utilisez la séquence suivante pour mettre à niveau votre système de stockage 100 % Flash SolidFire pour Element 12.5 ou une version ultérieure.

.Étapes
. link:task_hcc_upgrade_element_prechecks.html["Exécutez les contrôles d'intégrité du stockage Element avant de mettre à niveau le stockage"] .
. link:task_hcc_upgrade_management_node.html["(Facultatif) mettre à niveau votre nœud de gestion"].
+

NOTE: Il n'est plus nécessaire de mettre à niveau le système d'exploitation du nœud de gestion pour mettre à niveau le logiciel Element sur le cluster de stockage. Si le nœud de gestion est en version 11.3 ou ultérieure, vous pouvez simplement mettre à niveau les services de gestion vers la dernière version pour effectuer des mises à niveau d'Element à l'aide de NetApp Hybrid Cloud Control. Suivez la procédure de mise à niveau du nœud de gestion correspondant à votre scénario si vous devez mettre à niveau le système d'exploitation du nœud de gestion pour d'autres raisons, telles que la correction de failles de sécurité.

. link:task_hcc_update_management_services.html["Mise à jour des services de gestion à partir du cloud hybride Control"].
+
[IMPORTANT]
====
** Le pack de services de gestion 2.27 inclut le plug-in Element pour vCenter Server 5.5, qui est uniquement compatible avec le nœud de gestion 12.8. Lorsque vous effectuez une mise à jour vers les services de gestion 2.27, vous devez modifier la séquence de mise à niveau et mettre à jour le bundle de services de gestion _après_ la mise à niveau vers Element 12.8 pour assurer la compatibilité entre le nœud de gestion et les services de gestion.
** Si vous effectuez une mise à jour vers les services de gestion 2.21.61 à 2.26.40, vous devez mettre à jour le bundle de services de gestion _avant_ la mise à niveau vers Element 12.8.


====
+

IMPORTANT: Si vous mettez à jour les services de gestion vers la version 2.16 ou ultérieure et que vous exécutez un nœud de gestion 11.3 à 11.8, vous devrez augmenter la RAM de votre machine virtuelle de nœud de gestion avant de mettre à jour les services de gestion.

. link:task_hcc_upgrade_element_software.html["Mettez à niveau le firmware de stockage et le logiciel Element"].
. link:task_hcc_upgrade_storage_firmware.html["(Facultatif) mettez uniquement à niveau le firmware de votre stockage Element"].
+

NOTE: Cette tâche peut être effectuée lorsqu'une nouvelle mise à niveau du firmware de stockage est disponible en dehors d'une version majeure.

. link:task_vcp_upgrade_plugin.html["Mettez à niveau le plug-in Element pour vCenter Server"].


[discrete]
== Trouvez plus d'informations

* https://docs.netapp.com/us-en/vcp/index.html["Plug-in NetApp Element pour vCenter Server"^]
* https://docs.netapp.com/us-en/element-software/index.html["Documentation SolidFire et Element"]

