---
sidebar: sidebar 
permalink: upgrade/concept_element_upgrade_overview.html 
summary: Après le déploiement, vous pouvez maintenir votre système de stockage SolidFire Element à jour en mettant à niveau tous les composants de stockage NetApp. 
keywords: netapp, solidfire upgrade, vcp upgrade, element upgrade, vsphere upgrade 
---
= Présentation de la séquence de mise à niveau
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/
:keywords: solidfire, cloud, onprem, documentation, help


[role="lead"]
Grâce à la mise à niveau séquentielle de tous les composants de stockage NetApp, vous pouvez maintenir votre système de stockage SolidFire Element à jour après le déploiement.

Parmi ces composants : services de gestion, NetApp Hybrid Cloud Control, logiciel Element, nœud de gestion et (selon votre installation) le plug-in Element pour vCenter Server.

[NOTE]
====
* À partir de l'élément 12.7, les nœuds de stockage SF2405 et SF9608, ainsi que les nœuds FC FC0025 et SF-FCN-01 ne sont pas pris en charge. Si vous tentez de mettre à niveau un de ces nœuds vers Element 12.7, une erreur s'affiche, indiquant que ce nœud n'est pas pris en charge par Element 12.7.
* Depuis Element 12.5, NetApp HealthTools n'est plus pris en charge pour les mises à niveau du logiciel Element. Si vous exécutez Element 11.0 ou 11.1, vous devez d'abord https://docs.netapp.com/us-en/element-software-123/upgrade/task_hcc_upgrade_element_software.html#upgrade-element-software-at-connected-sites-using-healthtools["Effectuez la mise à niveau vers Element 12.3 à l'aide de HealthTools"^] Puis mettez à niveau vers Element 12.5 ou version ultérieure avec NetApp Hybrid Cloud Control.


====
Le <<sys_upgrade,séquence de mise à niveau du système>> Nous décrivons dans les tâches nécessaires à la mise à niveau d'un système de stockage 100 % Flash SolidFire. Idéalement, ces procédures sont exécutées dans le cadre d'une séquence de mise à niveau plus importante et non isolément. Si une mise à niveau ou une mise à jour basée sur les composants est nécessaire, reportez-vous aux conditions préalables requises pour vous assurer que des complexités supplémentaires sont traitées.

Le link:task_sf_upgrade_all_vsphere.html["Séquence de mise à niveau de vSphere"] L'ajout du contenu du plug-in Element pour vCenter Server décrit les étapes supplémentaires requises pour la préinstallation et la post-mise à niveau pour vCenter Server.

.Ce dont vous avez besoin
* Vous exécutez le nœud de gestion 11.3 ou version ultérieure. Les dernières versions du nœud de gestion disposent d'une architecture modulaire qui fournit des services individuels.
+

TIP: Pour vérifier la version, connectez-vous à votre nœud de gestion et consultez le numéro de version d'élément dans la bannière de connexion. Si vous n'avez pas 11.3, voir link:task_hcc_upgrade_management_node.html["Mettez à niveau le nœud de gestion"].

* Vous avez mis à niveau vos services de gestion vers au moins la version 2.1.326.
+
Les mises à niveau utilisant NetApp Hybrid Cloud Control ne sont pas disponibles dans les versions précédentes de Service bundle.

* Vous avez vérifié que l'heure du système sur tous les nœuds est synchronisée et que le protocole NTP est correctement configuré pour le cluster de stockage et les nœuds. Chaque nœud doit être configuré avec un serveur de noms DNS dans l'interface utilisateur Web par nœud (`https://[IP address]:442`) sans erreurs de cluster non résolues liées à l'inclinaison temporelle.
* Vous avez prévu suffisamment de temps pour votre link:task_hcc_upgrade_element_software.html#element-upgrade-time["Logiciel Element"] et link:task_hcc_upgrade_storage_firmware.html#storage-firmware-upgrade["micrologiciel de stockage"] mises à niveau. Lorsque vous effectuez une mise à niveau vers Element 12.5 ou une version ultérieure, le processus de mise à niveau varie en fonction de la version du logiciel Element et des mises à jour du firmware.




== [[sys_upgrade]]séquence de mise à niveau du système

Utilisez la séquence suivante pour mettre à niveau votre système de stockage 100 % Flash SolidFire pour Element 12.5 ou une version ultérieure.

.Étapes
. link:task_hcc_update_management_services.html["Mise à jour des services de gestion à partir du cloud hybride Control"].
+

IMPORTANT: Si vous mettez à jour les services de gestion vers la version 2.16 ou ultérieure et que vous exécutez un nœud de gestion 11.3 à 11.8, vous devez augmenter la RAM de la machine virtuelle du nœud de gestion avant de mettre à jour les services de gestion.

+

IMPORTANT: Vous devez effectuer la mise à jour vers le dernier pack de services de gestion avant de mettre à niveau votre logiciel Element.

. link:task_hcc_upgrade_element_prechecks.html["Exécutez des vérifications de l'état du stockage Element avant la mise à niveau du stockage"].
. link:task_hcc_upgrade_element_software.html["Mettez à niveau le firmware de stockage et le logiciel Element"].
. link:task_hcc_upgrade_storage_firmware.html["(Facultatif) mettez uniquement à niveau le firmware de votre stockage Element"].
+

NOTE: Cette tâche peut être effectuée lorsqu'une nouvelle mise à niveau du firmware de stockage est disponible en dehors d'une version majeure.

. link:task_hcc_upgrade_management_node.html["(Facultatif) mettre à niveau votre nœud de gestion"].
+

NOTE: La mise à niveau du système d'exploitation du nœud de gestion n'est plus nécessaire pour mettre à niveau le logiciel Element sur le cluster de stockage. Si le nœud de gestion est la version 11.3 ou ultérieure, il vous suffit de mettre à niveau les services de gestion vers la dernière version pour effectuer les mises à niveau Element avec NetApp Hybrid Cloud Control. Suivez la procédure de mise à niveau du nœud de gestion pour votre scénario si vous souhaitez mettre à niveau le système d'exploitation du nœud de gestion pour d'autres raisons, telles que la résolution des problèmes de sécurité.

. link:task_vcp_upgrade_plugin.html["Mettez à niveau le plug-in Element pour vCenter Server"].


[discrete]
== Trouvez plus d'informations

* https://docs.netapp.com/us-en/vcp/index.html["Plug-in NetApp Element pour vCenter Server"^]
* https://www.netapp.com/data-storage/solidfire/documentation["Page Ressources SolidFire et Element"^]

