---
sidebar: sidebar 
permalink: mnode/task_mnode_enable_activeIQ.html 
summary: 'Vous pouvez utiliser le nœud de gestion (nœud M) pour activer Active IQ pour le stockage 100 % Flash de SolidFire.' 
keywords: netapp, Element, api, enable, active iq, activeiq 
---
= Surveillance Active IQ et NetApp
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Vous pouvez activer la surveillance du stockage Active IQ si ce n'est pas déjà le cas pendant l'installation ou la mise à niveau. Cette procédure peut être nécessaire si vous n'avez pas configuré SolidFire Active IQ pendant l'installation d'un système de stockage 100 % Flash SolidFire.

Le service Active IQ Collector transmet les données de configuration et les metrics de performance du cluster logiciel Element à SolidFire Active IQ pour un reporting historique et un contrôle des performances en temps quasi réel. Le service de surveillance NetApp permet de transférer les défaillances de cluster de stockage vers vCenter afin d'en informer les alertes.

.Avant de commencer
* Certaines fonctions dans Active IQ, par exemple la qualité de service (QoS), exigent que l'élément 11.3 ou une version ultérieure fonctionne correctement. Pour confirmer que vous êtes capable d'utiliser toutes les fonctions Active IQ, NetApp recommande :
+
** Votre cluster de stockage exécute NetApp Element version 11.3 ou ultérieure.
** Vous avez déployé un nœud de gestion exécutant la version 11.3 ou ultérieure.


* Vous avez accès à Internet. Le service Active IQ Collector ne peut pas être utilisé à partir de sites sombres qui n'ont pas de connectivité externe.


.Étapes
. Procurez-vous l'ID de ressource de base pour l'installation :
+
.. Ouvrez l'interface utilisateur de l'API REST du service d'inventaire sur le nœud de gestion :
+
[listing]
----
https://<ManagementNodeIP>/inventory/1/
----
.. Sélectionnez *Authorise* et procédez comme suit :
+
... Saisissez le nom d'utilisateur et le mot de passe du cluster.
... Saisissez l'ID client en tant que `mnode-client`.
... Sélectionnez *Autoriser* pour démarrer une session.
... Fermez la fenêtre.


.. Dans l'interface utilisateur de l'API REST, sélectionnez *OBTENIR ​/installations*.
.. Sélectionnez *essayez-le*.
.. Sélectionnez *Exécuter*.
.. À partir du corps de réponse du code 200, copiez le `id` pour l'installation.
+
[listing, subs="+quotes"]
----
{
  "installations": [
    {
      "_links": {
        "collection": "https://10.111.211.111/inventory/1/installations",
        "self": "https://10.111.217.111/inventory/1/installations/abcd01e2-ab00-1xxx-91ee-12f111xxc7x0x"
      },
      *"id": "abcd01e2-ab00-1xxx-91ee-12f111xxc7x0x",*
----
+

NOTE: Votre installation dispose d'une configuration de ressource de base créée lors de l'installation ou de la mise à niveau.



. Activer la télémétrie :
+
.. Accédez à l'interface de l'API du service mNode sur le nœud de gestion en entrant l'adresse IP du nœud de gestion suivie de `/mnode`:
+
[listing]
----
https://<ManagementNodeIP>/mnode
----
.. Sélectionnez *Authorise* ou une icône de verrouillage et procédez comme suit :
+
... Saisissez le nom d'utilisateur et le mot de passe du cluster.
... Saisissez l'ID client en tant que `mnode-client`.
... Sélectionnez *Autoriser* pour démarrer une session.
... Fermez la fenêtre.


.. Configurer l'actif de base :
+
... Sélectionnez *PUT /Assets/{ASSET_ID}*.
... Sélectionnez *essayez-le*.
... Entrez la valeur suivante dans la charge JSON :
+
[listing]
----
{
"telemetry_active": true
"config": {}
}
----
... Saisissez l'ID de base de l'étape précédente dans *Asset_ID*.
... Sélectionnez *Exécuter*.
+
Le service Active IQ redémarre automatiquement dès que les ressources sont modifiées. La modification des actifs entraîne un court délai avant l'application des paramètres.





. Si ce n'est pas encore fait, ajoutez un actif de contrôleur vCenter pour le contrôle du cloud hybride NetApp au nœud de gestion des ressources connues :
+

NOTE: Une ressource de contrôleur est requise pour les services de surveillance NetApp.

+
.. Sélectionnez *POST /Assets/{ASSET_ID}/contrôleurs* pour ajouter un sous-actif de contrôleur.
.. Sélectionnez *essayez-le*.
.. Saisissez l'ID d'actif de base parent que vous avez copié dans le presse-papiers dans le champ *Asset_ID*.
.. Entrer les valeurs de charge utile requises avec `type` comme `vCenter` Et vCenter.
+
[listing]
----
{
"username": "string",
"password": "string",
"ip": "string",
"type": "vCenter",
"host_name": "string",
"config": {}
}
----
+

NOTE: `ip` Est l'adresse IP vCenter.

.. Sélectionnez *Exécuter*.




[discrete]
== Trouvez plus d'informations

* https://docs.netapp.com/us-en/vcp/index.html["Plug-in NetApp Element pour vCenter Server"^]
* https://docs.netapp.com/us-en/element-software/index.html["Documentation SolidFire et Element"]

