---
permalink: concepts/concept_intro_product_overview.html 
sidebar: sidebar 
keywords:  
summary: 'Un système de stockage 100 % Flash SolidFire comprend des composants matériels distincts \(disques et nœuds\) regroupés dans un seul pool de ressources de stockage. Ce cluster unifié présente comme un système de stockage unique utilisable par des clients externes, et est géré à l"aide du logiciel NetApp Element.' 
---
= Présentation du produit
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Un système de stockage 100 % Flash SolidFire comprend des composants matériels distincts (disques et nœuds) regroupés dans un seul pool de ressources de stockage. Ce cluster unifié présente comme un système de stockage unique utilisable par des clients externes, et est géré à l'aide du logiciel NetApp Element.

Grâce à l'interface Element, aux API ou à d'autres outils de gestion, vous pouvez surveiller la capacité et les performances de stockage du cluster SolidFire et gérer les activités de stockage sur une infrastructure mutualisée.



== Fonctionnalités SolidFire

Le système SolidFire offre les fonctionnalités suivantes :

* Offre un stockage haute performance pour votre infrastructure de cloud privé à grande échelle
* Une évolutivité flexible qui permet de répondre à l'évolution des besoins en stockage
* Utilise une interface logicielle de gestion du stockage Element basée sur des API
* Garantit les performances à l'aide des règles de qualité de service
* Équilibrage automatique de la charge sur l'ensemble des nœuds du cluster inclus
* Rééquilibrage automatique des clusters lors de l'ajout ou de la suppression de nœuds




== Déploiement SolidFire

Nœuds de stockage fournis par NetApp et intégrés au logiciel NetApp Element

link:../concepts/concept_solidfire_concepts_solidfire_architecture_overview.html["Présentation de l'architecture de stockage 100 % Flash de SolidFire"]



== Trouvez plus d'informations

* https://www.netapp.com/data-storage/solidfire/["Présentation du stockage 100 % Flash de SolidFire"^]
* https://docs.netapp.com/us-en/element-software/index.html["Documentation SolidFire et Element"]
* https://docs.netapp.com/us-en/vcp/index.html["Plug-in NetApp Element pour vCenter Server"^]

