---
permalink: storage/concept_system_manage_cluster_terms_manage_the_terms_of_use_banner.html 
sidebar: sidebar 
keywords: element, terms of use, banner, config, edit, terms of use, disable, enable 
summary: 'Vous pouvez activer, modifier ou configurer une bannière contenant un message pour l"utilisateur.' 
---
= Gérez la bannière Conditions d'utilisation
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez activer, modifier ou configurer une bannière contenant un message pour l'utilisateur.

 the Terms of Use banner
 the Terms of Use banner
 the Terms of Use banner



== Activez la bannière Conditions d'utilisation

Vous pouvez activer une bannière Conditions d'utilisation qui s'affiche lorsqu'un utilisateur se connecte à l'interface utilisateur Element. Lorsque l'utilisateur clique sur la bannière, une boîte de dialogue de texte contenant le message que vous avez configuré pour le cluster s'affiche. La bannière peut être rejetée à tout moment.

Vous devez disposer des privilèges d'administrateur de cluster pour activer la fonctionnalité Conditions d'utilisation.

. Cliquez sur *utilisateurs* > *Conditions d'utilisation*.
. Dans le formulaire *Conditions d'utilisation*, entrez le texte à afficher pour la boîte de dialogue Conditions d'utilisation.
+

NOTE: Ne pas dépasser 4096 caractères.

. Cliquez sur *Activer*.




== Modifiez la bannière Conditions d'utilisation

Vous pouvez modifier le texte qu'un utilisateur voit lorsqu'il sélectionne la bannière de connexion Conditions d'utilisation.

.Ce dont vous avez besoin, 8217;ll
* Vous devez disposer des privilèges d'administrateur de cluster pour configurer les conditions d'utilisation.
* Assurez-vous que la fonctionnalité Conditions d'utilisation est activée.


.Étapes
. Cliquez sur *utilisateurs* > *Conditions d'utilisation*.
. Dans la boîte de dialogue *Conditions d'utilisation*, modifiez le texte que vous souhaitez afficher.
+

NOTE: Ne pas dépasser 4096 caractères.

. Cliquez sur *Enregistrer les modifications*.




== Désactivez la bannière Conditions d'utilisation

Vous pouvez désactiver la bannière Conditions d'utilisation. Lorsque la bannière est désactivée, l'utilisateur n'est plus invité à accepter les conditions d'utilisation lors de l'utilisation de l'interface utilisateur Element.

.Ce dont vous avez besoin, 8217;ll
* Vous devez disposer des privilèges d'administrateur de cluster pour configurer les conditions d'utilisation.
* Assurez-vous que les Conditions d'utilisation sont activées.


.Étapes
. Cliquez sur *utilisateurs* > *Conditions d'utilisation*.
. Cliquez sur *Désactiver*.

