---
permalink: storage/concept_data_protection.html 
sidebar: sidebar 
keywords: data protection, protect your data, snapshots, replication, back up 
summary: 'Le logiciel NetApp Element vous permet de protéger vos données de différentes manières : il offre des fonctionnalités telles que les snapshots de volumes individuels ou de groupes de volumes, la réplication entre les clusters et les volumes exécutés sur Element, ou la réplication vers les systèmes ONTAP.' 
---
= Protégez vos données
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Le logiciel NetApp Element vous permet de protéger vos données de différentes manières : il offre des fonctionnalités telles que les snapshots de volumes individuels ou de groupes de volumes, la réplication entre les clusters et les volumes exécutés sur Element, ou la réplication vers les systèmes ONTAP.

* *Snapshots*
+
La protection des données snapshot uniquement réplique les données modifiées au point spécifique de temps sur un cluster distant. Seuls les snapshots créés sur le cluster source sont répliqués. Les écritures actives du volume source ne sont pas.

+
xref:task_data_protection_using_volume_snapshots.adoc[Utilisation des snapshots de volumes pour la protection des données]

* *Réplication à distance entre les clusters et les volumes fonctionnant sur Element*
+
Il peut répliquer des données de volume de manière synchrone ou asynchrone depuis l'un des clusters d'une paire de clusters qui s'exécute sous Element pour les scénarios de basculement et de retour arrière.

+
xref:task_replication_perform_remote_replication_between_element_clusters.adoc[Réplication à distance entre les clusters exécutant le logiciel NetApp Element]

* *La réplication entre des clusters Element et ONTAP à l'aide de la technologie SnapMirror*
+
Avec la technologie NetApp SnapMirror, vous pouvez répliquer les snapshots pris en utilisant Element vers ONTAP à des fins de reprise après incident. Dans une relation SnapMirror, Element est un terminal et ONTAP l'autre.

+
xref:task_snapmirror_use_replication_between_element_and_ontap_clusters.adoc[Utilisez la réplication SnapMirror entre les clusters Element et ONTAP]

* *Sauvegarde et restauration de volumes à partir de magasins d'objets SolidFire, S3 ou Swift*
+
Vous pouvez sauvegarder et restaurer des volumes dans d'autres systèmes de stockage SolidFire, ainsi que des magasins d'objets secondaires compatibles avec Amazon S3 ou OpenStack Swift.

+
xref:task_data_protection_back_up_and_restore_volumes.adoc[Sauvegarde et restauration de volumes dans des magasins d'objets SolidFire, S3 ou Swift]





== Pour en savoir plus

* https://docs.netapp.com/us-en/element-software/index.html["Documentation SolidFire et Element"]
* https://docs.netapp.com/us-en/vcp/index.html["Plug-in NetApp Element pour vCenter Server"^]

