---
permalink: storage/concept_system_manage_drives_managing_drives.html 
sidebar: sidebar 
keywords: drives, manage, cluster, element ui, remove drives 
summary: 'Chaque nœud contient un ou plusieurs disques physiques utilisés pour stocker une partie des données pour le cluster. Le cluster utilise la capacité et les performances du disque une fois le disque ajouté au cluster. Vous pouvez gérer les disques à l"aide de l"interface utilisateur Element.' 
---
= Gérer les disques
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Chaque nœud contient un ou plusieurs disques physiques utilisés pour stocker une partie des données pour le cluster. Le cluster utilise la capacité et les performances du disque une fois le disque ajouté au cluster. Vous pouvez gérer les disques à l'aide de l'interface utilisateur Element.



== Détails sur le disque

La page lecteurs de l'onglet Cluster fournit la liste des lecteurs actifs du cluster. Vous pouvez filtrer la page en sélectionnant dans les onglets actif, disponible, Suppression, Effacement et échec.

Lorsque vous initialisez un cluster, la liste des disques actifs est vide. Vous pouvez ajouter des disques non attribués à un cluster et dans l'onglet disponible après la création d'un nouveau cluster SolidFire.

Les éléments suivants apparaissent dans la liste des lecteurs actifs.

* *ID de lecteur*
+
Numéro séquentiel attribué au disque.

* *ID de nœud*
+
Numéro de nœud attribué lorsque ce nœud est ajouté au cluster.

* *Nom du noeud*
+
Nom du nœud qui héberge le disque.

* *Slot*
+
Numéro de logement où le lecteur est physiquement situé.

* *Capacité*
+
Taille du lecteur, en Go.

* *Série*
+
Numéro de série du disque.

* *Usure restante*
+
L'indicateur de niveau d'usure.

+
Le système de stockage indique l'usure approximative disponible sur chaque disque SSD pour l'écriture et l'effacement des données. Un disque qui a consommé 5 % de ses cycles d'écriture et d'effacement prévus signale l'usure restante de 95 %. Le système n'actualise pas automatiquement les informations relatives à l'usure des disques ; vous pouvez actualiser ou fermer et recharger la page pour actualiser les informations.

* *Type*
+
Type de disque. Ce type peut être un bloc ou des métadonnées.





== Pour en savoir plus

* https://docs.netapp.com/us-en/element-software/index.html["Documentation SolidFire et Element"]
* https://docs.netapp.com/us-en/vcp/index.html["Plug-in NetApp Element pour vCenter Server"^]

