---
permalink: storage/concept-element-replication-create-custom-replication-policy.html 
sidebar: sidebar 
keywords: ontap, cli, create, custom, replication, policy, relationship, 
summary: 'Vous pouvez créer une stratégie de réplication personnalisée si la stratégie par défaut d"une relation n"est pas appropriée.' 
---
= Création d'une règle de réplication personnalisée
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez utiliser une règle par défaut ou personnalisée lorsque vous créez une relation de réplication. Pour une règle de réplication unifiée personnalisée, vous devez définir une ou plusieurs _règles_ qui déterminent quelles copies Snapshot sont transférées lors de l'initialisation et de la mise à jour.

Vous pouvez créer une stratégie de réplication personnalisée si la stratégie par défaut d'une relation n'est pas appropriée. Vous pouvez par exemple compresser les données dans un transfert réseau ou modifier le nombre de tentatives effectuées par SnapMirror pour transférer des copies Snapshot.

.Description de la tâche
Le _policy type_ de la règle de réplication détermine le type de relation qu'elle prend en charge. Le tableau ci-dessous présente les types de stratégies disponibles.

[cols="2*"]
|===


| Type de règle | Type de relation 


 a| 
mise en miroir asynchrone
 a| 
Reprise sur incident SnapMirror



 a| 
coffre-fort
 a| 
Réplication unifiée

|===
.Étape
. Création d'une règle de réplication personnalisée :
+
`snapmirror policy create -vserver _SVM_ -policy policy -type async-mirror|mirror-vault -comment _comment_ -tries _transfer_tries_ -transfer-priority low|normal -is-network-compression-enabled true|false`

+
Pour connaître la syntaxe complète de la commande, reportez-vous à la page man.

+
À partir de ONTAP 9.5, vous pouvez spécifier la planification de la création d'une planification de copie Snapshot commune pour les relations SnapMirror synchrone à l'aide du `-common-snapshot-schedule` paramètre. Par défaut, la planification commune des copies Snapshot pour les relations SnapMirror synchrone est d'une heure. La planification des copies Snapshot pour les relations SnapMirror synchrone peut être définie sur une valeur comprise entre 30 minutes et deux heures.

+
L'exemple suivant crée une règle de réplication personnalisée pour SnapMirror DR qui permet la compression réseau pour les transferts de données :

+
[listing]
----
cluster_dst::> snapmirror policy create -vserver svm1 -policy DR_compressed -type async-mirror -comment “DR with network compression enabled” -is-network-compression-enabled true
----
+
L'exemple suivant crée une règle de réplication personnalisée pour la réplication unifiée :

+
[listing]
----
cluster_dst::> snapmirror policy create -vserver svm1 -policy my_unified -type mirror-vault
----


.Une fois que vous avez terminé
Pour les types de règles « miroir-vault », vous devez définir des règles qui déterminent quelles copies Snapshot sont transférées au cours de l'initialisation et de la mise à jour.

Utilisez `snapmirror policy show` la commande pour vérifier que la règle SnapMirror a été créée. Pour connaître la syntaxe complète de la commande, reportez-vous à la page man.
