---
permalink: storage/concept_system_manage_virtual_manage_virtual_networks.html 
sidebar: sidebar 
keywords: virtual networks, manage, traffic, clients, vlan tagging 
summary: 'La mise en réseau virtuelle dans le stockage SolidFire permet la connexion au cluster du trafic entre plusieurs clients sur des réseaux logiques distincts. Les connexions au cluster sont isolées sur la pile réseau via l"utilisation de balisage VLAN.' 
---
= Gérer des réseaux virtuels
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La mise en réseau virtuelle dans le stockage SolidFire permet la connexion au cluster du trafic entre plusieurs clients sur des réseaux logiques distincts. Les connexions au cluster sont isolées sur la pile réseau via l'utilisation de balisage VLAN.



== Trouvez plus d'informations

* xref:task_system_manage_virtual_add_a_virtual_network.adoc[Ajouter un réseau virtuel]
* xref:task_system_manage_virtual_enable_virtual_routing_and_forwarding.adoc[Activer le routage et le transfert virtuels]
* xref:task_system_manage_virtual_edit_a_virtual_network.adoc[Modifier un réseau virtuel]
* xref:task_system_manage_virtual_edit_vrf_vlans.adoc[Modifier les VLAN VRF]
* xref:task_system_manage_virtual_delete_a_virtual_network.adoc[Supprimer un réseau virtuel]

