---
permalink: storage/reference_system_manage_snmp_snmp_details.html 
sidebar: sidebar 
keywords: snmp, overview, reference, mib, settings, trap 
summary: 'Sur la page SNMP de l"onglet Cluster, vous pouvez afficher les informations suivantes.' 
---
= En savoir plus sur SNMP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez configurer le protocole SNMP (simple Network Management Protocol) dans votre cluster.

Vous pouvez sélectionner un demandeur SNMP, sélectionner la version de SNMP à utiliser, identifier l'utilisateur SNMP user based Security Model (USM) et configurer les traps pour surveiller le cluster SolidFire. Vous pouvez également afficher les fichiers de la base d'informations de gestion et y accéder.


NOTE: Vous pouvez utiliser les adresses IPv4 et IPv6.



== Détails SNMP

Sur la page SNMP de l'onglet Cluster, vous pouvez afficher les informations suivantes.

* *MIB SNMP*
+
Les fichiers MIB qui sont disponibles pour vous à visualiser ou télécharger.

* *Paramètres SNMP généraux*
+
Vous pouvez activer ou désactiver SNMP. Après avoir activé SNMP, vous pouvez choisir la version à utiliser. Si vous utilisez la version 2, vous pouvez ajouter des requestors et, si vous utilisez la version 3, vous pouvez configurer des utilisateurs USM.

* *Paramètres de déroutement SNMP*
+
Vous pouvez identifier les recouvrements que vous souhaitez capturer. Vous pouvez définir l'hôte, le port et la chaîne de communauté pour chaque destinataire de l'interruption.


