---
permalink: storage/reference_replication_volume_pairing_warnings.html 
sidebar: sidebar 
keywords: volume warnings, messages, replication, data protection 
summary: 'La page paires de volumes de l"onglet protection des données fournit ces messages après la paire de volumes. Ces messages peuvent s"afficher aux extrémités source et cible de la paire \(sauf indication contraire\) dans la vue liste volumes répliqués.' 
---
= Avertissements de couplage de volume
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La page paires de volumes de l'onglet protection des données fournit ces messages après la paire de volumes. Ces messages peuvent s'afficher aux extrémités source et cible de la paire (sauf indication contraire) dans la vue de liste volumes de réplication.

* *PausedClusterFull*
+
Étant donné que le cluster cible est plein, la réplication source et le transfert de données en bloc ne peuvent pas se faire. Le message s'affiche uniquement à l'extrémité source de la paire.

* *PausedExcededMaxSnapshotCount*
+
Le volume cible dispose déjà du nombre maximal de snapshots et ne peut pas répliquer d'autres snapshots.

* *PausedManual*
+
Le volume local a été mis en pause manuellement. Il doit être mis en pause avant la reprise de la réplication.

* *PausedManualRemote*
+
Le volume distant est en mode pause manuelle. Intervention manuelle requise pour annuler la pause du volume distant avant la reprise de la réplication.

* *PausedMisConfigured*
+
Attente d'une source et d'une cible actives. Intervention manuelle requise pour reprendre la réplication.

* *PausedQoS*
+
La qualité de service cible n'a pas pu supporter les E/S entrantes. Reprises automatiques de la réplication. Le message s'affiche uniquement à l'extrémité source de la paire.

* *PausedSlowLink*
+
Liaison lente détectée et interruption de la réplication. Reprises automatiques de la réplication. Le message s'affiche uniquement à l'extrémité source de la paire.

* *PausedVolumeSizeMatch*
+
La taille du volume cible n'est pas identique à celle du volume source.

* *PausedXCopy*
+
Une commande SCSI XCOPY est envoyée vers un volume source. La commande doit se terminer avant que la réplication puisse reprendre. Le message s'affiche uniquement à l'extrémité source de la paire.

* *StoppedMisConfigured*
+
Une erreur de configuration permanente a été détectée. Le volume distant a été purgé ou non apparié. Aucune action corrective n'est possible ; une nouvelle association doit être établie.


