---
permalink: storage/reference_system_manage_fips_ssl_cipher_changes.html 
sidebar: sidebar 
keywords: fips, ssl ciphers, 140-2, encryption algorithms 
summary: Le chiffrement SSL sont des algorithmes de cryptage utilisés par les hôtes pour établir une communication sécurisée. Le logiciel Element prend en charge les chiffrements standard et non standard lorsque le mode FIPS 140-2 est activé. 
---
= Chiffrement SSL
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Le chiffrement SSL sont des algorithmes de cryptage utilisés par les hôtes pour établir une communication sécurisée. Le logiciel Element prend en charge les chiffrements standard et non standard lorsque le mode FIPS 140-2 est activé.

Les listes suivantes fournissent le chiffrement SSL (Secure Socket Layer) standard pris en charge par le logiciel Element et le chiffrement SSL pris en charge lorsque le mode FIPS 140-2 est activé :

* *FIPS 140-2 désactivé*
+
TLS_DHE_RSA_WITH_AES_128_CBC_SHA256 (DH 2048) - A.

+
TLS_DHE_RSA_WITH_AES_128_GCM_SHA256 (DH 2048) - A.

+
TLS_DHE_RSA_WITH_AES_256_CBC_SHA256 (DH 2048) - A.

+
TLS_DHE_RSA_WITH_AES_256_GCM_SHA384 (DH 2048) - A.

+
TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256 (SECP256R1) - A.

+
TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256 (SECP256R1) - A.

+
TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384 (SECP256R1) - A.

+
TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384 (SECP256R1) - A.

+
TLS_RSA_WITH_3DES_EDE_CBC_SHA (RSA 2048) - C

+
TLS_RSA_WITH_AES_128_CBC_SHA (RSA 2048) - A.

+
TLS_RSA_WITH_AES_128_CBC_SHA256 (RSA 2048) - A.

+
TLS_RSA_WAS_AES_128_GCM_SHA256 (RSA 2048) - A.

+
TLS_RSA_WITH_AES_256_CBC_SHA (RSA 2048) - A.

+
TLS_RSA_WITH_AES_256_CBC_SHA256 (RSA 2048) - A.

+
TLS_RSA_WITH_AES_256_GCM_SHA384 (RSA 2048) - A.

+
TLS_RSA_WITH_CAMELLIA_128_CBC_SHA (RSA 2048) - A

+
TLS_RSA_WITH_CAMELLIA_256_CBC_SHA (RSA 2048) - A

+
TLS_RSA_WITH_IDEA_CBC_SHA (RSA 2048) - A.

+
TLS_RSA_WITH_RC4_128_MD5 (RSA 2048) - C

+
TLS_RSA_WITH_RC4_128_SHA (RSA 2048) - C.

+
TLS_RSA_WITH_SEED_CBC_SHA (RSA 2048) - A.

* *FIPS 140-2 activé*
+
TLS_DHE_RSA_WITH_AES_128_CBC_SHA256 (DH 2048) - A.

+
TLS_DHE_RSA_WITH_AES_128_GCM_SHA256 (DH 2048) - A.

+
TLS_DHE_RSA_WITH_AES_256_CBC_SHA256 (DH 2048) - A.

+
TLS_DHE_RSA_WITH_AES_256_GCM_SHA384 (DH 2048) - A.

+
TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256 (SECT571R1) - A.

+
TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256 (SECP256R1) - A.

+
TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256 (SECP256R1) - A.

+
TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256 (SECT571R1) - A.

+
TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384 (SECT571R1) - A.

+
TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384 (SECP256R1) - A.

+
TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384 (SECP256R1) - A.

+
TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384 (SECT571R1) - A.

+
TLS_RSA_WITH_3DES_EDE_CBC_SHA (RSA 2048) - C

+
TLS_RSA_WITH_AES_128_CBC_SHA (RSA 2048) - A.

+
TLS_RSA_WITH_AES_128_CBC_SHA256 (RSA 2048) - A.

+
TLS_RSA_WAS_AES_128_GCM_SHA256 (RSA 2048) - A.

+
TLS_RSA_WITH_AES_256_CBC_SHA (RSA 2048) - A.

+
TLS_RSA_WITH_AES_256_CBC_SHA256 (RSA 2048) - A.

+
TLS_RSA_WITH_AES_256_GCM_SHA384 (RSA 2048) - A.





== Trouvez plus d'informations

xref:task_system_manage_fips_enable_fips_140_2_for_https.adoc[Activez FIPS 140-2 pour HTTPS sur votre cluster]
