---
permalink: storage/task-element-replication-create-replication-relationship.html 
sidebar: sidebar 
keywords: ontap, cli, create, relationship, element, source, destination 
summary: 'Vous pouvez utiliser SnapMirror pour répliquer les copies Snapshot d"un volume Element vers un système de destination ONTAP. En cas d"incident au niveau du système Element, vous pouvez délivrer les données aux clients via le système ONTAP, puis réactiver le volume source Element une fois que le service est restauré.' 
---
= Création d'une relation entre une source d'élément et une destination ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La relation entre le volume source du stockage primaire et le volume de destination du stockage secondaire est appelée « relation de protection des données ». Vous pouvez utiliser `snapmirror create` la commande pour créer une relation de protection des données entre une source Element et une destination ONTAP, ou entre une source ONTAP et une destination Element.

Vous pouvez utiliser SnapMirror pour répliquer les copies Snapshot d'un volume Element vers un système de destination ONTAP. En cas d'incident au niveau du système Element, vous pouvez délivrer les données aux clients via le système ONTAP, puis réactiver le volume source Element une fois que le service est restauré.

.Avant de commencer
* Le nœud Element contenant le volume à répliquer doit avoir été accessible à ONTAP.
* Le volume Element doit avoir été activé pour la réplication SnapMirror.
* Si vous utilisez le type de règle « miroir-vault », une étiquette SnapMirror doit avoir été configurée pour que les copies Snapshot d'élément soient répliquées.
+
[NOTE]
====
Vous ne pouvez effectuer cette tâche que dans link:concept_snapmirror_labels.html["Interface utilisateur web du logiciel Element"]ou à l'aide de link:../api/concept_element_api_snapshots_overview.html["Méthodes API"].

====


.Description de la tâche
Vous devez spécifier le chemin source de l'élément sous la forme `<hostip:>/lun/<name>`, où « lun » est la chaîne réelle « lun » et `name` le nom du volume d'élément.

Un volume Element équivaut à peu près à un LUN ONTAP. SnapMirror crée un LUN avec le nom du volume Element lorsqu'une relation de protection des données entre le logiciel Element et ONTAP est initialisée. SnapMirror réplique les données vers une LUN existante si la LUN répond aux exigences en matière de réplication depuis le logiciel Element vers ONTAP.

Les règles de réplication sont les suivantes :

* Un volume ONTAP peut contenir uniquement des données d'un volume Element.
* Vous ne pouvez pas répliquer les données depuis un volume ONTAP vers plusieurs volumes Element.


Dans ONTAP 9.3 et versions antérieures, un volume de destination peut contenir jusqu'à 251 copies snapshot. Dans ONTAP 9.4 et versions ultérieures, un volume de destination peut contenir jusqu'à 1019 copies snapshot.

.Étape
. Depuis le cluster destination, créer une relation de réplication depuis une source Element vers une destination ONTAP :
+
`snapmirror create -source-path <hostip:>/lun/<name> -destination-path <SVM:volume>|<cluster://SVM/volume> -type XDP -schedule schedule -policy <policy>`

+
Pour connaître la syntaxe complète de la commande, reportez-vous à la page man.

+
L'exemple suivant illustre la création d'une relation SnapMirror DR à l'aide de la règle par défaut `MirrorLatest` :

+
[listing]
----
cluster_dst::> snapmirror create -source-path 10.0.0.11:/lun/0005 -destination-path svm_backup:volA_dst -type XDP -schedule my_daily -policy MirrorLatest
----
+
L'exemple suivant illustre la création d'une relation de réplication unifiée à l'aide de la règle par défaut `MirrorAndVault` :

+
[listing]
----
cluster_dst:> snapmirror create -source-path 10.0.0.11:/lun/0005 -destination-path svm_backup:volA_dst -type XDP -schedule my_daily -policy MirrorAndVault
----
+
L'exemple suivant illustre la création d'une relation de réplication unifiée à l'aide de la `Unified7year` règle :

+
[listing]
----
cluster_dst::> snapmirror create -source-path 10.0.0.11:/lun/0005 -destination-path svm_backup:volA_dst -type XDP -schedule my_daily -policy Unified7year
----
+
L'exemple suivant illustre la création d'une relation de réplication unifiée à l'aide de la règle personnalisée `my_unified` :

+
[listing]
----
cluster_dst::> snapmirror create -source-path 10.0.0.11:/lun/0005 -destination-path svm_backup:volA_dst -type XDP -schedule my_daily -policy my_unified
----


.Une fois que vous avez terminé
Utiliser `snapmirror show` la commande pour vérifier que la relation SnapMirror a été créée. Pour connaître la syntaxe complète de la commande, reportez-vous à la page man.
