---
permalink: storage/task-element-replication-create-relationship-element-destination.html 
sidebar: sidebar 
keywords: ontap, cli, create, relationship, replication, snapmirror 
summary: 'Depuis la version ONTAP 9.4, vous pouvez utiliser SnapMirror pour répliquer les copies Snapshot d"une LUN créée dans une source ONTAP vers une destination Element. Il est possible d"utiliser le LUN pour migrer les données d"ONTAP vers le logiciel Element.' 
---
= Création d'une relation entre une source ONTAP et une destination Element
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Depuis la version ONTAP 9.4, vous pouvez utiliser SnapMirror pour répliquer les copies Snapshot d'une LUN créée dans une source ONTAP vers une destination Element. Il est possible d'utiliser le LUN pour migrer les données d'ONTAP vers le logiciel Element.

.Avant de commencer
* Le nœud de destination de l'élément doit avoir été accessible à ONTAP.
* Le volume Element doit avoir été activé pour la réplication SnapMirror.


.Description de la tâche
Vous devez spécifier le chemin de destination de l'élément sous la forme `<hostip:>/lun/<name>`, où « lun » est la chaîne réelle « lun » et `name` le nom du volume d'élément.

Les règles de réplication sont les suivantes :

* La relation de réplication doit avoir une règle de type « async-mirror ».
+
Vous pouvez utiliser une stratégie par défaut ou personnalisée.

* Seules les LUN iSCSI sont prises en charge.
* Vous ne pouvez pas répliquer plusieurs LUN depuis un volume ONTAP vers un volume Element.
* Vous ne pouvez pas répliquer un LUN depuis un volume ONTAP vers plusieurs volumes Element.


.Étape
. Créer une relation de réplication depuis une source ONTAP vers une destination Element :
+
`snapmirror create -source-path <SVM:volume>|<cluster://SVM/volume> -destination-path <hostip:>/lun/<name> -type XDP -schedule schedule -policy <policy>`

+
Pour connaître la syntaxe complète de la commande, reportez-vous à la page man.

+
L'exemple suivant illustre la création d'une relation SnapMirror DR à l'aide de la règle par défaut `MirrorLatest` :

+
[listing]
----
cluster_dst::> snapmirror create -source-path svm_1:volA_dst -destination-path 10.0.0.11:/lun/0005 -type XDP -schedule my_daily -policy MirrorLatest
----
+
L'exemple suivant illustre la création d'une relation SnapMirror DR à l'aide de la règle personnalisée `my_mirror` :

+
[listing]
----
cluster_dst::> snapmirror create -source-path svm_1:volA_dst -destination-path 10.0.0.11:/lun/0005 -type XDP -schedule my_daily -policy my_mirror
----


.Une fois que vous avez terminé
Utiliser `snapmirror show` la commande pour vérifier que la relation SnapMirror a été créée. Pour connaître la syntaxe complète de la commande, reportez-vous à la page man.
