---
permalink: storage/task_post_deploy_configure_system_options.html 
sidebar: sidebar 
keywords: deployment, post deployment options, credentials, components, FIPS security, passwords, MFA, multifactor authentication, mutli-factor authentication, security, EKM, key management, external key management, FIPS 
summary: 'Une fois le système SolidFire configuré, vous pouvez effectuer certaines tâches facultatives. En outre, vous pouvez configurer les paramètres d"authentification multifacteur, de gestion externe des clés et de sécurité Federal information Processing Standards \(FIPS\).' 
---
= Configuration des options du système SolidFire après le déploiement
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Une fois le système SolidFire configuré, vous pouvez effectuer certaines tâches facultatives.

Si vous modifiez les informations d'identification dans le système, vous pouvez connaître l'impact sur les autres composants.

En outre, vous pouvez configurer les paramètres de l'authentification multifacteur, de la gestion externe des clés et de la sécurité FIPS (Federal information Processing Standards). Vous devez également examiner la mise à jour des mots de passe si nécessaire.



== Trouvez plus d'informations

* link:task_post_deploy_credentials.html["Modifiez les identifiants dans NetApp HCI et NetApp SolidFire"]
* link:reference_post_deploy_change_default_ssl_certificate.html["Modifiez le certificat SSL par défaut du logiciel Element"]
* link:task_post_deploy_credential_change_ipmi_password.html["Modifiez le mot de passe IPMI pour les nœuds"]
* link:concept_system_manage_mfa_enable_multi_factor_authentication.html["Activez l'authentification multifacteur"]
* link:concept_system_manage_key_get_started_with_external_key_management.html["Commencez par une gestion externe des clés"]
* link:task_system_manage_fips_create_a_cluster_supporting_fips_drives.html["Créez un cluster prenant en charge les disques FIPS"]

