---
permalink: storage/task_data_protection_restore_volume_from_backup_on_openstack_swift.html 
sidebar: sidebar 
keywords: volume restore, openstack swift object store 
summary: 'Vous pouvez restaurer un volume à partir d"une sauvegarde dans un magasin d"objets OpenStack Swift.' 
---
= Restauration d'un volume à partir d'une sauvegarde sur un magasin d'objets OpenStack Swift
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez restaurer un volume à partir d'une sauvegarde dans un magasin d'objets OpenStack Swift.

. Cliquez sur *Rapport* > *Journal des événements*.
. Recherchez l'événement de sauvegarde qui a créé la sauvegarde à restaurer.
. Dans la colonne *Détails* de l'événement, cliquez sur *Afficher les détails*.
. Copiez les informations du manifeste dans le presse-papiers.
. Cliquez sur *Management* > *volumes*.
. Cliquez sur l'icône actions du volume à restaurer.
. Dans le menu résultant, cliquez sur *Restaurer depuis*.
. Dans la boîte de dialogue *Integrated Restore* sous *Restore from*, sélectionnez *Swift*.
. Sélectionnez l'option correspondant à la sauvegarde sous *format de données* :
+
** *Natif* : format compressé lisible uniquement par les systèmes de stockage SolidFire.
** *Non compressé* : format non compressé compatible avec d'autres systèmes.


. Saisissez une URL à utiliser pour accéder au magasin d'objets dans le champ *URL*.
. Entrez un nom d'utilisateur pour le compte dans le champ *Nom d'utilisateur*.
. Saisissez la clé d'authentification du compte dans le champ *clé d'authentification*.
. Entrez le nom du conteneur dans lequel la sauvegarde est stockée dans le champ *Container*.
. Collez les informations du manifeste dans le champ *manifest*.
. Cliquez sur *Start Write*.

