---
permalink: storage/task_system_manage_fips_create_a_cluster_supporting_fips_drives.html 
sidebar: sidebar 
keywords: fips, security, federal information processing standards, 140-2, cluster, create 
summary: 'La sécurité devient de plus en plus cruciale pour le déploiement de solutions dans de nombreux environnements clients. Les normes fédérales de traitement de l"information \(FIPS\) sont des normes relatives à la sécurité et à l"interopérabilité des ordinateurs. Le chiffrement certifié FIPS 140-2 pour les données au repos est un composant de la solution de sécurité globale.' 
---
= Préparer le cluster Element pour la fonction de disques FIPS
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La sécurité devient de plus en plus cruciale pour le déploiement de solutions dans de nombreux environnements clients. La norme FIPS (Federal information Processing Standards) est une norme en matière de sécurité et d'interopérabilité des ordinateurs. Le chiffrement certifié FIPS 140-2 pour les données au repos est un composant de la solution de sécurité globale.

Pour préparer l'activation de la fonctionnalité de lecteurs FIPS, évitez de combiner les nœuds où certains prennent en charge des disques FIPS et d'autres non.

Un cluster est considéré comme étant conforme à la norme FIPS dans les conditions suivantes :

* Tous les disques sont certifiés FIPS.
* Tous les nœuds sont des nœuds de disques FIPS.
* Le chiffrement au repos est activé.
* La fonctionnalité disques FIPS est activée. L'ensemble des disques et nœuds doit être compatible FIPS et le chiffrement au repos doit être activé pour que la fonctionnalité de disque FIPS soit activée.

