---
permalink: storage/task_data_protection_back_up_volume_snapshot_to_solidfire.html 
sidebar: sidebar 
keywords: volume snapshot, backup, solidfire cluster 
summary: Vous pouvez sauvegarder des snapshots de volumes résidant sur un cluster SolidFire vers un cluster SolidFire distant. 
---
= Sauvegarder un snapshot de volume sur un cluster SolidFire
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez sauvegarder des snapshots de volumes résidant sur un cluster SolidFire vers un cluster SolidFire distant.

Assurez-vous que les clusters source et cible sont appariés.

Lors de la sauvegarde ou de la restauration d'un cluster à un autre, le système génère une clé à utiliser pour l'authentification entre les clusters. Cette clé d'écriture de volume en bloc permet au cluster source de s'authentifier auprès du cluster de destination, offrant un niveau de sécurité lors de l'écriture sur le volume de destination. Dans le cadre du processus de sauvegarde ou de restauration, vous devez générer une clé d'écriture de volume en bloc à partir du volume de destination avant de démarrer l'opération.

. Sur le cluster de destination, cliquez sur *Management* > *volumes*.
. Cliquez sur l'icône *actions* pour le volume de destination.
. Dans le menu résultant, cliquez sur *Restaurer depuis*.
. Dans la boîte de dialogue *Restauration intégrée* sous *Restaurer depuis*, sélectionnez *SolidFire*.
. Sélectionnez un format de données sous *format de données* :
+
** *Natif* : format compressé lisible uniquement par les systèmes de stockage SolidFire.
** *Non compressé* : format non compressé compatible avec d'autres systèmes.


. Cliquez sur *générer clé*.
. Copiez la clé de la case *clé d'écriture de volume en masse* dans votre presse-papiers.
. Sur le cluster source, cliquez sur *Data protection* > *snapshots*.
. Cliquez sur l'icône actions correspondant au snapshot que vous souhaitez utiliser pour la sauvegarde.
. Dans le menu qui s'affiche, cliquez sur *Sauvegarder sur*.
. Dans la boîte de dialogue** de la boîte de dialogue** sauvegarde intégrée de la section *sauvegarde vers*, sélectionnez *SolidFire*.
. Sélectionnez le même format de données que celui sélectionné précédemment dans le champ *format de données*.
. Entrez l'adresse IP virtuelle de gestion du cluster du volume de destination dans le champ *Remote Cluster MVIP*.
. Entrez le nom d'utilisateur du cluster distant dans le champ *Nom d'utilisateur du cluster distant*.
. Saisissez le mot de passe du cluster distant dans le champ *Mot de passe du cluster distant*.
. Dans le champ *clé d'écriture de volume en bloc*, collez la clé que vous avez générée précédemment sur le cluster de destination.
. Cliquez sur *Démarrer lecture*.

