---
permalink: storage/task_snapmirror_use_replication_between_element_and_ontap_clusters.html 
sidebar: sidebar 
keywords: replication, snapmirror, data protection 
summary: 'Vous pouvez créer des relations SnapMirror à partir de l"onglet protection des données dans l"interface utilisateur de NetApp Element. La fonctionnalité SnapMirror doit être activée pour que ce type de fonctionnalité soit visible dans l"interface utilisateur.' 
---
= Utilisation de la réplication SnapMirror entre les clusters Element et ONTAP (interface utilisateur Element)
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez créer des relations SnapMirror à partir de l'onglet protection des données dans l'interface utilisateur de NetApp Element. La fonctionnalité SnapMirror doit être activée pour que ce type de fonctionnalité soit visible dans l'interface utilisateur.

Le protocole IPv6 n'est pas pris en charge pour la réplication SnapMirror entre le logiciel NetApp Element et les clusters ONTAP.

https://www.youtube.com/embed/kerGI1ZtnZQ?rel=0["Vidéo NetApp : SnapMirror pour NetApp HCI et Element"^]

Les systèmes exécutant le logiciel NetApp Element prennent en charge la fonctionnalité SnapMirror pour copier et restaurer les copies Snapshot avec les systèmes NetApp ONTAP. Cette technologie repose en premier lieu sur la reprise après incident de NetApp HCI vers ONTAP. Ces terminaux incluent ONTAP, ONTAP Select et Cloud Volumes ONTAP. Consultez le document TR-4641 protection des données NetApp HCI.

https://www.netapp.com/pdf.html?item=/media/17048-tr4641pdf.pdf["Rapport technique NetApp 4641 : protection des données NetApp HCI"^]



== Trouvez plus d'informations

* https://www.netapp.com/pdf.html?item=/media/16991-tr4748pdf.pdf["Bâtissez votre Data Fabric avec NetApp HCI, ONTAP et l'infrastructure convergée"^]
* link:element-replication-index.html["Réplication entre le logiciel NetApp Element et ONTAP (interface de ligne de commande ONTAP)"]

