---
permalink: storage/task-element-replication-update-replication-relationship-manually.html 
sidebar: sidebar 
keywords: update, replication, relationship, manually 
summary: 'Vous devrez peut-être mettre à jour une relation de réplication manuellement si une mise à jour échoue en raison d"une erreur réseau.' 
---
= Mettre à jour une relation de réplication manuellement
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous devrez peut-être mettre à jour une relation de réplication manuellement si une mise à jour échoue en raison d'une erreur réseau.

.Description de la tâche
Vous devez spécifier le chemin source de l'élément sous la forme `<hostip:>/lun/<name>`, où « lun » est la chaîne réelle « lun » et `name` le nom du volume d'élément.

.Étapes
. Mettre à jour une relation de réplication manuellement :
+
`snapmirror update -source-path <hostip:>/lun/<name> -destination-path <SVM:volume>|<cluster://SVM/volume>`

+
Pour connaître la syntaxe complète de la commande, reportez-vous à la page man.

+
[NOTE]
====
Si aucune copie Snapshot commune n'existe sur la source et la destination, la commande échoue. Utilisez `snapmirror initialize` pour réinitialiser la relation.

====
+
L'exemple suivant met à jour la relation entre le volume source `0005` à l'adresse IP 10.0.0.11 et le volume de destination `volA_dst` sur `svm_backup`:

+
[listing]
----
cluster_src::> snapmirror update -source-path 10.0.0.11:/lun/0005 -destination-path svm_backup:volA_dst
----

