---
permalink: storage/task_replication_pair_clusters.html 
sidebar: sidebar 
keywords: pair clusters, replication, connect clusters, data protection 
summary: 'Vous devez coupler deux clusters pour utiliser la fonctionnalité de réplication en temps réel. Une fois que vous avez couplé et connecté deux clusters, vous pouvez configurer des volumes actifs sur un cluster pour qu"ils soient répliqués en continu sur un second cluster, ce qui assure la protection continue des données \(CDP\).' 
---
= Coupler les clusters pour la réplication
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous devez coupler deux clusters pour utiliser la fonctionnalité de réplication en temps réel. Une fois que vous avez couplé et connecté deux clusters, vous pouvez configurer des volumes actifs sur un cluster pour qu'ils soient répliqués en continu sur un second cluster, assurant ainsi la protection continue des données (CDP).

.Ce dont vous avez besoin
* Vous devez disposer des privilèges d'administrateur de cluster sur un ou les deux clusters en cours d'association.
* Tous les MIP et SIP de nœud sont acheminés les uns vers les autres.
* Moins de 2000 ms de latence aller-retour entre les clusters.
* Les deux clusters de stockage doivent avoir des noms de cluster uniques, des adresses MVIP, des adresses SVIP et toutes les adresses IP de nœud.
* La différence entre les versions des logiciels Element sur les clusters est supérieure à une version principale. Si la différence est supérieure, l'un des clusters doit être mis à niveau pour effectuer la réplication des données.



NOTE: L'association de cluster requiert une connectivité complète entre les nœuds du réseau de gestion. La réplication nécessite une connectivité entre les différents nœuds du réseau de cluster de stockage.

Vous pouvez coupler un cluster avec quatre autres clusters au maximum pour répliquer des volumes. Vous pouvez également coupler les clusters au sein du groupe de clusters.



== Couplez des clusters à l'aide de MVIP ou d'une clé de couplage

Vous pouvez coupler un cluster source et cible à l'aide du MVIP du cluster cible si un administrateur de cluster a accès aux deux clusters. Si l'accès à l'administrateur de cluster n'est disponible que sur un seul cluster d'une paire de clusters, une clé de couplage peut être utilisée sur le cluster cible pour terminer le couplage du cluster.

. Sélectionnez l'une des méthodes suivantes pour coupler les clusters :
+
** link:task_replication_pair_cluster_using_mvip.html["Couplez des clusters à l'aide de MVIP"]Utilisez cette méthode si l'administrateur du cluster a accès aux deux clusters. Cette méthode utilise le MVIP du cluster distant pour apparier deux clusters.
** link:task_replication_pair_cluster_using_pairing_key.html["Couplez des clusters à l'aide d'une clé de couplage"]Utilisez cette méthode si l'administrateur du cluster n'a accès qu'à un seul des clusters. Cette méthode génère une clé d'appariement qui peut être utilisée sur le cluster cible pour finaliser l'appariement des clusters.






== Trouvez plus d'informations

xref:reference_prereq_network_port_requirements.adoc[Configuration requise pour les ports réseau]
