---
permalink: storage/task-element-replication-create-replication-job-schedule.html 
sidebar: sidebar 
keywords: ontap, cli, create, replication, job, schedule 
summary: Vous pouvez utiliser la commande cron create de planification de travaux pour créer une planification de travaux de réplication. La planification des tâches détermine lorsque SnapMirror met automatiquement à jour la relation de protection des données à laquelle la planification est attribuée. 
---
= Créer une planification de tâche de réplication
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Que vous répliquant des données d'Element vers ONTAP ou de ONTAP vers Element, vous devez configurer une planification de tâche, spécifier une règle et créer et initialiser la relation. Vous pouvez utiliser une stratégie par défaut ou personnalisée.

Vous pouvez utiliser `job schedule cron create` la commande pour créer une planification de tâche de réplication. La planification des tâches détermine lorsque SnapMirror met automatiquement à jour la relation de protection des données à laquelle la planification est attribuée.

.Description de la tâche
Vous affectez un planning de travail lorsque vous créez une relation de protection des données. Si vous n'attribuez pas de programme de travail, vous devez mettre à jour la relation manuellement.

.Étape
. Création d'un programme de travail :
+
`job schedule cron create -name _job_name_ -month _month_ -dayofweek _day_of_week_ -day _day_of_month_ -hour _hour_ -minute _minute_`

+
Pour `-month`, , `-dayofweek` et `-hour`, vous pouvez spécifier `all` d'exécuter le travail chaque mois, jour de la semaine et heure, respectivement.

+
Depuis ONTAP 9.10.1, vous pouvez inclure le vServer dans votre calendrier des tâches :

+
`job schedule cron create -name _job_name_ -vserver _Vserver_name_ -month _month_ -dayofweek _day_of_week_ -day _day_of_month_ -hour _hour_ -minute _minute_`

+
L'exemple suivant crée un horaire de travail nommé `my_weekly` qui s'exécute le samedi à 3 h 00 :

+
[listing]
----
cluster_dst::> job schedule cron create -name my_weekly -dayofweek "Saturday" -hour 3 -minute 0
----

