---
permalink: storage/task_data_protection_back_up_volume_to_solidfire.html 
sidebar: sidebar 
keywords: volume backup, solidfire storage cluster 
summary: Vous pouvez sauvegarder des volumes résidant sur un cluster distant pour des clusters de stockage exécutant le logiciel Element. 
---
= Sauvegarder un volume sur un cluster de stockage SolidFire
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez sauvegarder des volumes résidant sur un cluster distant pour des clusters de stockage exécutant le logiciel Element.

Assurez-vous que les clusters source et cible sont appariés.

Voir link:task_replication_pair_clusters.html["Coupler les clusters pour la réplication"].

Lors de la sauvegarde ou de la restauration d'un cluster à un autre, le système génère une clé à utiliser pour l'authentification entre les clusters. Cette clé d'écriture de volume en bloc permet au cluster source de s'authentifier auprès du cluster de destination, offrant un niveau de sécurité lors de l'écriture sur le volume de destination. Dans le cadre du processus de sauvegarde ou de restauration, vous devez générer une clé d'écriture de volume en bloc à partir du volume de destination avant de démarrer l'opération.

. Sur le cluster de destination, *Management* > *volumes*.
. Cliquez sur l'icône actions du volume de destination.
. Dans le menu résultant, cliquez sur *Restaurer depuis*.
. Dans la boîte de dialogue *Restauration intégrée*, sous *Restaurer depuis*, sélectionnez *SolidFire*.
. Sélectionnez une option sous *format de données* :
+
** *Natif* : format compressé lisible uniquement par les systèmes de stockage SolidFire.
** *Non compressé* : format non compressé compatible avec d'autres systèmes.


. Cliquez sur *générer clé*.
. Copiez la clé de la case *clé d'écriture de volume en masse* dans votre presse-papiers.
. Sur le cluster source, accédez à *Management* > *volumes*.
. Cliquez sur l'icône actions du volume à sauvegarder.
. Dans le menu qui s'affiche, cliquez sur *Sauvegarder sur*.
. Dans la boîte de dialogue *sauvegarde intégrée* sous *sauvegarde vers*, sélectionnez *SolidFire*.
. Sélectionnez la même option que celle sélectionnée précédemment dans le champ *format de données*.
. Entrez l'adresse IP virtuelle de gestion du cluster du volume de destination dans le champ *Remote Cluster MVIP*.
. Entrez le nom d'utilisateur du cluster distant dans le champ *Nom d'utilisateur du cluster distant*.
. Saisissez le mot de passe du cluster distant dans le champ *Mot de passe du cluster distant*.
. Dans le champ *clé d'écriture de volume en bloc*, collez la clé que vous avez générée précédemment sur le cluster de destination.
. Cliquez sur *Démarrer lecture*.

