---
permalink: storage/task_data_protection_use_group_snapshots_for_data_protection.html 
sidebar: sidebar 
keywords: group snapshots, data protection, set of volumes, backup, rollback 
summary: 'Vous pouvez créer un snapshot de groupe d"un ensemble de volumes associé afin de conserver une copie instantanée des métadonnées de chaque volume. Vous pouvez utiliser l"instantané de groupe ultérieurement comme sauvegarde ou restauration pour restaurer l"état du groupe de volumes à un état précédent.' 
---
= Utilisation de snapshots de groupe pour la tâche de protection des données
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez créer un snapshot de groupe d'un ensemble de volumes associé afin de conserver une copie instantanée des métadonnées de chaque volume. Vous pouvez utiliser l'instantané de groupe ultérieurement comme sauvegarde ou restauration pour restaurer l'état du groupe de volumes à un état précédent.



== Trouvez plus d'informations

* xref:task_data_protection_create_a_group_snapshot.adoc[Créez un snapshot de groupe]
* xref:task_data_protection_edit_group_snapshots.adoc[Modifier les instantanés de groupe]
* xref:task_data_protection_edit_members_of_group_snapshot.adoc[Modifier les membres de l'instantané de groupe]
* xref:task_data_protection_delete_a_group_snapshot.adoc[Supprimer un snapshot de groupe]
* xref:task_data_protection_roll_back_volumes_to_a_group_snapshot.adoc[Restaurer les volumes dans un snapshot de groupe]
* xref:task_data_protection_clone_multiple_volumes.adoc[Clonage de plusieurs volumes]
* xref:task_data_protection_clone_multiple_volumes_from_a_group_snapshot.adoc[Cloner plusieurs volumes à partir d'un snapshot de groupe]

