---
permalink: storage/task_post_deploy_credential_change_ipmi_password.html 
sidebar: sidebar 
keywords: ipmi, password, intelligent platform management interface, netapp, element, h410s, h610s 
summary: 'Vous pouvez modifier le mot de passe administrateur par défaut de l"interface IPMI (Intelligent Platform Management interface) dès que vous disposez d"un accès IPMI à distance au nœud. Vous pouvez le faire si des mises à jour d"installation sont disponibles.' 
---
= Modifiez le mot de passe IPMI par défaut pour les nœuds
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez modifier le mot de passe administrateur par défaut de l'interface IPMI (Intelligent Platform Management interface) dès que vous disposez d'un accès IPMI à distance au nœud. Vous pouvez le faire si des mises à jour d'installation sont disponibles.

Pour plus de détails sur la configuration de l'accès IPM pour les nœuds, voir link:https://docs.netapp.com/us-en/hci/docs/hci_prereqs_final_prep.html["Configurez IPMI pour chaque nœud"^].

Vous pouvez modifier le mot de passe IPM pour ces nœuds :

* Nœuds H410S
* Nœuds H610S




== Modifiez le mot de passe IPMI par défaut pour les nœuds H410S

Vous devez modifier le mot de passe par défaut du compte administrateur IPMI sur chaque nœud de stockage dès que vous configurez le port réseau IPMI.

.Ce dont vous avez besoin
Vous devez avoir configuré l'adresse IP IPMI pour chaque nœud de stockage.

.Étapes
. Ouvrez un navigateur Web sur un ordinateur qui peut atteindre le réseau IPMI et naviguez jusqu'à l'adresse IP IPMI du nœud.
. Entrez le nom d'utilisateur `ADMIN` et mot de passe `ADMIN` dans l'invite de connexion.
. Lorsque vous vous connectez, cliquez sur l'onglet *Configuration*.
. Cliquez sur *utilisateurs*.
. Sélectionner `ADMIN` Et cliquez sur *Modifier l'utilisateur*.
. Cochez la case *Modifier le mot de passe*.
. Entrez un nouveau mot de passe dans les champs *Mot de passe* et *confirmer le mot de passe*.
. Cliquez sur *Modifier*, puis sur *OK*.
. Répétez cette procédure pour tous les autres nœuds H410S avec des mots de passe IPMI par défaut.




== Modifiez le mot de passe IPMI par défaut pour les nœuds H610S

Vous devez modifier le mot de passe par défaut du compte administrateur IPMI sur chaque nœud de stockage dès que vous configurez le port réseau IPMI.

.Ce dont vous avez besoin
Vous devez avoir configuré l'adresse IP IPMI pour chaque nœud de stockage.

.Étapes
. Ouvrez un navigateur Web sur un ordinateur qui peut atteindre le réseau IPMI et naviguez jusqu'à l'adresse IP IPMI du nœud.
. Entrez le nom d'utilisateur `root` et mot de passe `calvin` dans l'invite de connexion.
. Lorsque vous vous connectez, cliquez sur l'icône de navigation dans le menu en haut à gauche de la page pour ouvrir le tiroir de la barre latérale.
. Cliquez sur *Paramètres*.
. Cliquez sur *gestion des utilisateurs*.
. Sélectionnez l'utilisateur *Administrateur* dans la liste.
. Activez la case à cocher *Modifier le mot de passe*.
. Saisissez un nouveau mot de passe fort dans les champs *Mot de passe* et *confirmer le mot de passe*.
. Cliquez sur *Enregistrer* en bas de la page.
. Répétez cette procédure pour tous les autres nœuds H610S avec mots de passe IPMI par défaut.




== Trouvez plus d'informations

* https://www.netapp.com/data-storage/solidfire/documentation["Page Ressources SolidFire et Element"^]
* https://docs.netapp.com/us-en/vcp/index.html["Plug-in NetApp Element pour vCenter Server"^]

