---
permalink: storage/task_data_manage_vol_access_group_add_multiple_initiators.html 
sidebar: sidebar 
keywords: initiator, add to volume access group, access groups, add multiple initiators, create initiator 
summary: 'Vous pouvez ajouter plusieurs initiateurs à un groupe d"accès de volume existant pour autoriser l"accès aux volumes du groupe d"accès de volume avec ou sans authentification CHAP.' 
---
= Ajoutez plusieurs initiateurs à un groupe d'accès de volume
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez ajouter plusieurs initiateurs à un groupe d'accès de volume existant pour autoriser l'accès aux volumes du groupe d'accès de volume avec ou sans authentification CHAP.

Lorsque vous ajoutez des initiateurs à un groupe d'accès de volume, les initiateurs ont accès à tous les volumes de ce groupe.


TIP: Vous pouvez trouver l'initiateur pour chaque volume en cliquant sur l'icône actions, puis sur *Afficher les détails* du volume dans la liste volumes actifs.

Vous pouvez ajouter plusieurs initiateurs à un groupe d'accès de volume existant pour permettre l'accès aux volumes et attribuer des informations d'identification CHAP uniques à chaque initiateur de ce groupe d'accès de volume. Cela vous permet d'appliquer cette option aux groupes d'accès aux volumes qui existent déjà.

Vous pouvez attribuer des attributs CHAP basés sur initator à l'aide d'un appel d'API. Pour ajouter un nom de compte CHAP et des informations d'identification par initiateur, vous devez utiliser l'appel API ModimodiyInitiator pour supprimer et ajouter des droits d'accès et des attributs CHAP.

Pour plus de détails, voir link:../api/index.html["Gérez le stockage avec l'API Element"].

.Étapes
. Cliquez sur *Management* > *Initiators*.
. Sélectionnez les initiateurs à ajouter à un groupe d'accès.
. Cliquez sur le bouton *actions groupées*.
. Cliquez sur *Ajouter au groupe d'accès de volume*.
. Dans la boîte de dialogue Ajouter au groupe d'accès au volume, sélectionnez un groupe d'accès dans la liste *Groupe d'accès au volume*.
. Cliquez sur *Ajouter*.

