---
permalink: storage/task-element-replication-reactivate-original-source-volume.html 
sidebar: sidebar 
keywords: ontap,cli, reactivate, original, source, volume 
summary: 'Vous pouvez rétablir la relation initiale de protection des données entre les volumes source et destination lorsque vous n"avez plus besoin de transmettre des données depuis la destination.' 
---
= Réactiver le volume source d'origine
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez rétablir la relation initiale de protection des données entre les volumes source et destination lorsque vous n'avez plus besoin de transmettre des données depuis la destination.

.Description de la tâche
La procédure ci-dessous suppose que la ligne de base du volume source d'origine est intacte. Si la base n'est pas intacte, vous devez créer et initialiser la relation entre le volume dont vous accédez aux données et le volume source d'origine avant d'effectuer la procédure.

Vous devez spécifier le chemin source de l'élément sous la forme `<hostip:>/lun/<name>`, où « lun » est la chaîne réelle « lun » et `name` le nom du volume d'élément.

Depuis ONTAP 9.4, les copies Snapshot d'une LUN créée pendant le transfert des données depuis la destination ONTAP sont automatiquement répliquées lorsque la source de l'élément est réactivée.

Les règles de réplication sont les suivantes :

* Seules les LUN iSCSI sont prises en charge.
* Vous ne pouvez pas répliquer plusieurs LUN depuis un volume ONTAP vers un volume Element.
* Vous ne pouvez pas répliquer un LUN depuis un volume ONTAP vers plusieurs volumes Element.


.Étapes
. Supprimez la relation de protection des données d'origine :
+
`snapmirror delete -source-path <SVM:volume>|<cluster://SVM/volume> -destination-path <hostip:>/lun/<name> -policy <policy>`

+
Pour connaître la syntaxe complète de la commande, reportez-vous à la page man.

+
L'exemple suivant supprime la relation entre le volume source d'origine, `0005` à l'adresse IP 10.0.0.11, et le volume depuis lequel vous traitez des données, `volA_dst` le `svm_backup`:

+
[listing]
----
cluster_dst::> snapmirror delete -source-path 10.0.0.11:/lun/0005 -policy MirrorLatest -destination-path svm_backup:volA_dst
----
. Inverser la relation de protection des données d'origine :
+
`snapmirror resync -source-path <SVM:volume>|<cluster://SVM/volume> -destination-path <hostip:>/lun/<name> -policy <policy>`

+
Pour connaître la syntaxe complète de la commande, reportez-vous à la page man.

+
Bien que la resynchronisation ne nécessite pas de transfert de base, elle peut prendre du temps. Vous pouvez exécuter la resynchronisation en dehors des heures de pointe.

+
L'exemple suivant inverse la relation entre le volume source d'origine, `0005` à l'adresse IP 10.0.0.11, et le volume à partir duquel vous traitez les données, `volA_dst` on `svm_backup`:

+
[listing]
----
cluster_dst::> snapmirror resync -source-path svm_backup:volA_dst -destination-path 10.0.0.11:/lun/0005 -policy MirrorLatest
----
. Mettre à jour la relation inversée :
+
`snapmirror update -source-path <SVM:volume>|<cluster://SVM/volume> -destination-path <hostip:>/lun/<name>`

+
Pour connaître la syntaxe complète de la commande, reportez-vous à la page man.

+
[NOTE]
====
Si aucune copie Snapshot commune n'existe sur la source et la destination, la commande échoue. Utilisez `snapmirror initialize` pour réinitialiser la relation.

====
+
L'exemple suivant met à jour la relation entre le volume que vous traitez des données depuis, on `svm_backup` et le volume source d'origine `0005`, `volA_dst` à l'adresse IP 10.0.0.11 :

+
[listing]
----
cluster_dst::> snapmirror update -source-path svm_backup:volA_dst -destination-path 10.0.0.11:/lun/0005
----
. Arrêter les transferts programmés pour la relation inversée :
+
`snapmirror quiesce -source-path <SVM:volume>|<cluster://SVM/volume> -destination-path <hostip:>/lun/<name>`

+
Pour connaître la syntaxe complète de la commande, reportez-vous à la page man.

+
L'exemple suivant arrête les transferts planifiés entre le volume que vous traitez des données depuis, sur `svm_backup` et le volume source d'origine `0005`, `volA_dst` à l'adresse IP 10.0.0.11 :

+
[listing]
----
cluster_dst::> snapmirror quiesce -source-path svm_backup:volA_dst -destination-path 10.0.0.11:/lun/0005
----
. Arrêter les transferts en cours pour la relation inversée :
+
`snapmirror abort -source-path <SVM:volume>|<cluster://SVM/volume> -destination-path <hostip:>/lun/<name>`

+
Pour connaître la syntaxe complète de la commande, reportez-vous à la page man.

+
L'exemple suivant arrête les transferts en cours entre le volume que vous traitez des données depuis, sur `svm_backup` et le volume source d'origine `0005`, `volA_dst` à l'adresse IP 10.0.0.11 :

+
[listing]
----
cluster_dst::> snapmirror abort -source-path svm_backup:volA_dst -destination-path 10.0.0.11:/lun/0005
----
. Rompez la relation inversée :
+
`snapmirror break -source-path <SVM:volume>|<cluster://SVM/volume> -destination-path <hostip:>/lun/<name>`

+
Pour connaître la syntaxe complète de la commande, reportez-vous à la page man.

+
L'exemple suivant rompt la relation entre le volume que vous traitez des données de, on `svm_backup` et le volume source d'origine `0005`, `volA_dst` à l'adresse IP 10.0.0.11:

+
[listing]
----
cluster_dst::> snapmirror break -source-path svm_backup:volA_dst -destination-path 10.0.0.11:/lun/0005
----
. Supprimez la relation de protection des données inversée :
+
`snapmirror delete -source-path <SVM:volume>|<cluster://SVM/volume> -destination-path <hostip:>/lun/<name> -policy <policy>`

+
Pour connaître la syntaxe complète de la commande, reportez-vous à la page man.

+
L'exemple suivant supprime la relation inversée entre le volume source d'origine, `0005` à l'adresse IP 10.0.0.11, et le volume à partir duquel vous traitez des données, `volA_dst` on `svm_backup`:

+
[listing]
----
cluster_src::> snapmirror delete -source-path svm_backup:volA_dst -destination-path 10.0.0.11:/lun/0005 -policy MirrorLatest
----
. Rétablir la relation initiale de protection des données :
+
`snapmirror resync -source-path <hostip:>/lun/<name> -destination-path <SVM:volume>|<cluster://SVM/volume>`

+
Pour connaître la syntaxe complète de la commande, reportez-vous à la page man.

+
L'exemple suivant rétablit la relation entre le volume source d'origine, `0005` à l'adresse IP 10.0.0.11, et le volume de destination d'origine, `volA_dst` on `svm_backup`:

+
[listing]
----
cluster_dst::> snapmirror resync -source-path 10.0.0.11:/lun/0005 -destination-path svm_backup:volA_dst
----


.Une fois que vous avez terminé
Utiliser `snapmirror show` la commande pour vérifier que la relation SnapMirror a été créée. Pour connaître la syntaxe complète de la commande, reportez-vous à la page man.
