---
permalink: storage/task-element-replication-define-rule-policy.html 
sidebar: sidebar 
keywords: ontap, cli, define, rule, policy 
summary: 'Pour les règles personnalisées avec le type de règle « mirror-vault », vous devez définir au moins une règle qui détermine les copies Snapshot qui sont transférées au cours de l"initialisation et de la mise à jour. Vous pouvez également définir des règles pour les stratégies par défaut avec le type de stratégie "mirror-vault".' 
---
= Définir une règle pour une règle
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Pour les règles personnalisées avec le type de règle « miroir-vault », vous devez définir au moins une règle qui détermine quelles copies Snapshot sont transférées au cours de l'initialisation et de la mise à jour. Vous pouvez également définir des règles pour les stratégies par défaut avec le type de stratégie "miroir-coffre-fort".

.Description de la tâche
Chaque règle de type « miroir-vault » doit avoir une règle qui spécifie les copies Snapshot à répliquer. La règle « bimensuelle », par exemple, indique que seules les copies snapshot attribuées au label SnapMirror « bimensuel » doivent être répliquées. Attribuez une étiquette SnapMirror lorsque vous configurez les copies Snapshot Element.

Chaque type de stratégie est associé à une ou plusieurs règles définies par le système. Ces règles sont automatiquement attribuées à une règle lorsque vous spécifiez son type de stratégie. Le tableau ci-dessous présente les règles définies par le système.

|===


| Règle définie par le système | Utilisé dans les types de stratégie | Résultat 


 a| 
sm_créé
 a| 
asynchrone-mirror, mirror-vault
 a| 
Une copie Snapshot créée par SnapMirror est transférée lors de l'initialisation et de la mise à jour.



 a| 
tous les jours
 a| 
coffre-fort
 a| 
Les nouvelles copies snapshot sur la source portant le label « quotidien » SnapMirror sont transférées lors de l'initialisation et de la mise à jour.



 a| 
hebdomadaire
 a| 
coffre-fort
 a| 
Les nouvelles copies Snapshot sur la source portant le libellé « hebdomadaire » du SnapMirror sont transférées au moment de l'initialisation et de la mise à jour.



 a| 
tous les mois
 a| 
coffre-fort
 a| 
Les nouvelles copies snapshot sur la source portant le libellé « mensuel » de SnapMirror sont transférées lors de l'initialisation et de la mise à jour.

|===
Vous pouvez indiquer des règles supplémentaires selon vos besoins pour les règles par défaut ou personnalisées. Par exemple :

* Pour la règle par défaut `MirrorAndVault`, vous pouvez créer une règle appelée « bimensuelle » pour faire correspondre les copies Snapshot sur la source avec l'étiquette SnapMirror « bimensuelle ».
* Pour une règle personnalisée de type « miroir-vault », vous pouvez créer une règle appelée « bi-hebdomadaire » pour faire correspondre les copies snapshot sur la source avec le libellé « bi-hebdomadaire » SnapMirror.


.Étape
. Définir une règle pour une règle :
+
`snapmirror policy add-rule -vserver _SVM_ -policy _policy_for_rule_ -snapmirror-label _snapmirror-label_ -keep _retention_count_`

+
Pour connaître la syntaxe complète de la commande, reportez-vous à la page man.

+
L'exemple suivant ajoute une règle portant le libellé SnapMirror `bi-monthly` à la règle par défaut `MirrorAndVault` :

+
[listing]
----
cluster_dst::> snapmirror policy add-rule -vserver svm1 -policy MirrorAndVault -snapmirror-label bi-monthly -keep 6
----
+
L'exemple suivant ajoute une règle portant le libellé SnapMirror `bi-weekly` à la règle personnalisée `my_snapvault` :

+
[listing]
----
cluster_dst::> snapmirror policy add-rule -vserver svm1 -policy my_snapvault -snapmirror-label bi-weekly -keep 26
----
+
L'exemple suivant ajoute une règle portant le libellé SnapMirror `app_consistent` à la règle personnalisée `Sync` :

+
[listing]
----
cluster_dst::> snapmirror policy add-rule -vserver svm1 -policy Sync -snapmirror-label app_consistent -keep 1
----
+
Vous pouvez ensuite répliquer des copies snapshot à partir du cluster source correspondant à cette étiquette SnapMirror :

+
[listing]
----
cluster_src::> snapshot create -vserver vs1 -volume vol1 -snapshot snapshot1 -snapmirror-label app_consistent
----

