---
permalink: setup/task_setup_create_a_storage_cluster.html 
sidebar: sidebar 
keywords:  
summary: 'Vous pouvez créer un cluster de stockage une fois que vous avez configuré tous les nœuds individuels. Lorsque vous créez un cluster, un compte utilisateur d"administrateur de cluster est automatiquement créé pour vous. L"administrateur de cluster est autorisé à gérer tous les attributs de cluster et peut créer d"autres comptes d"administrateur de cluster.' 
---
= Créer un cluster de stockage
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez créer un cluster de stockage une fois que vous avez configuré tous les nœuds individuels. Lorsque vous créez un cluster, un compte utilisateur d'administrateur de cluster est automatiquement créé pour vous. L'administrateur de cluster est autorisé à gérer tous les attributs de cluster et peut créer d'autres comptes d'administrateur de cluster.

.Ce dont vous avez besoin
* Vous avez installé le nœud de gestion.
* Vous avez configuré tous les nœuds individuels.


.Description de la tâche
Lors de la nouvelle configuration de nœud, des adresses IP de gestion (MIP) 1G ou 10G sont attribuées à chaque nœud. Vous devez utiliser l'une des adresses IP de nœud créées lors de la configuration pour ouvrir la page Créer un nouveau cluster. L'adresse IP que vous utilisez dépend du réseau que vous avez choisi pour la gestion du cluster.

[IMPORTANT]
====
Si vous souhaitez activer l'ensemble du cluster link:../concepts/concept_solidfire_concepts_security.html#encryption-at-rest-software["chiffrement logiciel pour les données au repos"] Pour les clusters de stockage 100 % Flash SolidFire, vous devez effectuer cette opération lors de la création du cluster. À partir de la version Element 12.5, vous devez activer le chiffrement logiciel au repos dans l'interface de création du cluster lors de la création du cluster. Pour Element 12.3.x et versions antérieures, vous devez créer le cluster à l'aide de link:../api/reference_element_api_createcluster.html["CreateCluster"] La méthode API et définissez le paramètre enableSoftwareEncryptionAtRest sur `true`. Si le chiffrement logiciel au repos est activé sur le cluster, il ne peut pas être désactivé. C'est possible link:../storage/task_system_manage_cluster_enable_and_disable_encryption_for_a_cluster.html["activer et désactiver"] Chiffrement matériel au repos après la création du cluster.

====
[NOTE]
====
Lorsque vous créez un nouveau cluster, tenez compte des points suivants :

* Si vous utilisez des nœuds de stockage qui résident dans un châssis partagé, vous pouvez envisager de concevoir un système de protection contre les défaillances au niveau du châssis à l'aide de la fonction de domaines de protection.
* Si un châssis partagé n'est pas utilisé, vous pouvez définir une disposition de domaine de protection personnalisée.


====
.Étapes
. Dans une fenêtre de navigateur, entrez `\https://MIP:443`, Où MIP est l'adresse IP du nœud de gestion.
. Dans Créer un nouveau cluster, saisissez les informations suivantes :
+
** Gestion VIP : IP virtuelle routable sur le réseau 1GbE ou 10GbE pour les tâches de gestion du réseau.
+

NOTE: Vous pouvez créer un nouveau cluster à l'aide de l'adressage IPv4 ou IPv6.

** ISCSI (stockage) VIP : IP virtuelle sur le réseau 10GbE pour le stockage et la découverte iSCSI.
+

NOTE: Vous ne pouvez pas modifier le nom MVIP, SVIP ou du cluster après avoir créé le cluster.

** Nom d'utilisateur : nom d'utilisateur principal de l'administrateur du cluster pour l'accès authentifié au cluster. Vous devez enregistrer le nom d'utilisateur pour référence ultérieure.
+

NOTE: Vous pouvez utiliser des lettres majuscules et minuscules, des caractères spéciaux et des chiffres pour le nom d'utilisateur et le mot de passe.

** Mot de passe : mot de passe pour l'accès authentifié au cluster. Vous devez enregistrer le mot de passe pour pouvoir le consulter ultérieurement. La protection des données bidirectionnelle est activée par défaut. Vous ne pouvez pas modifier ce paramètre.


. Lisez le contrat de licence de l'utilisateur final et sélectionnez *J'accepte*.
. *Facultatif* : dans la liste nœuds, assurez-vous que les cases à cocher des nœuds qui ne doivent pas être inclus dans le cluster ne sont pas sélectionnées.
. Sélectionnez *Créer un cluster*.
+
La création du cluster peut prendre plusieurs minutes, en fonction du nombre de nœuds qu'il contient. Sur un réseau correctement configuré, un petit cluster de cinq nœuds doit prendre moins d'une minute. Une fois le cluster créé, la fenêtre Créer un nouveau cluster est redirigée vers l'adresse URL MVIP du cluster et affiche l'interface utilisateur de l'élément.





== Pour en savoir plus

* link:../api/concept_element_api_about_the_api.html["Gestion du stockage avec l'API Element"]
* https://docs.netapp.com/us-en/element-software/index.html["Documentation SolidFire et Element"]
* https://docs.netapp.com/us-en/vcp/index.html["Plug-in NetApp Element pour vCenter Server"^]

