---
permalink: esds/reference_esds_containerlogs.html 
sidebar: sidebar 
keywords: element, solidfire esds, get container logs, sds containers 
summary: 'En savoir plus sur les conteneurs ESDS de SolidFire et sur l"emplacement d"obtention des journaux associés. Les informations fournies ici sont destinées à vous aider à démarrer la collecte des journaux pour le dépannage. Il est préférable d"faire appel au service de support de NetApp, où les ingénieurs formés très bien au sujet de l"analyse des journaux peuvent contribuer à résoudre les problèmes.' 
---
= Collecte des journaux de conteneur
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
En savoir plus sur les conteneurs ESDS de SolidFire et sur l'emplacement d'obtention des journaux associés. Les informations fournies ici sont destinées à vous aider à démarrer la collecte des journaux pour le dépannage. Il est préférable de s'engager https://www.netapp.com/company/contact-us/support/["Support NetApp"^], où des ingénieurs formés et expérimentés en matière d'analyse des journaux peuvent contribuer à résoudre les problèmes.

SolidFire ESDS inclut les conteneurs suivants :

* Conteneur d'éléments (`element`) : Héberge tous les services Element dans un seul conteneur.
* Conteneur d'authentification d'élément (`element_auth`) : Fournit des jetons d'authentification multifacteur (MFA) et d'authentification de session pour les interfaces utilisateur de gestion.
* Conteneur de surveillance réseau (`sfnetwd`) : Assure la surveillance des battements cardiaques de l'instance d'élément local et le basculement des adresses IP virtuelles (MVIP et SVIP).


Pour accéder aux conteneurs d'un nœud ESDS via SSH, le propriétaire du nœud doit activer SSH et fournir les informations d'identification de connexion. Une fois que vous avez accès SSH au système hôte, vous pouvez vérifier l'état d'un ou de plusieurs conteneurs à l'aide de l' `podman ps` commande. Voir l'exemple ci-dessous :

[listing]
----
# podman ps
CONTAINER ID IMAGE COMMAND CREATED STATUS PORTS NAMES
f6b8817c024a localhost/solidfire-element:12.2.0.777 --config /sf/etc/... 11 seconds ago Up 10 seconds ago sfnetwd
c3fed6141259 localhost/solidfire-auth:12.2.0.777 --config /sf/etc/... 11 seconds ago Up 11 seconds ago element_auth
1ffa8289c701 localhost/solidfire-element:12.2.0.777 --config /sf/etc/... 12 seconds ago Up 12 seconds ago element
#
----

IMPORTANT: Si l'un des conteneurs n'est pas opérationnel, n'utilisez pas Podman pour contrôler directement (arrêter ou démarrer) les conteneurs. Le logiciel Element est contrôlé via le `solidfire systemd` unité de service. Ce service utilise `elementctl` Pour orchestrer l'exécution du logiciel dans les conteneurs trois éléments. À l'aide de `systemctl` Pour contrôler le service SolidFire sur l'hôte, il est recommandé et pris en charge de démarrer et d'arrêter le logiciel Element sur n'importe quel nœud. Toutefois, pour ce faire, vous devez uniquement faire sous les instructions du support.

Tous les journaux associés à SolidFire ESDS se trouvent dans `/var/log/solidfire/` sur l'hôte, qui reste sur toutes les instances de conteneur. Ce répertoire contient les journaux du conteneur d'éléments, et contient le `element_auth/` et `sfnetwd/` les sous-répertoires qui contiennent les logs du `element_auth` et `sfnetwd` conteneurs, respectivement. Depuis l'intérieur d'un conteneur, vous pouvez accéder à des journaux spécifiques à ce conteneur à `/var/log`.



== Utilisez l'interface utilisateur NetApp Hybrid Cloud Control pour collecter les journaux

Vous pouvez collecter des journaux à envoyer au support NetApp pour vous aider à diagnostiquer les problèmes liés à vos clusters SolidFire ESDS.

Gardez à l'esprit les éléments suivants pour la collecte des journaux :

* N'utilisez pas les commandes Podman pour collecter les journaux.
* Le support NetApp utilise un seul recueil pour la collecte des journaux de l'hôte. Pour une expérience de support optimale, vous devez avoir installé un outil Collect.


.Étapes
. Ouvrez l'adresse IP du nœud de gestion dans un navigateur Web. Par exemple :
+
[listing]
----
https://[management node IP address]
----
. Connectez-vous au contrôle de cloud hybride NetApp en fournissant les identifiants de l'administrateur du cluster de stockage.
. Dans le Tableau de bord, sélectionnez le menu en haut à droite.
. Sélectionnez *collecter les journaux*.
. Sélectionnez une plage de dates dans le menu déroulant *Plage de dates* pour spécifier les dates que les journaux doivent inclure.
+
Si vous spécifiez une date de début personnalisée, vous pouvez sélectionner la date pour commencer la plage de dates. Les journaux seront collectés à partir de cette date jusqu'à l'heure actuelle.

. Dans la section *Log Collection*, sélectionnez le cluster de stockage ou des nœuds de stockage spécifiques.
. Sélectionnez *collecter les journaux* pour démarrer la collecte des journaux.
+
La collecte des journaux s'exécute en arrière-plan et la page affiche la progression.

+

NOTE: Selon les journaux que vous collectez, la barre de progression peut rester à un certain pourcentage pendant plusieurs minutes, ou progresser très lentement à certains points.

. Sélectionnez *Télécharger les journaux* pour télécharger le fichier journal.
+
Le package log est en un fichier UNIX compressé `.tgz` format de fichier.





== Trouvez plus d'informations

* https://www.netapp.com/data-storage/solidfire/documentation/["Page des ressources NetApp SolidFire"^]
* https://docs.netapp.com/sfe-122/topic/com.netapp.ndc.sfe-vers/GUID-B1944B0E-B335-4E0B-B9F1-E960BF32AE56.html["Documentation relative aux versions antérieures des produits NetApp SolidFire et Element"^]

