---
permalink: esds/reference_esds_sf_sds_config_file.html 
sidebar: sidebar 
keywords: element, solidfire esds, hardware components, configuration file 
summary: 'Chaque nœud dispose d"un fichier sf_sds_config.yaml, qui inclut la liste du matériel que vous spécifiez pour être utilisé par les services ESDS de SolidFire. Après avoir remplacé un disque, vous devez ajouter les informations de remplacement dans ce fichier pour le nœud à partir lequel vous avez remplacé le disque. Ce fichier est stocké dans /opt/sf/. Ce fichier inclut toutes les informations relatives aux disques du nœud. Vous devez entrer les détails du nouveau lecteur dans ce fichier chaque fois que vous ajoutez un nouveau lecteur.' 
---
= Contenu du fichier sf_sds_config.yaml
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Chaque nœud a un `sf_sds_config.yaml` Fichier, qui inclut la liste du matériel que vous spécifiez pour être utilisé par les services ESDS de SolidFire. Après avoir remplacé un disque, vous devez ajouter les informations de remplacement dans ce fichier pour le nœud à partir lequel vous avez remplacé le disque. Ce fichier est stocké dans `/opt/sf/`. Ce fichier inclut toutes les informations relatives aux disques du nœud. Vous devez entrer les détails du nouveau lecteur dans ce fichier chaque fois que vous ajoutez un nouveau lecteur.

Voici le contenu *requis* du fichier :

[cols="4*"]
|===
| Clé | Valeur par défaut | Type | Description 


 a| 
Schemaversion
 a| 
« 2.0 »
 a| 
Chaîne
 a| 
Numéro de version du schéma pour le fichier.



 a| 
le réseau
 a| 
S/O
 a| 
Liste
 a| 
Valeurs autorisées : interface de gestion, interface de stockage



 a| 
Interface de gestion
 a| 
« team0 »
 a| 
Chaîne
 a| 
Nom de l'interface réseau du système d'exploitation hôte préconfigurée, redondante et préintégrée, à utiliser pour la gestion et le trafic de gestion du cluster.



 a| 
Interface de stockage
 a| 
« team1 »
 a| 
Chaîne
 a| 
Nom de l'interface réseau du système d'exploitation hôte préconfigurée et redondante à utiliser pour le trafic réseau de stockage (trafic iSCSI).



 a| 
Lecteurs de données
 a| 
S/O
 a| 
Liste
 a| 
Liste des chemins du système d'exploitation hôte vers les périphériques de stockage physique utilisés par SolidFire ESDS. Vous pouvez spécifier ceci en tant que chemins complets vers le bloc ou les périphériques NVMe. Voici les exemples de chemin complet pris en charge : /dev/disque/by-ID/wwn-xxxx-EXEMPLE, /dev/disque/by-UUID/nvme-xxxx-EXEMPLE et /dev/sda1



 a| 
CacheDeDices
 a| 
S/O
 a| 
Liste
 a| 
Chemin du système d'exploitation hôte vers le périphérique physique utilisé comme périphérique de cache par SolidFire ESDS. Vous devez l'indiquer comme entrée de liste. Voici un exemple de chemin complet pris en charge : /dev/disk/by-ID/nvme-nvme.8086-XXXXXXX-XXXXX-XXXXXX-EXEMPLE

|===


== Trouvez plus d'informations

* https://www.netapp.com/data-storage/solidfire/documentation/["Page des ressources NetApp SolidFire"^]
* https://docs.netapp.com/sfe-122/topic/com.netapp.ndc.sfe-vers/GUID-B1944B0E-B335-4E0B-B9F1-E960BF32AE56.html["Documentation relative aux versions antérieures des produits NetApp SolidFire et Element"^]

