---
permalink: api/reference_element_api_removevirtualnetwork.html 
sidebar: sidebar 
keywords: virtual,network,networks,remove,removing,removevirtualnetwork 
summary: Vous pouvez utiliser la méthode RemoveVirtualNetwork pour supprimer un réseau virtuel ajouté précédemment. 
---
= RemoveVirtualNetwork
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez utiliser le `RemoveVirtualNetwork` méthode de suppression d'un réseau virtuel ajouté précédemment.


NOTE: Cette méthode nécessite soit l'ID virtualNetworkTag soit la virtualNetworkTag comme paramètre, mais pas les deux.


NOTE: Vous ne pouvez pas supprimer un réseau virtuel s'il existe des initiateurs associés. Dissociez d'abord les initiateurs, puis supprimez le réseau virtuel.



== Paramètres

Cette méthode présente les paramètres d'entrée suivants :

|===
| Nom | Description | Type | Valeur par défaut | Obligatoire 


 a| 
VirtualNetworkID
 a| 
ID réseau identifiant le réseau virtuel à supprimer.
 a| 
entier
 a| 
Aucune
 a| 
Oui.



 a| 
VirtualNetworkTag
 a| 
Balise réseau qui identifie le réseau virtuel à supprimer.
 a| 
entier
 a| 
Aucune
 a| 
Oui.

|===


== Valeurs de retour

Cette méthode n'a pas de valeurs de retour.



== Exemple de demande

Les demandes pour cette méthode sont similaires à l'exemple suivant :

[listing]
----
{
  "method": "RemoveVirtualNetwork",
  "params": {
     "virtualNetworkID": 5
    }
}
----


== Exemple de réponse

Cette méthode renvoie une réponse similaire à l'exemple suivant :

[listing]
----
{
   "id": 1,
   "result": {}
}
----


== Nouveau depuis la version

9.6
