---
permalink: api/reference_element_api_getpendingoperation.html 
sidebar: sidebar 
keywords: get,getting,pending,operation,getpendingoperation 
summary: 'Vous pouvez utiliser la méthode GetPendingOperation pour détecter une opération sur un noeud en cours. Cette méthode peut également être utilisée pour signaler une fois l"opération terminée.' 
---
= GetPendingOperation
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez utiliser le `GetPendingOperation` méthode de détection d'une opération sur un nœud en cours d'exécution. Cette méthode peut également être utilisée pour signaler une fois l'opération terminée.



== Paramètres

Cette méthode n'a pas de paramètres d'entrée.



== Valeurs de retour

Cette méthode a les valeurs de retour suivantes :

|===
| Nom | Description | Type 


 a| 
en attente
 a| 
Valeurs possibles :

* True : l'opération est toujours en cours.
* faux :
+
L'opération n'est plus en cours.


 a| 
booléen



 a| 
fonctionnement
 a| 
Nom de l'opération en cours ou terminée.
 a| 
chaîne

|===


== Exemple de demande

Les demandes pour cette méthode sont similaires à l'exemple suivant :

[listing]
----
{
   "method": "GetPendingOperation",
   "params": {},
   "id" : 1
}
----


== Exemple de réponse

Cette méthode renvoie une réponse similaire à l'exemple suivant :

[listing]
----
{
   "id" : 1,
   "result" : {
      "pendingOperation" : {
         "pending" : "true",
         "operation" : "TestDrivesInternal",
      }
   }
}
----


== Nouveau depuis la version

9.6
