---
permalink: api/reference_element_api_completevolumepairing.html 
sidebar: sidebar 
keywords: volume,pairing,CompleteVolumePairing,pair,volumes,complete,completing 
summary: Vous pouvez utiliser CompleteVolumePairing pour terminer le couplage de deux volumes. 
---
= Couplage complet VolumePairing
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez utiliser `CompleteVolumePairing` pour terminer le couplage de deux volumes.



== Paramètres

Cette méthode présente les paramètres d'entrée suivants :

|===
| Nom | Description | Type | Valeur par défaut | Obligatoire 


 a| 
ID de volume
 a| 
ID du volume qui termine la paire de volumes.
 a| 
entier
 a| 
Aucune
 a| 
Oui.



 a| 
Volume PairingKey
 a| 
La clé renvoyée par le xref:reference_element_api_startvolumepairing.adoc[StartVolumePairing] Méthode API.
 a| 
chaîne
 a| 
Aucune
 a| 
Oui.

|===


== Retour de valeur

Cette méthode n'a pas de valeurs de retour.



== Exemple de demande

Les demandes pour cette méthode sont similaires à l'exemple suivant :

[listing]
----
{
   "method": "CompleteVolumePairing",
   "params": {
        "volumeID" : 12,
        "volumePairingKey" : "7b22636c7573746572506169724944223a312c22636c75737465725061697255554944223a2231636561313336322d346338662d343631612d626537322d373435363661393533643266222c22636c7573746572556e697175654944223a2278736d36222c226d766970223a223139322e3136382e3133392e313232222c226e616d65223a224175746f54657374322d63307552222c2270617373776f7264223a22695e59686f20492d64774d7d4c67614b222c22727063436f6e6e656374696f6e4944223a3931333134323634392c22757365726e616d65223a225f5f53465f706169725f50597a796647704c7246564432444a42227d"
        },
   "id" : 1
}
----


== Exemple de réponse

Cette méthode renvoie une réponse similaire à l'exemple suivant :

[listing]
----
{
"id": 1,
"result": {}
}
----


== Nouveau depuis la version

9.6



== Trouvez plus d'informations

xref:reference_element_api_startvolumepairing.adoc[StartVolumePairing]
