---
permalink: api/reference_element_api_cancelgroupclone.html 
sidebar: sidebar 
keywords:  
summary: Vous pouvez utiliser la méthode CancelGroupClone pour arrêter un processus de clonage en cours sur un groupe de volumes. Lorsque vous annulez une opération de clonage de groupe, le système termine et supprime l’opération asynchrone associée. 
---
= CancelGroupClone
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez utiliser le `CancelGroupClone` méthode d'arrêt d'un processus de clonage permanent survenant sur un groupe de volumes. Lorsque vous annulez une opération de clonage de groupe, le système termine et supprime l'opération associée à EasycHandle.



== Paramètre

Cette méthode dispose du paramètre d'entrée suivant :

|===
| Nom | Description | Type | Valeur par défaut | Obligatoire 


 a| 
ID de groupe
 a| 
ID de clone dans le cadre du processus de clonage en cours.
 a| 
entier
 a| 
Aucune
 a| 
Oui.

|===


== Valeurs de retour

Cette méthode n'a pas de valeurs de retour.



== Exemple de demande

Les demandes pour cette méthode sont similaires à l'exemple suivant :

[listing]
----
{
   "method": "CancelGroupClone",
   "params": {
      "cloneID" : 5,
   },
   "id" : 1
}
----


== Exemple de réponse

Cette méthode renvoie une réponse similaire à l'exemple suivant :

[listing]
----
{
  "id" : 1,
  "result" : {}
}
----


== Nouveau depuis la version

9.6
