---
permalink: api/reference_element_api_checkproposedcluster.html 
sidebar: sidebar 
keywords: cluster,creation,check,proposed,checking,nodes,node,before,CheckProposedCluster 
summary: 'Vous pouvez utiliser la méthode CheckProtesdCluster pour tester un ensemble de nœuds de stockage avant de créer un cluster de stockage afin d"identifier les erreurs ou défaillances éventuelles survenant lors de la tentative, comme les capacités mixtes de nœuds non équilibrées ou les types de nœuds non pris en charge pour les clusters de stockage à deux nœuds.' 
---
= CheckedCluster
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez utiliser le `CheckProposedCluster` méthode de test d'un ensemble de nœuds de stockage avant de créer un cluster de stockage en vue d'identifier les erreurs ou défaillances possibles suite à la tentative, telles que les capacités de nœuds mixtes non équilibrées ou les types de nœuds non pris en charge pour les clusters de stockage à deux nœuds.



== Paramètres

Cette méthode dispose du paramètre d'entrée suivant :

|===
| Nom | Description | Type | Valeur par défaut | Obligatoire 


 a| 
nœuds
 a| 
Liste des adresses IP de stockage du jeu initial de nœuds de stockage qui constitue le cluster de stockage.
 a| 
tableau de chaînes
 a| 
Aucune
 a| 
Oui.



 a| 
de force
 a| 
Définissez sur true pour l'exécution sur l'ensemble des nœuds de stockage du cluster de stockage.
 a| 
booléen
 a| 
Aucune
 a| 
Non

|===


== Valeurs de retour

Cette méthode a les valeurs de retour suivantes :

|===


| Nom | Description | Type 


 a| 
ProposedClusterValid
 a| 
Indique si les nœuds de stockage proposés constituent ou non un cluster de stockage valide. Valeurs possibles :

* vrai
* faux

 a| 
booléen



 a| 
ProposedClusterErrors
 a| 
Erreurs qui se produisent lors de la création d'un cluster de stockage à l'aide des nœuds de stockage proposés.
 a| 
tableau de chaînes

|===


== Exemple de demande

Les demandes pour cette méthode sont similaires à l'exemple suivant :

[listing]
----
{
	"method": "CheckProposedCluster",
	"params": {
	"nodes": [
		"192.168.1.11",
		"192.168.1.12",
		"192.168.1.13",
		"192.168.1.14"
	]
},
	"id": 1
}
----


== Exemple de réponse

Cette méthode renvoie une réponse similaire à l'exemple suivant :

[listing]
----
{
	"id": 1,
	"result": {
		"proposedClusterValid": true,
		"proposedClusterErrors": [ ]
	}
}
----


== Nouveau depuis la version

11.0
