---
permalink: api/reference_element_api_modifyvolume.html 
sidebar: sidebar 
keywords: volumes,volume,modifying,modify,change,changing,edit,editing,modifyvolume,settings 
summary: 'Vous pouvez utiliser la méthode Modify Volume pour modifier les paramètres d"un volume existant. Vous pouvez apporter des modifications à un volume à la fois et les modifications ont lieu immédiatement.' 
---
= Modification du volume
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez utiliser le `ModifyVolume` méthode de modification des paramètres d'un volume existant. Vous pouvez apporter des modifications à un volume à la fois et les modifications ont lieu immédiatement.

Si vous ne spécifiez pas de valeurs QoS lors de la modification d'un volume, elles restent les mêmes qu'avant la modification. Pour récupérer les valeurs QoS par défaut d'un volume récemment créé, exécutez la `GetDefaultQoS` méthode.

Si vous devez augmenter la taille d'un volume en cours de réplication, procédez de la manière suivante afin d'éviter les erreurs de réplication :

. Augmentez la taille du volume grâce à la réplicationaccès cible.
. Augmentez la taille de la source ou du volume avec l'accès ReadWrite.


Assurez-vous que les volumes cible et source sont de la même taille.


NOTE: Si vous définissez l'état d'accès sur verrouillé ou réplicationTarget, toutes les connexions iSCSI existantes sont arrêtées.



== Paramètres

Cette méthode présente les paramètres d'entrée suivants :

|===
| Nom | Description | Type | Valeur par défaut | Obligatoire 


 a| 
ID de volume
 a| 
ID du volume à modifier.
 a| 
entier
 a| 
Aucune
 a| 
Oui.



 a| 
l'accès
 a| 
Accès autorisé pour le volume. Valeurs possibles :

* `readOnly`: Seules les opérations de lecture sont autorisées.
* `readWrite`: Les lectures et les écritures sont autorisées.
* `locked`: Aucune lecture ou écriture n'est autorisée. Si elle n'est pas spécifiée, la valeur d'accès ne change pas.
* `replicationTarget`: Identifier un volume comme volume cible pour un ensemble de volumes appariés. Si le volume n'est pas couplé, l'état d'accès est verrouillé. Si aucune valeur n'est spécifiée, la valeur d'accès ne change pas.
* `snapMirrorTarget`: Identifier un volume en tant que volume cible pour la réplication SnapMirror.

 a| 
chaîne
 a| 
Aucune
 a| 
Non



 a| 
ID compte
 a| 
ID comptable auquel le volume est réaffecté. Si aucun n'est spécifié, le nom de compte précédent est utilisé.
 a| 
entier
 a| 
Aucune
 a| 
Non



 a| 
AssociateWithQoSPolicy
 a| 
Associez le volume à la règle de QoS spécifiée. Valeurs possibles :

* `true`: Associez le volume à la règle QoS spécifiée dans le paramètre QoSPolicyID.
* `false`: N'associez pas le volume à la règle QoS spécifiée dans le paramètre QoSPolicyID. Lorsque la valeur est FALSE, toute association de règles existante est supprimée, que vous spécifiiez ou non une stratégie QoS dans le paramètre QoSPolicy.

 a| 
booléen
 a| 
Aucune
 a| 
Non



 a| 
attributs
 a| 
Liste des paires nom-valeur au format d'objet JSON.
 a| 
Objet JSON
 a| 
Aucune
 a| 
Non



 a| 
CREATETIME
 a| 
Chaîne de date ISO 8601 à définir comme nouvelle date de création du volume. Obligatoire si setCreateTime est défini sur vrai.
 a| 
Chaîne ISO 8601
 a| 
Aucune
 a| 
Non



 a| 
EnableSnapMirror orReplication
 a| 
Détermine si le volume peut être utilisé pour la réplication avec les terminaux SnapMirror. Valeurs possibles :

* `true`
* `false`

 a| 
booléen
 a| 
faux
 a| 
Non



| Fif50 | Spécifie le nombre maximal de snapshots de premier entré en premier sorti (FIFO) pris en charge par le volume. Notez que les instantanés FIFO et non FIFO utilisent tous les deux le même pool d'emplacements de snapshot disponibles sur un volume. Utilisez cette option pour limiter la consommation de snapshot FIFO des emplacements de snapshot disponibles. Notez que vous ne pouvez pas modifier cette valeur pour qu'elle soit inférieure au nombre actuel de snapshots FIFO. | entier | Aucune | Non 


| Taille mini | Spécifie le nombre d'emplacements de snapshot réservés aux snapshots de premier entré, premier sorti uniquement. Puisque les instantanés FIFO et non FIFO partagent le même pool, le paramètre minFifoSize réduit le nombre total d'instantanés non FIFO possibles de la même quantité. Notez que vous ne pouvez pas modifier cette valeur de manière à ce qu'elle entre en conflit avec le nombre de snapshots non FIFO en cours. | entier | Aucune | Non 


 a| 
mode
 a| 
Mode de réplication de volume. Valeurs possibles :

* `asynch`: Attend que le système reconnaisse que les données sont stockées sur la source avant d'écrire sur la cible.
* `sync`: N'attend pas que l'accusé de réception de transmission de données de la source commence à écrire des données sur la cible.

 a| 
chaîne
 a| 
Aucune
 a| 
Non



 a| 
la qos
 a| 
Les nouveaux paramètres de qualité de service de ce volume. Si ce n'est pas spécifié, les paramètres de QoS ne sont pas modifiés. Valeurs possibles :

* `minIOPS`
* `maxIOPS`
* `burstIOPS`

 a| 
xref:reference_element_api_qos.adoc[La QoS]
 a| 
Aucune
 a| 
Non



 a| 
QosPolicyID
 a| 
ID de la politique dont les paramètres QoS doivent être appliqués aux volumes spécifiés Ce paramètre s'excluent mutuellement avec le paramètre de qos.
 a| 
entier
 a| 
Aucune
 a| 
Non



 a| 
SetCreateTime
 a| 
Réglez sur vrai pour modifier la date d'enregistrement de la création du volume.
 a| 
booléen
 a| 
Aucune
 a| 
Non



 a| 
Taille totale
 a| 
La nouvelle taille du volume en octets. 1000000000 correspond à 1 Go. La taille est arrondie au mégaoctet le plus proche. Ce paramètre ne peut être utilisé que pour augmenter la taille d'un volume.
 a| 
entier
 a| 
Aucune
 a| 
Non

|===


== Retour de valeur

Cette méthode a la valeur de retour suivante :

|===


| Nom | Description | Type 


 a| 
volumétrie
 a| 
Objet contenant des informations sur le nouveau volume modifié.
 a| 
xref:reference_element_api_volume.adoc[volumétrie]

|===


== Exemple de demande

Les demandes pour cette méthode sont similaires à l'exemple suivant :

[listing]
----
{
  "method": "ModifyVolume",
  "params": {
     "volumeID": 5,
     "attributes": {
        "name1": "value1",
        "name2": "value2",
        "name3": "value3"
     },
     "qos": {
        "minIOPS": 60,
        "maxIOPS": 100,
        "burstIOPS": 150,
        "burstTime": 60
     },
      "access" :"readWrite"
     },
      "totalSize": 20000000000,
     "id": 1
}
----


== Exemple de réponse

Cette méthode renvoie une réponse similaire à l'exemple suivant :

[listing]
----
{
  "id": 1,
  "result": {
      "volume": {
          "access": "readWrite",
          "accountID": 1,
          "attributes": {
              "name1": "value1",
              "name2": "value2",
              "name3": "value3"
          },
          "blockSize": 4096,
          "createTime": "2016-03-28T16:16:13Z",
          "deleteTime": "",
          "enable512e": true,
          "iqn": "iqn.2010-01.com.solidfire:jyay.1459181777648.5",
          "name": "1459181777648",
          "purgeTime": "",
          "qos": {
              "burstIOPS": 150,
              "burstTime": 60,
              "curve": {
                  "4096": 100,
                  "8192": 160,
                  "16384": 270,
                  "32768": 500,
                  "65536": 1000,
                  "131072": 1950,
                  "262144": 3900,
                  "524288": 7600,
                  "1048576": 15000
              },
              "maxIOPS": 100,
              "minIOPS": 60
          },
          "scsiEUIDeviceID": "6a79617900000005f47acc0100000000",
          "scsiNAADeviceID": "6f47acc1000000006a79617900000005",
          "sliceCount": 1,
          "status": "active",
          "totalSize": 1000341504,
          "virtualVolumeID": null,
          "volumeAccessGroups": [
              1
          ],
          "volumeID": 5,
          "volumePairs": []
      }
  }
}
----


== Nouveau depuis la version

9.6



== Trouvez plus d'informations

xref:reference_element_api_getdefaultqos.adoc[GetDefaultQoS]
