---
permalink: api/reference_element_api_modifyqospolicy.html 
sidebar: sidebar 
keywords: modify,modifying,edit,editing,change,changing,qos,policy,policies,modifyqospolicy 
summary: Vous pouvez utiliser la méthode Modify QoSPolicy pour modifier une stratégie QoS existante sur le système. 
---
= Modification de QoSPolicy
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez utiliser le `ModifyQoSPolicy` Méthode de modification d'une politique de QoS existante sur le système



== Paramètres

Cette méthode présente les paramètres d'entrée suivants :

|===


| Nom | Description | Type | Valeur par défaut | Obligatoire 


 a| 
QosPolicyID
 a| 
ID de la règle à modifier.
 a| 
entier
 a| 
Aucune
 a| 
Oui.



 a| 
nom
 a| 
S'il est fourni, le nom de la règle de qualité de service (par ex. Gold, Platinum, Silver) est remplacé par cette valeur.
 a| 
chaîne
 a| 
Aucune
 a| 
Non



 a| 
la qos
 a| 
Le cas échéant, les paramètres de QoS de cette règle sont modifiés selon ces paramètres. Vous pouvez fournir des valeurs QoS partielles et modifier uniquement certains paramètres de QoS.
 a| 
Objet QoS
 a| 
Aucune
 a| 
Non

|===


== Valeurs de retour

Cette méthode a les valeurs de retour suivantes :

|===


| Nom | Description | Type 


 a| 
QosPolicy
 a| 
Détails de la nouvelle politique de QoS.
 a| 
xref:reference_element_api_qospolicy.adoc[QoSPolicy]

|===


== Exemple de demande

Les demandes pour cette méthode sont similaires à l'exemple suivant :

[listing]
----
{
  "id": 1950,
  "method": "ModifyQoSPolicy",
  "params": {
    "qosPolicyID": 2,
    "qos": {
      "minIOPS": 51,
      "maxIOPS": 15002,
      "burstIOPS": 15002
    }
  }
}
----


== Exemple de réponse

Cette méthode renvoie une réponse similaire à l'exemple suivant :

[listing]
----
{
  "id": 1950,
  "result": {
    "qosPolicy": {
      "name": "bronze",
      "qos": {
        "burstIOPS": 15002,
        "burstTime": 60,
        "curve": {
          "4096": 100,
          "8192": 160,
          "16384": 270,
          "32768": 500,
          "65536": 1000,
          "131072": 1950,
          "262144": 3900,
          "524288": 7600,
          "1048576": 15000
        },
        "maxIOPS": 15002,
        "minIOPS": 51
      },
      "qosPolicyID": 2,
      "volumeIDs": [
        2
      ]
    }
  }
}
----


== Nouveau depuis la version

10.0
