---
permalink: api/reference_element_api_testkeyproviderkmip.html 
sidebar: sidebar 
keywords: KMIP,key provider,testing,test 
summary: 'Vous pouvez utiliser la méthode TestKeyProviderKmip pour tester si le fournisseur de clés \(KMIP\) spécifié est accessible et fonctionne normalement.' 
---
= TestKeyProviderKmip
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez utiliser le `TestKeyProviderKmip` Méthode de test permettant de vérifier si le fournisseur de clés KMIP (Key Management Interoperability Protocol) spécifié est accessible et fonctionne normalement.



== Paramètres

Cette méthode présente les paramètres d'entrée suivants :

|===
| Nom | Description | Type | Valeur par défaut | Obligatoire 


 a| 
KeyProviderID
 a| 
ID du fournisseur de clé à tester.
 a| 
entier
 a| 
Aucune
 a| 
Oui.

|===


== Valeurs de retour

Cette méthode n'a pas de valeurs de retour. Le test est considéré comme réussi tant qu'aucune erreur n'est renvoyée.



== Exemple de demande

Les demandes pour cette méthode sont similaires à l'exemple suivant :

[listing]
----
{
  "method": "TestKeyProviderKmip",
  "params": {
    "keyProviderID": 15
  },
"id": 1
}
----


== Exemple de réponse

Cette méthode renvoie une réponse similaire à l'exemple suivant :

[listing]
----
{
   "id": 1,
   "result":
      {}
    }
}
----


== Nouveau depuis la version

11.7
