---
permalink: api/reference_element_api_getkeyproviderkmip.html 
sidebar: sidebar 
keywords: KMIP,key provider,retrieving,get,retrieve 
summary: 'Vous pouvez utiliser la méthode GetKeyProviderKmip pour récupérer des informations sur le fournisseur de clés \(KMIP\) de Key Management Interoperability Protocol spécifié.' 
---
= GetKeyProviderKmip
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez utiliser le `GetKeyProviderKmip` Méthode d'extraction d'informations relatives au fournisseur de clés KMIP (Key Management Interoperability Protocol) spécifié.



== Paramètres

Cette méthode présente les paramètres d'entrée suivants :

|===
| Nom | Description | Type | Valeur par défaut | Obligatoire 


 a| 
KeyProviderID
 a| 
ID de l'objet du fournisseur de clés KMIP à renvoyer.
 a| 
entier
 a| 
Aucune
 a| 
Oui.

|===


== Valeurs de retour

Cette méthode a les valeurs de retour suivantes :

|===
| Nom | Description | Type 


 a| 
KmipKeyProvider
 a| 
Objet contenant des détails sur le fournisseur de clés demandé.
 a| 
link:reference_element_api_keyproviderkmip.html["KeyProviderKmip"]

|===


== Exemple de demande

Les demandes pour cette méthode sont similaires à l'exemple suivant :

[listing]
----
{
  "method": "GetKeyProviderKmip",
  "params": {
    "keyProviderID": 15
    },
"id": 1
}
----


== Exemple de réponse

Cette méthode renvoie une réponse similaire à l'exemple suivant :

[listing]
----
{
   "id": 1,
   "result":
    {
    "kmipKeyProvider": {
        "keyProviderID": 15,
        "kmipCapabilities": "SSL",
        "keyProviderIsActive": true,
        "keyServerIDs": [
            1
        ],
        "keyProviderName": "ProviderName"
    }
   }
}
----


== Nouveau depuis la version

11.7
