---
permalink: api/reference_element_api_getdrivehardwareinfo.html 
sidebar: sidebar 
keywords: drive,get,getting,hardware,info,getdrivehardwareinfo 
summary: 'Vous pouvez utiliser la méthode GetDriveHardwareInfo pour obtenir toutes les informations sur le matériel pour le lecteur donné. Cela comprend généralement les fabricants, les fournisseurs, les versions et d"autres informations d"identification du matériel associé.' 
---
= GetDriveHardwareInfo
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez utiliser le `GetDriveHardwareInfo` méthode d'obtention de toutes les informations matérielles pour le lecteur donné. Cela comprend généralement les fabricants, les fournisseurs, les versions et d'autres informations d'identification du matériel associé.



== Paramètre

Cette méthode dispose du paramètre d'entrée suivant :

|===
| Nom | Description | Type | Valeur par défaut | Obligatoire 


 a| 
ID de conduite
 a| 
ID du lecteur pour la demande.
 a| 
entier
 a| 
Aucune
 a| 
Oui.

|===


== Retour de valeur

Cette méthode a la valeur de retour suivante :

|===
| Nom | Description | Type 


 a| 
résultat
 a| 
Informations matérielles renvoyées pour l'ID de conduite spécifié.
 a| 
xref:reference_element_api_hardwareinfo.adoc[Info matériel]

|===


== Exemple de demande

Les demandes pour cette méthode sont similaires à l'exemple suivant :

[listing]
----
{
   "method": "GetDriveHardwareInfo",
   "params": {
     "driveID": 5
   },
   "id" : 100
}
----


== Exemple de réponse

Cette méthode renvoie une réponse similaire à l'exemple suivant :

[listing]
----
{
   "id" : 100,
   "result" : {
     "driveHardwareInfo" : {
       "description" : "ATA Drive",
       "dev" : "8:80",
       "devpath" : "/devices/pci0000:40/0000:40:01.0/0000:41:00.0/host6/port-6:0/expander-6:0/port-6:0:4/end_device-6:0:4/target6:0:4/6:0:4:0/block/sdf",
       "driveSecurityAtMaximum" : false,
       "driveSecurityFrozen" : false
       "driveSecurityLocked" : false,
       "logicalname" : "/dev/sdf",
       "product" : "INTEL SSDSA2CW300G3",
       "securityFeatureEnabled" : false,
       "securityFeatureSupported" : true,
       "serial" : "CVPR121400NT300EGN",
       "size" : "300069052416",
       "uuid" : "7e1fd5b9-5acc-8991-e2ac-c48f813a3884",
       "version" : "4PC10362"
     }
   }
}
----


== Nouveau depuis la version

9.6



== Trouvez plus d'informations

xref:reference_element_api_listdrives.adoc[Lecteurs de listes]
