---
permalink: api/reference_element_api_listauthsessionbyclusteradmin.html 
sidebar: sidebar 
keywords: cluster admin,sessions,auth sessions,list 
summary: 'Vous pouvez utiliser la méthode ListAuthSessionsByClusterAdmin pour lister toutes les sessions d"authentification associées à l"ID ClusterAdminID spécifié. Si le ClusterAdminID spécifié est mappé à un groupe d"utilisateurs, toutes les sessions d"authentification pour tous les membres de ce groupe seront répertoriées.' 
---
= ListAuthSessionsByClusterAdmin
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez utiliser le `ListAuthSessionsByClusterAdmin` méthode permettant de répertorier toutes les sessions d'authentification associées à l' `ClusterAdminID`. Si le spécifié `ClusterAdminID` correspond à un groupe d'utilisateurs, toutes les sessions d'authentification pour tous les membres de ce groupe seront répertoriées.



== Paramètres

Cette méthode dispose du paramètre d'entrée suivant :

|===
| Nom | Description | Type | Valeur par défaut | Obligatoire 


 a| 
ClusterAdminID
 a| 
Identificateur unique pour l'administrateur du cluster.
 a| 
entier
 a| 
Aucune
 a| 
Oui.

|===


== Valeurs de retour

Cette méthode a la valeur de retour suivante :

|===


| Nom | Description | Type 


 a| 
sessions
 a| 
Liste des informations de session pour les sessions d'authentification.
 a| 
link:reference_element_api_authsessioninfo.html["AuthSessionInfo"]

|===


== Exemple de demande

Les demandes pour cette méthode sont similaires à l'exemple suivant :

[listing]
----
{
    "method": "ListAuthSessionsByClusterAdmin",
    "clusterAdminID": 1
}
----


== Exemple de réponse

Cette méthode renvoie une réponse similaire à l'exemple suivant :

[listing]
----
{
"sessions": [
      {
        "accessGroupList": [
          "administrator"
        ],
        "authMethod": "Cluster",
        "clusterAdminIDs": [
          1
        ],
        "finalTimeout": "2020-03-14T19:21:24Z",
        "idpConfigVersion": 0,
        "lastAccessTimeout": "2020-03-11T19:51:24Z",
        "sessionCreationTime": "2020-03-11T19:21:24Z",
        "sessionID": "b12bfc64-f233-44df-8b9f-6fb6c011abf7",
        "username": "admin"
      }
    ]
}
----


== Nouveau depuis la version

12.0
