---
permalink: api/reference_element_api_getremotelogginghosts.html 
sidebar: sidebar 
keywords: remote,logging,hosts,host,get,getting,getremotelogginghosts 
summary: Vous pouvez utiliser la méthode GetRemoteLoggingits pour obtenir la liste actuelle des serveurs de journaux. 
---
= GetRemoteLoggingits
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez utiliser le `GetRemoteLoggingHosts` méthode d'obtention de la liste actuelle des serveurs de journaux.



== Paramètres

Il n'y a pas de paramètres d'entrée pour `GetRemoteLoggingHosts` .



== Retour de valeur

Le `GetRemoteLoggingHosts` Cette méthode a la valeur de retour suivante :

|===
| Nom | Description | Type 


 a| 
Distanciles
 a| 
Liste l'adresse IP, le nom de domaine complet (FQDN) et les informations de port des hôtes configurés pour recevoir les informations de journalisation transférées.
 a| 
xref:reference_element_api_loggingserver.adoc[Serveur de consignation] baie

|===


== Exemple de demande

Les demandes pour cette méthode sont similaires à l'exemple suivant :

[listing]
----
{
   "id": 3386609,
   "method": "GetRemoteLoggingHosts",
   "params": {}
}
----


== Exemple de réponse

Cette méthode renvoie une réponse similaire à l'exemple suivant :

[listing]
----
{
   "id": 3386609,
   "result": {
      "remoteHosts": [
         {
           "host": "172.16.1.20",
           "port": 10514
         },
         {
           "host": "172.16.1.25"
         },
         {
            "host": "syslogs.lab.company.net",
            "port": 514
         }
      ]
   }
}
----


== Nouveau depuis la version

Disponible à partir d' ONTAP 9.6.



== Trouvez plus d'informations

xref:reference_element_api_setremotelogginghosts.adoc[SetRemoteLoggingids]
