---
permalink: api/reference_element_api_deletestoragecontainers.html 
sidebar: sidebar 
keywords: virtual,volume,storage,container,delete,deleting,vvol,DeleteStorageContainers 
summary: 'Vous pouvez utiliser la méthode DeleteStorageContainers pour supprimer jusqu"à 2000 conteneurs de stockage Virtual Volume \(VVol\) simultanément du système. Les conteneurs de stockage que vous supprimez ne doivent pas contenir de volumes virtuels.' 
---
= DeleteStorageContainers
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez utiliser le `DeleteStorageContainers` Méthode permettant de retirer jusqu'à 2000 conteneurs de stockage de volume virtuel (VVol) simultanément du système. Les conteneurs de stockage que vous supprimez ne doivent pas contenir de volumes virtuels.



== Paramètres

Cette méthode dispose du paramètre d'entrée suivant :

|===
| Nom | Description | Type | Valeur par défaut | Obligatoire 


 a| 
StorageautoreouveID
 a| 
Liste des ID des conteneurs de stockage à supprimer. Vous pouvez spécifier jusqu'à 2000 ID dans la liste.
 a| 
Matrice UUID
 a| 
Aucune
 a| 
Oui.

|===


== Valeurs de retour

Cette méthode n'a pas de valeurs de retour.



== Exemple de demande

Les demandes pour cette méthode sont similaires à l'exemple suivant :

[listing]
----
{
  "method": "DeleteStorageContainers",
    "params": {
        "storageContainerIDs" : ["a9ec1138-e386-4a44-90d7-b9acbbc05176"]
    },
    "id": 1
}
----


== Exemple de réponse

Cette méthode renvoie une réponse similaire à l'exemple suivant :

[listing]
----
{
  "id": 1,
  "result": {}
}
----


== Nouveau depuis la version

9.6
