---
permalink: api/reference_element_api_listvolumes.html 
sidebar: sidebar 
keywords: volume,volumes,list,listing,listvolumes 
summary: Vous pouvez utiliser la méthode Listvolumes pour obtenir une liste des volumes qui se trouvent dans un cluster. Vous pouvez spécifier les volumes que vous souhaitez retourner dans la liste en utilisant les paramètres disponibles. 
---
= Listvolumes
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez utiliser le `ListVolumes` méthode d'obtention de la liste des volumes d'un cluster. Vous pouvez spécifier les volumes que vous souhaitez retourner dans la liste en utilisant les paramètres disponibles.



== Paramètres

Cette méthode présente les paramètres d'entrée suivants :

|===
| Nom | Description | Type | Valeur par défaut | Obligatoire 


 a| 
comptes
 a| 
Seuls les volumes appartenant aux comptes spécifiés ici sont renvoyés. S'excluent mutuellement avec le paramètre Volume IDS.
 a| 
tableau entier
 a| 
Aucune
 a| 
Non



 a| 
Y compris Virtualvolumes
 a| 
Des volumes virtuels sont inclus dans la réponse par défaut. Pour exclure des volumes virtuels, définissez sur false.
 a| 
booléen
 a| 
vrai
 a| 
Non



 a| 
IsPdiffusé
 a| 
Renvoie les volumes qui sont appariés ou non associés. Valeurs possibles :

* True : renvoie tous les volumes couplés.
* FALSE : renvoie tous les volumes non appariés.

 a| 
booléen
 a| 
Aucune
 a| 
Non



 a| 
limite
 a| 
Permet de définir le nombre maximum de résultats de volume renvoyés. S'excluent mutuellement avec le paramètre Volume IDS.
 a| 
entier
 a| 
10000
 a| 
Non



 a| 
ID de volume startVolume
 a| 
Seuls les volumes dont l'ID est supérieur ou égal à cette valeur sont renvoyés. S'excluent mutuellement avec le paramètre Volume IDS.
 a| 
entier
 a| 
Aucune
 a| 
Non



 a| 
ID de volume
 a| 
Une liste des ID de volume. Si vous spécifiez ce paramètre, d'autres paramètres fonctionnent uniquement sur cet ensemble de volumes. S'excluent mutuellement avec les comptes, startVolumeID et les paramètres de limite.
 a| 
tableau entier
 a| 
Non
 a| 
Non



 a| 
Nom du volume
 a| 
Seules les informations sur les objets de volume correspondant au nom du volume sont renvoyées.
 a| 
chaîne
 a| 
Non
 a| 
Non



 a| 
État du volume
 a| 
Seuls les volumes dont le statut est égal à la valeur d'état sont renvoyés. Valeurs possibles :

* création
* snapshots
* actif
* supprimé

 a| 
chaîne
 a| 
Non
 a| 
Non

|===


== Retour de valeur

Cette méthode a la valeur de retour suivante :

|===


| Nom | Description | Type 


 a| 
volumes
 a| 
Liste des volumes.
 a| 
xref:reference_element_api_volume.adoc[volumétrie] baie

|===


== Exemple de demande

Les demandes pour cette méthode sont similaires à l'exemple suivant :

[listing]
----
{
  "method": "ListVolumes",
    "params": {
        "volumeIDs": [1],
        "volumeStatus": "active",
        "isPaired": "false"
    },
    "id": 1
}
----


== Exemple de réponse

Cette méthode renvoie une réponse similaire à l'exemple suivant :

[listing]
----
{
    "id": 1,
    "result": {
        "volumes": [
            {
                "access": "readWrite",
                "accountID": 1,
                "attributes": {},
                "blockSize": 4096,
                "createTime": "2016-03-28T14:39:05Z",
                "deleteTime": "",
                "enable512e": true,
                "iqn": "iqn.2010-01.com.solidfire:testvolume1.1",
                "name": "testVolume1",
                "purgeTime": "",
                "qos": {
                    "burstIOPS": 15000,
                    "burstTime": 60,
                    "curve": {
                        "4096": 100,
                        "8192": 160,
                        "16384": 270,
                        "32768": 500,
                        "65536": 1000,
                        "131072": 1950,
                        "262144": 3900,
                        "524288": 7600,
                        "1048576": 15000
                    },
                    "maxIOPS": 15000,
                    "minIOPS": 50
                },
                "scsiEUIDeviceID": "6a79617900000001f47acc0100000000",
                "scsiNAADeviceID": "6f47acc1000000006a79617900000001",
                "sliceCount": 1,
                "status": "active",
                "totalSize": 5000658944,
                "virtualVolumeID": null,
                "volumeAccessGroups": [],
                "volumeID": 1,
                "volumePairs": []
            }
        ]
    }
}
----


== Nouveau depuis la version

9.6
