---
permalink: api/reference_element_api_getnetworkinterface.html 
sidebar: sidebar 
keywords: nodes,node,network,interface,get,getting,getnetworkinterface 
summary: Vous pouvez utiliser la méthode GetNetworkinterface pour obtenir des informations sur une interface réseau sur un nœud. 
---
= GetNetworkinterface
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez utiliser le `GetNetworkInterface` méthode d'obtention d'informations sur une interface réseau sur un nœud.



== Paramètres

Cette méthode présente les paramètres d'entrée suivants :

|===
| Nom | Description | Type | Valeur par défaut | Obligatoire 


 a| 
interface
 a| 
Nom de l'interface pour obtenir des informations sur chaque nœud. Valeurs possibles :

* Bond1G
* Bond10G

 a| 
chaîne
 a| 
Aucune
 a| 
Non



 a| 
de force
 a| 
Définissez ce paramètre sur true pour s'exécuter sur l'ensemble des nœuds du cluster.
 a| 
booléen
 a| 
faux
 a| 
Non

|===


== Retour de valeur

Cette méthode a la valeur de retour suivante :

|===
| Nom | Description | Type 


 a| 
nœuds
 a| 
Matrice d'objets décrivant l'interface de chaque nœud de stockage du cluster de stockage. Chaque objet du tableau contient les éléments suivants :

* Nodeid : (entier) ID du nœud de stockage dans le cluster de stockage les informations d'interface s'appliquent à.
* résultat: (xref:reference_element_api_networkinterface.adoc[Networkinterface]) Informations de configuration d'interface pour ce nœud de stockage.

 a| 
Baie d'objets JSON

|===


== Exemple de demande

Les demandes pour cette méthode sont similaires à l'exemple suivant :

[listing]
----
{
	"method": "GetNetworkInterface",
	"params": {
		"interface": "Bond1G",
		"force": true
		},
	"id": 1
}
----


== Exemple de réponse

Cette méthode renvoie une réponse similaire à l'exemple suivant :

[listing]
----
{
	"id": 1,
	"result": {
		"nodes": [
			{
				"nodeID": 1,
				"result": {
					"interface": {
						"address": "10.117.64.32",
						"addressV6": "::",
						"broadcast": "10.117.79.255",
						"macAddress": "90:b1:1c:42:e0:1e",
						"mtu": 1500,
						"name": "Bond1G",
						"namespace": false,
						"netmask": "255.255.240.0",
						"status": "UpAndRunning",
						"type": "BondMaster",
						"virtualNetworkTag": 0
					}
				}
			},
			{
				"nodeID": 2,
				"result": {
					"interface": {
						"address": "10.117.64.35",
						"addressV6": "::",
						"broadcast": "10.117.79.255",
						"macAddress": "d4:ae:52:7a:ae:23",
						"mtu": 1500,
						"name": "Bond1G",
						"namespace": false,
						"netmask": "255.255.240.0",
						"status": "UpAndRunning",
						"type": "BondMaster",
						"virtualNetworkTag": 0
					}
				}
			},
			{
				"nodeID": 3,
				"result": {
					"interface": {
						"address": "10.117.64.39",
						"addressV6": "::",
						"broadcast": "10.117.79.255",
						"macAddress": "c8:1f:66:f0:9d:17",
						"mtu": 1500,
						"name": "Bond1G",
						"namespace": false,
						"netmask": "255.255.240.0",
						"status": "UpAndRunning",
						"type": "BondMaster",
						"virtualNetworkTag": 0
					}
				}
			},
			{
				"nodeID": 4,
				"result": {
					"interface": {
						"address": "10.117.64.107",
						"addressV6": "::",
						"broadcast": "10.117.79.255",
						"macAddress": "b8:ca:3a:f5:24:f8",
						"mtu": 1500,
						"name": "Bond1G",
						"namespace": false,
						"netmask": "255.255.240.0",
						"status": "UpAndRunning",
						"type": "BondMaster",
						"virtualNetworkTag": 0
					}
				}
			}
		]
	}
}
----


== Nouveau depuis la version

9.6
