---
permalink: api/reference_element_api_listfibrechannelportinfo.html 
sidebar: sidebar 
keywords: fibre,channel,port,ports,list,listing,listfibrechannelportinfo 
summary: Vous pouvez utiliser la méthode ListFibreChannelPortInfo pour lister les informations sur les ports Fibre Channel. 
---
= ListFibreChannelPortInfo
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez utiliser le `ListFibreChannelPortInfo` Méthode pour lister les informations sur les ports Fibre Channel.

Cette méthode d'API est destinée à être utilisée sur des nœuds individuels ; un ID utilisateur et un mot de passe sont requis pour accéder à des nœuds Fibre Channel individuels. Cependant, cette méthode peut être utilisée sur le cluster si le paramètre force est défini sur vrai. Lorsqu'elles sont utilisées sur le cluster, toutes les interfaces Fibre Channel sont répertoriées.



== Paramètre

Cette méthode dispose du paramètre d'entrée suivant :

|===
| Nom | Description | Type | Valeur par défaut | Obligatoire 


 a| 
de force
 a| 
Définissez sur true pour l'exécution sur l'ensemble des nœuds du cluster.
 a| 
booléen
 a| 
Aucune
 a| 
Non

|===


== Retour de valeur

Cette méthode a la valeur de retour suivante :

|===


| Nom | Description | Type 


 a| 
Ports de fibroChannelports
 a| 
Une liste de tous les ports Fibre Channel physiques ou un port pour un seul nœud.
 a| 
xref:reference_element_api_fibrechannelport.adoc[Port de fibre ChannelPort] baie

|===


== Exemple de demande

Les demandes pour cette méthode sont similaires à l'exemple suivant :

[listing]
----
{
  "method": "ListFibreChannelPortInfo",
    "params": {},
    "id" : 1
}
----


== Exemple de réponse

Cette méthode renvoie une réponse similaire à l'exemple suivant :

[listing]
----
{
  "id": 1,
  "result": {
    "fibreChannelPortInfo": {
      "5": {
        "result": {
          "fibreChannelPorts": [
            {
             "firmware": "7.04.00 (d0d5)",
             "hbaPort": 1,
             "model": "QLE2672",
             "nPortID": "0xc70084",
             "pciSlot": 3,
             "serial": "BFE1335E03500",
             "speed": "8 Gbit",
             "state": "Online",
             "switchWwn": "20:01:00:2a:6a:98:a3:41",
             "wwnn": "5f:47:ac:c8:3c:e4:95:00",
             "wwpn": "5f:47:ac:c0:3c:e4:95:0a"
           },
           {
             "firmware": "7.04.00 (d0d5)",
             "hbaPort": 2,
             "model": "QLE2672",
             "nPortID": "0x0600a4",
             "pciSlot": 3,
             "serial": "BFE1335E03500",
             "speed": "8 Gbit",
             "state": "Online",
             "switchWwn": "20:01:00:2a:6a:9c:71:01",
             "wwnn": "5f:47:ac:c8:3c:e4:95:00",
             "wwpn": "5f:47:ac:c0:3c:e4:95:0b"
           },
           {
             "firmware": "7.04.00 (d0d5)",
             "hbaPort": 1,
             "model": "QLE2672",
             "nPortID": "0xc70044",
             "pciSlot": 2,
             "serial": "BFE1335E04029",
             "speed": "8 Gbit",
             "state": "Online",
             "switchWwn": "20:01:00:2a:6a:98:a3:41",
             "wwnn": "5f:47:ac:c8:3c:e4:95:00",
             "wwpn": "5f:47:ac:c0:3c:e4:95:08"
          },
          {
            "firmware": "7.04.00 (d0d5)",
            "hbaPort": 2,
            "model": "QLE2672",
            "nPortID": "0x060044",
            "pciSlot": 2,
            "serial": "BFE1335E04029",
            "speed": "8 Gbit",
            "state": "Online",
            "switchWwn": "20:01:00:2a:6a:9c:71:01",
            "wwnn": "5f:47:ac:c8:3c:e4:95:00",
            "wwpn": "5f:47:ac:c0:3c:e4:95:09"
          }
       ]
    }
  },
   "6": {
     "result": {
         "fibreChannelPorts": [
        {
           "firmware": "7.04.00 (d0d5)",
           "hbaPort": 1,
           "model": "QLE2672",
           "nPortID": "0x060084",
           "pciSlot": 3,
           "serial": "BFE1335E04217",
           "speed": "8 Gbit",
           "state": "Online",
           "switchWwn": "20:01:00:2a:6a:9c:71:01",
           "wwnn": "5f:47:ac:c8:3c:e4:95:00",
           "wwpn": "5f:47:ac:c0:3c:e4:95:02"
        },
        {
           "firmware": "7.04.00 (d0d5)",
           "hbaPort": 2,
           "model": "QLE2672",
           "nPortID": "0xc700a4",
           "pciSlot": 3,
           "serial": "BFE1335E04217",
           "speed": "8 Gbit",
           "state": "Online",
           "switchWwn": "20:01:00:2a:6a:98:a3:41",
           "wwnn": "5f:47:ac:c8:3c:e4:95:00",
           "wwpn": "5f:47:ac:c0:3c:e4:95:03"
        },
        {
           "firmware": "7.04.00 (d0d5)",
           "hbaPort": 1,
           "model": "QLE2672",
           "nPortID": "0xc70064",
           "pciSlot": 2,
           "serial": "BFE1341E09515",
           "speed": "8 Gbit",
           "state": "Online",
           "switchWwn": "20:01:00:2a:6a:98:a3:41",
           "wwnn": "5f:47:ac:c8:3c:e4:95:00",
           "wwpn": "5f:47:ac:c0:3c:e4:95:00"
        },
        {
           "firmware": "7.04.00 (d0d5)",
           "hbaPort": 2,
           "model": "QLE2672",
           "nPortID": "0x060064",
           "pciSlot": 2,
           "serial": "BFE1341E09515",
           "speed": "8 Gbit",
           "state": "Online",
           "switchWwn": "20:01:00:2a:6a:9c:71:01",
           "wwnn": "5f:47:ac:c8:3c:e4:95:00",
           "wwpn": "5f:47:ac:c0:3c:e4:95:01"
        }
     ]
    }
   }
  }
 }
}
----


== Nouveau depuis la version

9.6
