---
permalink: api/reference_element_api_getipmiconfig.html 
sidebar: sidebar 
keywords: hardware,sensor,config,configuration,get,getting,getipmiconfig 
summary: Vous pouvez utiliser la méthode GetIpmiConfig pour récupérer les informations de capteur matériel à partir des capteurs de votre nœud. 
---
= GetIpmiConfig
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez utiliser le `GetIpmiConfig` méthode pour récupérer les informations relatives au capteur matériel à partir des capteurs de votre nœud.



== Paramètre

Cette méthode dispose du paramètre d'entrée suivant :

|===
| Nom | Description | Type 


 a| 
ChassisType
 a| 
Permet d'afficher des informations pour chaque type de châssis de nœud. Valeurs possibles :

* tous : renvoie des informations sur le capteur pour chaque type de châssis.
* {chassis type} : renvoie les informations relatives au capteur pour un type de châssis spécifié.

 a| 
chaîne

|===


== Valeurs de retour

Cette méthode a les valeurs de retour suivantes :

|===
| Nom | Description | Type 


 a| 
Nom du capteur
 a| 
Nom du capteur trouvé.
 a| 
chaîne



 a| 
UniqueSensorID
 a| 
Identifiant unique du capteur.
 a| 
chaîne

|===


== Exemple de demande

Les demandes pour cette méthode sont similaires à l'exemple suivant :

[listing]
----
{
  "method": "GetIpmiConfig",
  "params": {
     "chassisType"; "all"
     },
  "id" : 1
}
----


== Exemple de réponse

Cette méthode renvoie une réponse similaire à l'exemple suivant :

[listing]
----
{
 "id": 1,
   "result": {
     "nodes": [
         {
           "nodeID": 1,
           "result": {
             "ipmiConfig": {
                "C220M4": [
                    {
                     "sensorName": "Fan1A RPM",
                     "uniqueSensorID": "29.1:0xf"
                    },
                    {
                      "sensorName": "Fan1B RPM",
                      "uniqueSensorID": "29.1:0x10"
                    },
                    {
                      "sensorName": "Fan2A RPM",
                      "uniqueSensorID": "29.2:0x11"
                    },
                    {
                      "sensorName": "Fan2B RPM",
                      "uniqueSensorID": "29.2:0x12"
                    },
                    {
                      "sensorName": "Fan3A RPM",
                      "uniqueSensorID": "29.3:0x13"
                    },
                    {
                      "sensorName": "Fan3B RPM",
                      "uniqueSensorID": "29.3:0x14"
                    },
                    {
                      "sensorName": "Fan4A RPM",
                      "uniqueSensorID": "29.4:0x15"
                    },
                    {
                      "sensorName": "Fan4B RPM",
                      "uniqueSensorID": "29.4:0x16"
                    },
                    {
                      "sensorName": "Fan5A RPM",
                      "uniqueSensorID": "29.5:0x17"
                    },
                    {
                      "sensorName": "Fan5B RPM",
                      "uniqueSensorID": "29.5:0x18"
                    },
                    {
                      "sensorName": "Fan6A RPM",
                      "uniqueSensorID": "29.6:0x19"
                    },
                    {
                      "sensorName": "Fan6B RPM",
                      "uniqueSensorID": "29.6:0x1a"
                    },
                    {
                      "sensorName": "Exhaust Temp",
                      "uniqueSensorID": "7.1:0x1"
                    },
                    {
                      "sensorName": "Inlet Temp",
                      "uniqueSensorID": "7.1:0x4"
                    },
                    {
                      "sensorName": "PS1",
                      "uniqueSensorID": "10.1:0x26"
                    },
                    {
                      "sensorName": "PS2",
                      "uniqueSensorID": "10.2:0x2c"
                    }
                ],
                "R620": [
                    {
                      "sensorName": "Fan1A RPM",
                      "uniqueSensorID": "7.1:0x30"
                    },
                    {
                      "sensorName": "Fan1B RPM",
                      "uniqueSensorID": "7.1:0x31"
                    },
                    {
                      "sensorName": "Fan2A RPM",
                      "uniqueSensorID": "7.1:0x32"
                    },
                    {
                      "sensorName": "Fan2B RPM",
                      "uniqueSensorID": "7.1:0x33"
                    },
                    {
                      "sensorName": "Fan3A RPM",
                      "uniqueSensorID": "7.1:0x34"
                    },
                    {
                      "sensorName": "Fan3B RPM",
                      "uniqueSensorID": "7.1:0x35"
                    },
                    {
                      "sensorName": "Fan4A RPM",
                      "uniqueSensorID": "7.1:0x36"
                    },
                    {
                      "sensorName": "Fan4B RPM",
                      "uniqueSensorID": "7.1:0x37"
                    },
                    {
                      "sensorName": "Fan5A RPM",
                      "uniqueSensorID": "7.1:0x38"
                    },
                    {
                      "sensorName": "Fan5B RPM",
                      "uniqueSensorID": "7.1:0x39"
                    },
                    {
                      "sensorName": "Fan6A RPM",
                      "uniqueSensorID": "7.1:0x3a"
                    },
                    {
                      "sensorName": "Fan6B RPM",
                      "uniqueSensorID": "7.1:0x3b"
                    },
                    {
                      "sensorName": "Fan7A RPM",
                      "uniqueSensorID": "7.1:0x3c"
                    },
                    {
                      "sensorName": "Fan7B RPM",
                      "uniqueSensorID": "7.1:0x3d"
                    },
                    {
                      "sensorName": "Exhaust Temp",
                      "uniqueSensorID": "7.1:0x1"
                    },
                    {
                      "sensorName": "Inlet Temp",
                      "uniqueSensorID": "7.1:0x4"
                    },
                    {
                      "sensorName": "PS1",
                      "uniqueSensorID": "10.1:0x62"
                    },
                    {
                      "sensorName": "PS2",
                      "uniqueSensorID": "10.2:0x63"
                    }
               ],
          }
----


== Nouveau depuis la version

9.6
