---
permalink: api/reference_element_api_listvirtualvolumehosts.html 
sidebar: sidebar 
keywords: virtual,volume,vvol,host,hosts,list,listing,known,listvirtualvolumehosts 
summary: 'Vous pouvez utiliser la méthode ListVolumeVirtualHots pour obtenir la liste de tous les hôtes de volumes virtuels connus pour le cluster. Un hôte de volume virtuel est un hôte VMware ESX qui a démarré une session avec le fournisseur d"API VASA.' 
---
= ListVirtualVolumeHots
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez utiliser le `ListVirtualVolumeHosts` méthode d'obtention de la liste de tous les hôtes de volume virtuel connus du cluster. Un hôte de volume virtuel est un hôte VMware ESX qui a démarré une session avec le fournisseur d'API VASA.



== Paramètres

Cette méthode dispose du paramètre d'entrée suivant :

|===
| Nom | Description | Type | Valeur par défaut | Obligatoire 


 a| 
ID de l'hôte virtualVolume
 a| 
Liste des ID d'hôte de volume virtuel pour lesquels récupérer des informations. Si vous omettez ce paramètre, la méthode renvoie des informations sur tous les hôtes de volume virtuel.
 a| 
Tableau UUID virtualVolumeHostID
 a| 
Aucune
 a| 
Non

|===


== Retour de valeur

Cette méthode a la valeur de retour suivante :

|===
| Nom | Description | Type 


 a| 
hôtes
 a| 
Liste d'objets décrivant les hôtes du volume virtuel dans le cluster.
 a| 
xref:reference_element_api_host.adoc[hôte] baie

|===


== Exemple de demande

Les demandes pour cette méthode sont similaires à l'exemple suivant :

[listing]
----
{
  "method": "ListVirtualVolumeHosts",
    "params": {
    },
    "id": 1
}
----


== Exemple de réponse

Cette méthode renvoie une réponse similaire à l'exemple suivant :

[listing]
----
{
  "id": 1,
  "result": {
    "hosts": [
      {
        "bindings": [],
        "clusterID": "5ebdb4ad-9617-4647-adfd-c1013578483b",
        "hostAddress": "172.30.89.117",
        "initiatorNames": [
          "iqn.1998-01.com.vmware:zdc-dhcp-0-c-29-d6-4b-f1-1a0cd614",
          "iqn.1998-01.com.vmware:zdc-dhcp-0-c-29-d6-4b-f1-5bcf9254"
        ],
        "virtualVolumeHostID": "564de1a4-9a99-da0f-8b7c-3a41dfd64bf1",
        "visibleProtocolEndpointIDs": [
          "5dd53da0-b9b7-43f9-9b7e-b41c2558e92b"
        ]
      }
    ]
  }
}
----


== Nouveau depuis la version

9.6
