---
permalink: api/reference_element_api_getremotelogginghosts.html 
sidebar: sidebar 
keywords: remote,logging,hosts,host,get,getting,getremotelogginghosts 
summary: Vous pouvez utiliser la méthode GetRemoteLoggingits pour obtenir la liste actuelle des serveurs de journaux. 
---
= GetRemoteLoggingits
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez utiliser le `GetRemoteLoggingHosts` méthode d'obtention de la liste actuelle des serveurs de journaux.



== Paramètres

Cette méthode n'a pas de paramètres d'entrée.



== Retour de valeur

Cette méthode a la valeur de retour suivante :

|===
| Nom | Description | Type 


 a| 
Distanciles
 a| 
Liste des informations d'adresse IP et de port sur les hôtes configurés pour recevoir les informations de journalisation transmises.
 a| 
xref:reference_element_api_loggingserver.adoc[Serveur de consignation] baie

|===


== Exemple de demande

Les demandes pour cette méthode sont similaires à l'exemple suivant :

[listing]
----
{
   "id": 3386609,
   "method": "GetRemoteLoggingHosts",
   "params": {}
}
----


== Exemple de réponse

Cette méthode renvoie une réponse similaire à l'exemple suivant :

[listing]
----
{
   "id": 3386609,
   "result": {
      "remoteHosts": [
         {
           "host": "172.16.1.20",
           "port": 10514
         },
         {
           "host": "172.16.1.25"
         }
      ]
   }
}
----


== Nouveau depuis la version

9.6



== Trouvez plus d'informations

xref:reference_element_api_setremotelogginghosts.adoc[SetRemoteLoggingids]
