---
permalink: api/reference_element_api_listevents.html 
sidebar: sidebar 
keywords: cluster,list,listing,event,events,listevents 
summary: Vous pouvez utiliser la méthode ListEvents pour répertorier les événements détectés sur le cluster, triés du plus ancien au plus récent. 
---
= ListEvents
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez utiliser le `ListEvents` méthode permettant de répertorier les événements détectés sur le cluster, triés du plus ancien au plus récent.



== Paramètres

Cette méthode présente les paramètres d'entrée suivants :

|===
| Nom | Description | Type | Valeur par défaut | Obligatoire 


 a| 
ID de conduite
 a| 
Spécifie que seuls les événements avec cet ID de lecteur seront renvoyés.
 a| 
entier
 a| 
0
 a| 
Non



 a| 
ID d'événement
 a| 
Identifie la fin d'une plage d'ID d'événement à renvoyer.
 a| 
entier
 a| 
(illimité)
 a| 
Non



 a| 
EndPublishTime
 a| 
Spécifie que seuls les événements publiés plus tôt que cette heure seront renvoyés.
 a| 
chaîne
 a| 
0
 a| 
Non



 a| 
EndReportTime
 a| 
Spécifie que seuls les événements signalés plus tôt que cette heure seront renvoyés.
 a| 
chaîne
 a| 
0
 a| 
Non



 a| 
Type d'événement
 a| 
Spécifie le type d'événements à renvoyer. Voir xref:reference_element_api_event.adoc[événement] pour les types d'événements possibles.
 a| 
chaîne
 a| 
0
 a| 
Non



 a| 
MaxEvents
 a| 
Spécifie le nombre maximal d'événements à renvoyer.
 a| 
entier
 a| 
(illimité)
 a| 
Non



 a| 
ID de nœud
 a| 
Spécifie que seuls les événements avec cet ID de nœud seront renvoyés.
 a| 
entier
 a| 
 a| 



 a| 
Service
 a| 
Spécifie que seuls les événements avec cet ID de service seront renvoyés.
 a| 
 a| 
 a| 



 a| 
StartEventID
 a| 
Identifie le début d'une série d'événements à renvoyer.
 a| 
entier
 a| 
0
 a| 
Non



 a| 
StartPublishTime
 a| 
Spécifie que seuls les événements publiés après cette période seront renvoyés.
 a| 
chaîne
 a| 
0
 a| 
Non



 a| 
StartReportTime
 a| 
Spécifie que seuls les événements signalés après cette période seront renvoyés.
 a| 
chaîne
 a| 
0
 a| 
Non

|===


== Retour de valeur

Cette méthode a la valeur de retour suivante :

|===


| Nom | Description | Type 


 a| 
événements
 a| 
Liste des événements.
 a| 
xref:reference_element_api_event.adoc[événement] baie

|===


== Exemple de demande

Les demandes pour cette méthode sont similaires à l'exemple suivant :

[listing]
----
{
   "method": "ListEvents",
   "params": {
   },
   "id" : 1
}
----


== Exemple de réponse

Cette méthode renvoie une réponse similaire à l'exemple suivant :

[listing]
----
{
  "id":1,
  "result":{
    "events":[
       {
          "details":
            {
              "paramGCGeneration":1431550800,
              "paramServiceID":2
            },
          "driveID":0,
          "eventID":2131,
          "eventInfoType":"gcEvent",
          "message":"GC Cluster Coordination Complete",
          "nodeID":0,
          "serviceID":2,
          "severity":0,
          "timeOfPublish":"2015-05-13T21:00:02.361354Z",
          "timeOfReport":"2015-05-13T21:00:02.361269Z"
       },{
          "details":
               {
                  "eligibleBS":[5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,24,25,26,27,28,29,30,31,40,41,42,43,44,45,46,47,52,53,54,55,56,57,58,59,60],
                  "generation":1431550800,
                  "participatingSS":[23,35,39,51]
               },
          "driveID":0,
          "eventID":2130,
          "eventInfoType":"gcEvent",
          "message":"GCStarted",
          "nodeID":0,
          "serviceID":2,
          "severity":0,
          "timeOfPublish":"2015-05-13T21:00:02.354128Z",
          "timeOfReport":"2015-05-13T21:00:02.353894Z"
       },{
          "details":"",
          "driveID":0,
          "eventID":2129,
          "eventInfoType":"tSEvent",
          "message":"return code:2 t:41286 tt:41286 qcc:1 qd:1 qc:1 vrc:1 tt:2 ct:Write etl:524288",
          "nodeID":0,
          "serviceID":0,
          "severity":0,
          "timeOfPublish":"2015-05-13T20:45:21.586483Z",
          "timeOfReport":"2015-05-13T20:45:21.586311Z"
       }
     ]
   }
}
----


== Nouveau depuis la version

9.6
