---
permalink: api/reference_element_api_deletekeyproviderkmip.html 
sidebar: sidebar 
keywords: KMIP,key provider,deleting,delete 
summary: 'Vous pouvez utiliser la méthode DeleteKeyProviderKmip pour supprimer le fournisseur de clés \(KMIP\) inactif spécifié.' 
---
= DeleteKeyProviderKmip
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez utiliser le `DeleteKeyProviderKmip` Méthode de suppression du fournisseur de clés KMIP (Key Management Interoperability Protocol) inactif spécifié.



== Paramètres

Cette méthode présente les paramètres d'entrée suivants :

|===
| Nom | Description | Type | Valeur par défaut | Obligatoire 


 a| 
KeyProviderID
 a| 
ID du fournisseur de clés à supprimer.
 a| 
entier
 a| 
Aucune
 a| 
Oui.

|===


== Valeurs de retour

Cette méthode n'a pas de valeurs de retour. L'opération de suppression est considérée comme réussie car il n'y a pas d'erreur.



== Exemple de demande

Les demandes pour cette méthode sont similaires à l'exemple suivant :

[listing]
----
{
  "method": "DeleteKeyProviderKmip",
  "params": {
    "keyProviderID": "1"
    },
"id": 1
}
----


== Exemple de réponse

Cette méthode renvoie une réponse similaire à l'exemple suivant :

[listing]
----
{
   "id": 1,
   "result":
      {}
}
----


== Nouveau depuis la version

11.7
