---
permalink: api/reference_element_api_loggingserver.html 
sidebar: sidebar 
keywords: object,objects,loggingServer 
summary: 'L"objet Loggingiserveur contient des informations sur tous les hôtes de consignation configurés pour le cluster de stockage. Vous pouvez utiliser GetRemoteLoggingigs pour déterminer ce que sont les hôtes de consignation actuels, puis utiliser SetRemoteLoggingits pour définir la liste désirée des hôtes de consignation actuels et nouveaux.' 
---
= Serveur de consignation
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
L'objet loggingServer stocke les informations relatives aux hôtes de journalisation configurés pour le cluster de stockage.  Utiliser `GetRemoteLoggingHosts` pour afficher les hôtes de journalisation actuels, puis utiliser `SetRemoteLoggingHosts` pour définir la liste souhaitée des hôtes de journalisation actuels et nouveaux.



== Membres d'objet

Cet objet contient les membres suivants :

|===
| Nom | Description | Type 


 a| 
hôte
 a| 
Nom de domaine complet (FQDN) ou adresse IP du serveur de journalisation
 a| 
chaîne



 a| 
port
 a| 
Numéro de port utilisé pour communiquer avec le serveur de journalisation
 a| 
entier

|===
.Informations associées
* link:reference_element_api_getremotelogginghosts.html["GetRemoteLoggingits"]
* link:reference_element_api_setremotelogginghosts.html["SetRemoteLoggingids"]

