---
permalink: api/reference_element_api_disableencryptionatrest.html 
sidebar: sidebar 
keywords: element, api, encryption, disable, disabling, at rest, rest, DisableEncryptionAtRest 
summary: 'Vous pouvez utiliser la méthode DisableEncryptionAtRest pour supprimer le cryptage précédemment appliqué au cluster à l"aide de la méthode EnableEncryptionAtRest. Cette méthode de désactivation est asynchrone et renvoie une réponse avant que le cryptage ne soit désactivé. Vous pouvez utiliser la méthode GetClusterInfo pour interroger le système afin de voir une fois le processus terminé.' 
---
= DisableEncryptionAtRest
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez utiliser le `DisableEncryptionAtRest` méthode de suppression du chiffrement précédemment appliqué au cluster à l'aide du `EnableEncryptionAtRest` méthode. Cette méthode de désactivation est asynchrone et renvoie une réponse avant que le cryptage ne soit désactivé. Vous pouvez utiliser le `GetClusterInfo` méthode d'interrogation du système pour voir quand le processus est terminé.


TIP: Pour voir l'état actuel du chiffrement au repos et/ou logiciel au repos sur le cluster, utilisez le link:../api/reference_element_api_getclusterinfo["obtenir la méthode d'information sur le cluster"^]. Vous pouvez utiliser le `GetSoftwareEncryptionAtRestInfo` link:../api/reference_element_api_getsoftwareencryptionatrestinfo["méthode d'obtention des informations que le cluster utilise pour chiffrer les données au repos"^].


NOTE: Vous ne pouvez pas utiliser cette méthode pour désactiver le chiffrement logiciel au repos. Pour désactiver le chiffrement logiciel au repos, vous devez link:reference_element_api_createcluster.html["créez un nouveau cluster"] le chiffrement logiciel des données au repos est désactivé.



== Paramètres

Cette méthode n'a pas de paramètres d'entrée.



== Valeurs de retour

Cette méthode n'a pas de valeurs de retour.



== Exemple de demande

Les demandes pour cette méthode sont similaires à l'exemple suivant :

[listing]
----
{
   "method": "DisableEncryptionAtRest",
   "params": {},
   "id": 1
}
----


== Exemple de réponse

Cette méthode renvoie une réponse similaire à l'exemple suivant :

[listing]
----
{
   "id" : 1,
  "result" : {}
}
----


== Nouveau depuis la version

9.6

[discrete]
== Trouvez plus d'informations

* link:api/reference_element_api_getclusterinfo.html["GetClusterInfo"]
* https://www.netapp.com/data-storage/solidfire/documentation/["Page des ressources NetApp SolidFire"^]
* https://docs.netapp.com/sfe-122/topic/com.netapp.ndc.sfe-vers/GUID-B1944B0E-B335-4E0B-B9F1-E960BF32AE56.html["Documentation relative aux versions antérieures des produits NetApp SolidFire et Element"^]

