---
permalink: api/reference_element_api_getnodesupportedtlsciphers.html 
sidebar: sidebar 
keywords: tls,cipher,ciphers,get,getting,supported,getnodesupportedtlsciphers 
summary: Vous pouvez utiliser la méthode GetNodeSupportedTlsCiphers sur un seul nœud pour obtenir la liste des chiffrements TLS actuellement pris en charge sur ce nœud. Vous pouvez utiliser cette méthode sur les nœuds de stockage et de gestion. 
---
= GetNodeSupportedTlsCiphers
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez utiliser le `GetNodeSupportedTlsCiphers` Méthode sur un seul nœud pour obtenir la liste des chiffrements TLS qui sont actuellement pris en charge sur ce nœud. Vous pouvez utiliser cette méthode sur les nœuds de stockage et de gestion.



== Paramètre

Cette méthode n'a pas de paramètres d'entrée.



== Valeurs de retour

Cette méthode a les valeurs de retour suivantes :

|===
| Nom | Description | Type 


 a| 
Ciphers de données
 a| 
Liste des suites de chiffrement TLS obligatoires pour le nœud. Ces chiffrements sont toujours actifs sur le nœud.
 a| 
chaîne



 a| 
DefaultSupplementalCiphers
 a| 
Liste des suites de chiffrement TLS supplémentaires par défaut pour le nœud. Les chiffrements supplémentaires sont restaurés dans cette liste lorsque vous exécutez la méthode API ResetNodeSupplementalTlsCiphers.
 a| 
chaîne



 a| 
SupprotedSupplementagentalCiphers
 a| 
Liste des suites de chiffrement TLS supplémentaires disponibles que vous pouvez configurer à l'aide de la méthode API SetNodeSupplemental TlsCiphers.
 a| 
chaîne

|===


== Exemple de demande

Les demandes pour cette méthode sont similaires à l'exemple suivant :

[listing]
----
{
  "method": "GetNodeSupportedTlsCiphers",
  "params": {},
  "id" : 1
}
----


== Exemple de réponse

Cette méthode renvoie une réponse similaire à l'exemple suivant :

[listing]
----
{
  "id" : 1,
  "result" : {
	"defaultSupplementalCiphers": [
		"DHE-RSA-AES128-SHA256",
		"DHE-RSA-AES128-GCM-SHA256",
		"ECDHE-RSA-AES128-SHA256",
		"ECDHE-RSA-AES128-GCM-SHA256"
	],
	"mandatoryCiphers": [
		"DHE-RSA-AES256-SHA256",
		"DHE-RSA-AES256-GCM-SHA384",
		"ECDHE-RSA-AES256-SHA384",
		"ECDHE-RSA-AES256-GCM-SHA384"
	],
	"supportedSupplementalCiphers": [
		"DHE-RSA-AES128-SHA256",
		"DHE-RSA-AES128-GCM-SHA256",
		"ECDHE-RSA-AES128-SHA256",
		"ECDHE-RSA-AES128-GCM-SHA256",
		"DHE-RSA-AES256-SHA",
		"ECDHE-RSA-AES256-SHA",
		"DHE-RSA-CAMELLIA256-SHA",
		"DHE-RSA-AES128-SHA",
		"ECDHE-RSA-AES128-SHA",
		"DHE-RSA-CAMELLIA128-SHA"
	]
}
}
----