---
permalink: api/reference_element_api_getschedule.html 
sidebar: sidebar 
keywords: snapshot,schedule,get,getting,getschedule 
summary: Vous pouvez utiliser GetSchedule pour obtenir des informations sur un instantané planifié. 
---
= GetSchedule
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez utiliser `GetSchedule` pour obtenir des informations sur un instantané planifié.

Vous pouvez afficher des informations sur un planning spécifique s'il existe de nombreuses planifications d'instantanés dans le système. Vous récupérez également des informations sur plusieurs planifications avec cette méthode en spécifiant des ID supplémentaires dans le paramètre scheduleID.



== Paramètre

Cette méthode dispose du paramètre d'entrée suivant :

|===
| Nom | Description | Type | Valeur par défaut | Obligatoire 


 a| 
ID planiche
 a| 
ID unique de la planification ou de plusieurs planifications à afficher.
 a| 
entier
 a| 
Aucune
 a| 
Oui.

|===


== Retour de valeur

Cette méthode a la valeur de retour suivante :

|===
| Nom | Description | Type 


 a| 
planification
 a| 
Un tableau d'attributs de planification.
 a| 
xref:reference_element_api_schedule.adoc[planification] baie

|===


== Exemple de demande

Les demandes pour cette méthode sont similaires à l'exemple suivant :

[listing]
----
{
"method": "GetSchedule",
  "params": {
              "scheduleID" : 2
      },
   "id" : 1
}
----


== Exemple de réponse

Cette méthode renvoie une réponse similaire à l'exemple suivant :

[listing]
----
{
  "id": 1,
  "result": {
    "schedule": {
      "attributes": {
        "frequency": "Time Interval"
      },
       "hasError": false,
       "hours": 0,
       "lastRunStatus": "Success",
       "lastRunTimeStarted": "2015-03-23T21:25:00Z",
       "minutes": 2,
       "monthdays": [],
       "paused": false,
       "recurring": true,
       "runNextInterval": false,
       "scheduleID": 2,
       "scheduleInfo": {
          "name": "MCA2",
          "volumeID": "3"
       },
       "scheduleName": "MCAsnapshot2",
       "scheduleType": "Snapshot",
       "startingDate": "2015-03-23T19:28:57Z",
       "toBeDeleted": false,
       "weekdays": []
      }
   }
}
----


== Nouveau depuis la version

9.6
