---
permalink: api/reference_element_api_deleteauthsession.html 
sidebar: sidebar 
keywords: authentication sessions,delete 
summary: 'Vous pouvez utiliser la méthode DeleteAuthSession pour supprimer une session d"authentification individuelle. Si l"utilisateur appelant ne se trouve pas dans ClusterAdmins / Administrator Access Group, seule la session d"authentification appartenant à l"utilisateur appelant peut être supprimée.' 
---
= DeleteAuthsession
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez utiliser le `DeleteAuthSession` méthode de suppression d'une session d'authentification utilisateur individuelle. Si l'utilisateur appelant ne se trouve pas dans ClusterAdmins / Administrator Access Group, seule la session d'authentification appartenant à l'utilisateur appelant peut être supprimée.



== Paramètres

Cette méthode dispose du paramètre d'entrée suivant :

|===
| Nom | Description | Type | Valeur par défaut | Obligatoire 


 a| 
ID de session
 a| 
Identifiant unique pour la session d'authentification à supprimer.
 a| 
UUID
 a| 
Aucune
 a| 
Oui.

|===


== Valeurs de retour

Cette méthode a la valeur de retour suivante :

|===


| Nom | Description | Type 


 a| 
gestion
 a| 
Informations de session pour la session d'authentification de suppression.
 a| 
link:reference_element_api_authsessioninfo.md#GUID-FF0CE38C-8F99-4F23-8A6F-F6EA4487E808["AuthSessionInfo"]

|===


== Exemple de demande

Les demandes pour cette méthode sont similaires à l'exemple suivant :

[listing]
----
{
    "method": "DeleteAuthSession",
    "params": {
        "sessionID": "a862a8bb-2c5b-4774-a592-2148e2304713"
    },
    "id": 1
}
----


== Exemple de réponse

Cette méthode renvoie une réponse similaire à l'exemple suivant :

[listing]
----
{
    "id": 1,
    "result": {
        "session": {
            "accessGroupList": [
                "administrator"
            ],
            "authMethod": "Cluster",
            "clusterAdminIDs": [
                1
            ],
            "finalTimeout": "2020-04-09T17:51:30Z",
            "idpConfigVersion": 0,
            "lastAccessTimeout": "2020-04-06T18:21:33Z",
            "sessionCreationTime": "2020-04-06T17:51:30Z",
            "sessionID": "a862a8bb-2c5b-4774-a592-2148e2304713",
            "username": "admin"
        }
    }
}
----


== Nouveau depuis la version

12.0
