---
permalink: api/reference_element_api_startvolumepairing.html 
sidebar: sidebar 
keywords: volume,pair,pairing,start,starting,startvolumepairing 
summary: 'Vous pouvez utiliser la méthode de transmission StartVolumePairing pour créer une clé codée à partir d"un volume utilisé pour coupler avec un autre volume. La clé créée par cette méthode est utilisée dans la méthode CompleteVolumePairing pour établir un couplage de volume.' 
---
= StartVolumePairing
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez utiliser le `StartVolumePairing` méthode de création d'une clé codée à partir d'un volume utilisé pour coupler avec un autre volume. La clé créée par cette méthode est utilisée dans le `CompleteVolumePairing` méthode d'établissement d'un couplage de volume.



== Paramètres

Cette méthode présente les paramètres d'entrée suivants :

|===
| Nom | Description | Type | Valeur par défaut | Obligatoire 


 a| 
mode
 a| 
Mode du volume sur lequel démarrer le processus de couplage. Le mode ne peut être défini que si le volume est le volume source. Valeurs possibles :

* `Async`: Les écritures sont acquittées lorsqu'elles sont terminées localement. Le cluster n'attend pas que les écritures soient répliquées sur le cluster cible. (Valeur par défaut si aucun paramètre de mode n'est spécifié.)
* `Sync`: Source reconnaît l'écriture lorsque les données sont stockées localement et sur le cluster distant.
* `SnapshotsOnly`: Seuls les snapshots créés sur le cluster source sont répliqués. Les écritures actives du volume source ne sont pas répliquées.

 a| 
chaîne
 a| 
Aucune
 a| 
Non



 a| 
ID de volume
 a| 
ID du volume sur lequel lancer le processus de couplage.
 a| 
entier
 a| 
Aucune
 a| 
Oui.

|===


== Retour de valeur

Cette méthode a la valeur de retour suivante :

|===
| Nom | Description | Type 


 a| 
Volume PairingKey
 a| 
Chaîne de caractères utilisée par le xref:reference_element_api_completevolumepairing.adoc[Couplage complet VolumePairing] Méthode API.
 a| 
chaîne

|===


== Exemple de demande

Les demandes pour cette méthode sont similaires à l'exemple suivant :

[listing]
----
{
   "method": "StartVolumePairing",
   "params": {
         "mode": "Async",
	 "volumeID" : 14
      },
   "id" : 1
}
----


== Exemple de réponse

Cette méthode renvoie une réponse similaire à l'exemple suivant :

[listing]
----
{
   "id" : 1,
   "result" : {
      "volumePairingKey" : "7b226d766970223a223139322e3136382e3133392e313232222c22766f6c756d654944223a312c22766f6c756d654e616d65223a2254657374222c22766f6c756d655061697255554944223a2236393632346663622d323032652d343332352d613536392d656339633635356337623561227d"
      }
}
----


== Nouveau depuis la version

9.6



== Trouvez plus d'informations

xref:reference_element_api_completevolumepairing.adoc[Couplage complet VolumePairing]
