---
permalink: api/reference_element_api_listactiveauthsessions.html 
sidebar: sidebar 
keywords: active,sessions,authentication session,list 
summary: 'Vous pouvez utiliser la méthode ListeActiveAuthSessions pour répertorier toutes les sessions authentifiées actives. Seuls les utilisateurs disposant de droits d"accès administrateur peuvent appeler cette méthode.' 
---
= ActiveListences
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez utiliser le `ListActiveAuthSessions` méthode permettant de répertorier toutes les sessions authentifiées actives. Seuls les utilisateurs disposant de droits d'accès administrateur peuvent appeler cette méthode.



== Paramètres

Cette méthode n'a pas de paramètres d'entrée.



== Valeurs de retour

Cette méthode a la valeur de retour suivante :

|===
| Nom | Description | Type 


 a| 
sessions
 a| 
Informations de session pour les sessions d'authentification.
 a| 
link:reference_element_api_authsessioninfo.html["AuthSessionInfo"]

|===


== Exemple de demande

Les demandes pour cette méthode sont similaires à l'exemple suivant :

[listing]
----
{
  "method": "ListActiveAuthSessions"
}
----


== Exemple de réponse

Cette méthode renvoie une réponse similaire à l'exemple suivant :

[listing]
----
{
"sessions": [
      {
        "accessGroupList": [
          "administrator"
        ],
        "authMethod": "Cluster",
        "clusterAdminIDs": [
          1
        ],
        "finalTimeout": "2020-03-14T19:21:24Z",
        "idpConfigVersion": 0,
        "lastAccessTimeout": "2020-03-11T19:51:24Z",
        "sessionCreationTime": "2020-03-11T19:21:24Z",
        "sessionID": "b12bfc64-f233-44df-8b9f-6fb6c011abf7",
        "username": "admin"
      }
    ]
}
----


== Nouveau depuis la version

12.0
