---
permalink: api/reference_element_api_listsnapshots.html 
sidebar: sidebar 
keywords: snapshot,snapshots,list,listing,attributes,listsnapshots 
summary: Vous pouvez utiliser Listsnapshots pour renvoyer les attributs de chaque instantané pris sur le volume. 
---
= Listsnapshots
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez utiliser `ListSnapshots` pour renvoyer les attributs de chaque snapshot pris sur le volume.

Les informations relatives aux snapshots qui résident sur le cluster cible s'affichent sur le cluster source lorsque cette méthode est appelée depuis le cluster source.



== Paramètres

Cette méthode présente les paramètres d'entrée suivants :

|===
| Nom | Description | Type | Valeur par défaut | Obligatoire 


 a| 
ID de volume
 a| 
Récupère les instantanés d'un volume. Si l'ID de volume n'est pas fourni, tous les snapshots de tous les volumes sont renvoyés.
 a| 
entier
 a| 
Aucune
 a| 
Non



 a| 
ID de snapshot
 a| 
Récupère les informations relatives à un ID de snapshot individuel.
 a| 
entier
 a| 
Aucune
 a| 
Non

|===


== Retour de valeur

Cette méthode a la valeur de retour suivante :

|===
| Nom | Description | Type 


 a| 
snapshots
 a| 
Informations sur chaque snapshot pour chaque volume. Si l'ID de volume n'est pas fourni, tous les snapshots de tous les volumes sont renvoyés. Les instantanés appartenant à un groupe sont renvoyés avec un ID de groupe.
 a| 
xref:reference_element_api_snapshot.adoc[snapshot] baie

|===


== Exemple de demande

Les demandes pour cette méthode sont similaires à l'exemple suivant :

[listing]
----
{
   "method": "ListSnapshots",
   "params": {
             "volumeID": "1"
       },
   "id" : 1
}
----


== Exemple de réponse

Cette méthode renvoie une réponse similaire à l'exemple suivant :

[listing]
----
{
  "id": 1,
  "result": {
    "snapshots": [
        {
          "attributes": {},
          "checksum": "0x0",
          "createTime": "2015-05-08T13:15:00Z",
          "enableRemoteReplication": true,
          "expirationReason": "None",
          "expirationTime": "2015-05-08T21:15:00Z",
          "groupID": 0,
          "groupSnapshotUUID": "00000000-0000-0000-0000-000000000000",
          "name": "Hourly",
          "remoteStatuses": [
              {
                "remoteStatus": "Present",
                "volumePairUUID": "237e1cf9-fb4a-49de-a089-a6a9a1f0361e"
              }
         ],
          "snapshotID": 572,
          "snapshotUUID": "efa98e40-cb36-4c20-a090-a36c48296c14",
          "status": "done",
          "totalSize": 10000269312,
          "volumeID": 1
        }
      ]
    }
  }
----


== Nouveau depuis la version

9.6
