---
permalink: api/reference_element_api_getcurrentclusteradmin.html 
sidebar: sidebar 
keywords: cluster,admin,get,getting,current,getcurrentclusteradmin 
summary: 'Vous pouvez utiliser la méthode GetCurrentClusterAdmin pour renvoyer des informations relatives à l"administrateur de cluster principal actuel. L"administrateur de cluster principal a été créé lors de la création du cluster.' 
---
= GetCurrentClusterAdmin
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez utiliser le `GetCurrentClusterAdmin` Méthode permettant de renvoyer des informations pour l'administrateur de cluster principal actuel. L'administrateur de cluster principal a été créé lors de la création du cluster.



== Paramètres

Cette méthode n'a pas de paramètres d'entrée.



== Retour de valeur

Cette méthode a la valeur de retour suivante :

|===
| Nom | Description | Type 


 a| 
ClusterAdmin
 a| 
Informations relatives à l'administrateur du cluster.
 a| 
xref:reference_element_api_clusteradmin.adoc[ClusterAdmin]

|===


== Exemple de demande

Les demandes pour cette méthode sont similaires à l'exemple suivant :

[listing]
----
{
"method": "GetCurrentClusterAdmin",
"id" : 1
}
----


== Exemple de réponse

Cette méthode renvoie une réponse similaire à l'exemple suivant :

[listing]
----
{
"id": 1,
"result": {
    "clusterAdmin":
        "access": [
           "administrator"
        ],
         "attributes": null,
         "authMethod": "Cluster"
         "clusterAdminID": 1,
         "username": "admin"
     }
   }
}
----


== Nouveau depuis la version

10.0
