---
permalink: api/reference_element_api_listactivenodes.html 
sidebar: sidebar 
keywords: cluster,list,listing,active,node,nodes,listactivenodes 
summary: Vous pouvez utiliser la méthode ListenActiveNodes pour renvoyer la liste des nœuds actuellement actifs dans le cluster. 
---
= ListenActiveNodes
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez utiliser le `ListActiveNodes` méthode pour renvoyer la liste des nœuds actuellement actifs dans le cluster.



== Paramètres

Cette méthode n'a pas de paramètres d'entrée.



== Retour de valeur

Cette méthode a la valeur de retour suivante :

|===
| Nom | Description | Type 


 a| 
nœuds
 a| 
Liste des nœuds actifs dans le cluster.
 a| 
xref:reference_element_api_node.adoc[nœud] baie

|===


== Exemple de demande

Les demandes pour cette méthode sont similaires à l'exemple suivant :

[listing]
----
{
   "method": "ListActiveNodes",
   "params": {},
   "id" : 1
}
----


== Exemple de réponse

En raison de la longueur de cet exemple de réponse, il est documenté dans un sujet supplémentaire.



== Nouveau depuis la version

9.6



== Trouvez plus d'informations

xref:reference_element_api_response_example_listactivenodes.adoc[ListenActiveNodes]
