---
permalink: api/reference_element_api_getnodestats.html 
sidebar: sidebar 
keywords: node,get,getting,stats,getnodestats 
summary: 'Vous pouvez utiliser la méthode GetNodeStats pour récupérer les mesures d"activité de haut niveau pour un seul nœud.' 
---
= GetNodeStats
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez utiliser le `GetNodeStats` méthode permettant de récupérer les mesures d'activité de haut niveau pour un seul nœud.



== Paramètre

Cette méthode dispose du paramètre d'entrée suivant :

|===
| Nom | Description | Type | Valeur par défaut | Obligatoire 


 a| 
ID de nœud
 a| 
Spécifie l'ID du nœud pour lequel les statistiques seront renvoyées.
 a| 
entier
 a| 
Aucune
 a| 
Oui.

|===


== Retour de valeur

Cette méthode a la valeur de retour suivante :

|===
| Nom | Description | Type 


 a| 
Statistiques du nœud
 a| 
Informations sur l'activité des nœuds.
 a| 
xref:reference_element_api_nodestats.adoc[Statistiques du nœud]

|===


== Exemple de demande

Les demandes pour cette méthode sont similaires à l'exemple suivant :

[listing]
----
{
   "method": "GetNodeStats",
   "params": {
     "nodeID": 5
   },
   "id": 1
}
----


== Exemple de réponse

Cette méthode renvoie une réponse similaire à l'exemple suivant :

[listing]
----
{
   "id" : 1,
   "result" : {
     "nodeStats" : {
       "cBytesIn" : 9725856460404,
       "cBytesOut" : 16730049266858,
       "cpu" : 98,
       "mBytesIn" : 50808519,
       "mBytesOut" : 52040158,
       "networkUtilizationCluster" : 84,
       "networkUtilizationStorage" : 0,
       "sBytesIn" : 9725856460404,
       "sBytesOut" : 16730049266858,
       "timestamp" : "2012-05-16T19:14:37.167521Z",
       "usedMemory" : 41195708000
     }
   }
}
----


== Nouveau depuis la version

9.6
