---
permalink: api/reference_element_api_getnvraminfo.html 
sidebar: sidebar 
keywords: nvram,info,get,getting,getnvraminfo 
summary: Vous pouvez utiliser la méthode GetNvramInfo pour obtenir des informations de chaque nœud sur la carte NVRAM. 
---
= GetNvramInfo
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez utiliser le `GetNvramInfo` Méthode d'obtention des informations de chaque nœud sur la carte NVRAM.



== Paramètre

Cette méthode dispose du paramètre d'entrée suivant :

|===
| Nom | Description | Type | Valeur par défaut | Obligatoire 


 a| 
de force
 a| 
Le paramètre force doit être inclus dans cette méthode pour s'exécuter correctement sur tous les nœuds du cluster.
 a| 
booléen
 a| 
Aucune
 a| 
Oui.

|===


== Retour de valeur

Cette méthode a la valeur de retour suivante :

|===
| Nom | Description | Type 


 a| 
NvramInfo
 a| 
Tableaux des événements et erreurs détectés sur la carte NVRAM.
 a| 
Objet JSON

|===


== Exemple de demande

Les demandes pour cette méthode sont similaires à l'exemple suivant :

[listing]
----
{
  "method": "GetNvramInfo",
  "params": {
      "force": true
	  },
  "id" : 1
}
----


== Exemple de réponse

En raison de la longueur de cet exemple de réponse, il est documenté dans un sujet supplémentaire.



== Nouveau depuis la version

9.6



== Trouvez plus d'informations

xref:reference_element_api_response_example_getnvraminfo.adoc[GetNvramInfo]
