---
permalink: api/reference_element_api_getnodeactivetlsciphers.html 
sidebar: sidebar 
keywords: tls,cipher,ciphers,get,getting,getnodeactivetlsciphers,accepted 
summary: Vous pouvez utiliser la méthode GetNodeActiveTlsCiphers sur un seul nœud pour obtenir la liste des chiffrements TLS qui sont actuellement acceptés sur ce nœud. Vous pouvez utiliser cette méthode sur les nœuds de stockage et de gestion. 
---
= GetNodeActiveTlsCiphers
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez utiliser le `GetNodeActiveTlsCiphers` Méthode sur un seul nœud pour obtenir la liste des chiffrements TLS qui sont actuellement acceptés sur ce nœud. Vous pouvez utiliser cette méthode sur les nœuds de stockage et de gestion.



== Paramètre

Cette méthode n'a pas de paramètres d'entrée.



== Valeurs de retour

Cette méthode a les valeurs de retour suivantes :

|===
| Nom | Description | Type 


 a| 
Ciphers de données
 a| 
Liste des suites de chiffrement TLS obligatoires pour le nœud. Ces chiffrements sont toujours actifs sur le nœud.
 a| 
chaîne



 a| 
Ciphers supplémentaires
 a| 
Liste des suites de chiffrement TLS supplémentaires pour le nœud.
 a| 
chaîne

|===


== Exemple de demande

Les demandes pour cette méthode sont similaires à l'exemple suivant :

[listing]
----
{
  "method": "GetNodeActiveTlsCiphers",
  "params": {},
  "id" : 1
}
----


== Exemple de réponse

Cette méthode renvoie une réponse similaire à l'exemple suivant :

[listing]
----
{
      "id" : 1,
      "result" : {
        "mandatoryCiphers": [
            "DHE-RSA-AES256-SHA256",
            "DHE-RSA-AES256-GCM-SHA384",
            "ECDHE-RSA-AES256-SHA384",
            "ECDHE-RSA-AES256-GCM-SHA384"
        ],
        "supplementalCiphers": [
            "DHE-RSA-AES128-SHA256",
            "DHE-RSA-AES128-GCM-SHA256",
            "ECDHE-RSA-AES128-SHA256",
            "ECDHE-RSA-AES128-GCM-SHA256"
        ]
    }
}
----