---
permalink: api/reference_element_api_abortsnapmirrorrelationship.html 
sidebar: sidebar 
keywords:  
summary: 'L"interface utilisateur Web du logiciel Element utilise la méthode AbortSnapMirror orRelationship pour arrêter les transferts SnapMirror effectués, mais qui ne sont pas encore terminés.' 
---
= ObortSnapMirror : Relationship
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
L'interface utilisateur Web du logiciel Element utilise le `AbortSnapMirrorRelationship` Méthode pour arrêter les transferts SnapMirror qui ont commencé, mais pas encore terminés.



== Paramètres

Cette méthode présente les paramètres d'entrée suivants :

|===
| Nom | Description | Type | Valeur par défaut | Obligatoire 


 a| 
SnapMirrorEndpointID
 a| 
L'ID de terminal du système de stockage ONTAP distant communique avec le cluster de stockage Element.
 a| 
entier
 a| 
Aucune
 a| 
Oui.



 a| 
Volume desestinationVolume
 a| 
Volume de destination dans la relation SnapMirror.
 a| 
xref:reference_element_api_snapmirrorvolumeinfo.adoc[SnapMirrorVolumeInfo]
 a| 
Aucune
 a| 
Oui.



 a| 
Point de contrôle
 a| 
Détermine s'il faut ou non effacer le point de contrôle de redémarrage. Valeurs possibles :

* vrai
* faux

 a| 
booléen
 a| 
faux
 a| 
Non

|===


== Valeurs de retour

Cette méthode a les valeurs de retour suivantes :

|===
| Nom | Description | Type 


 a| 
SnapMirrorRelationship
 a| 
Objet contenant des informations sur la relation SnapMirror abandonnée.
 a| 
xref:reference_element_api_snapmirrorrelationship.adoc[SnapMirrorRelationship]

|===


== Nouveau depuis la version

10.1
