---
permalink: api/reference_element_api_listauthsessionbyusername.html 
sidebar: sidebar 
keywords: username,sessions,authentication sessions,list 
summary: 'Vous pouvez utiliser la méthode ListAuthSessionsByUsername pour répertorier toutes les sessions d"authentification pour l"utilisateur spécifié. Un appelant ne se trouvant pas dans Access Group ClusterAdmins / privilèges d"administrateur peut uniquement répertorier ses propres sessions. Un appelant disposant de privilèges ClusterAdmins / Administrateur peut lister les sessions appartenant à n"importe quel utilisateur.' 
---
= ListeAuthSessionsByUsername
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez utiliser le `ListAuthSessionsByUsername` méthode permettant de répertorier toutes les sessions d'authentification pour l'utilisateur spécifié. Un appelant ne se trouvant pas dans Access Group ClusterAdmins / privilèges d'administrateur peut uniquement répertorier ses propres sessions. Un appelant disposant de privilèges ClusterAdmins / Administrateur peut lister les sessions appartenant à n'importe quel utilisateur.



== Paramètres

Cette méthode présente les paramètres d'entrée suivants :

|===
| Nom | Description | Type | Valeur par défaut | Obligatoire 


 a| 
Méthode d'authentification
 a| 
Méthode d'authentification des sessions utilisateur à lister. Seul un appelant du groupe d'accès ClusterAdmins/Administrateur peut fournir ce paramètre. Les valeurs possibles sont :

* *AuthMethod=Cluster* spécifie le nom d'utilisateur ClusterAdmin.
* *AuthMethod=LDAP* spécifie le DN LDAP de l'utilisateur.
* *AuthMethod=IDP* spécifie l'UUID ou le NameID de l'utilisateur. Si l'IDP n'est pas configuré pour renvoyer l'une ou l'autre des options, cela spécifie un UUID aléatoire émis lors de la création de la session.

 a| 
Méthode d'authentification
 a| 
Aucune
 a| 
Oui.



 a| 
nom d'utilisateur
 a| 
Identifiant unique de l'utilisateur.
 a| 
chaîne
 a| 
Aucune
 a| 
Oui.

|===


== Valeurs de retour

Cette méthode a la valeur de retour suivante :

|===


| Nom | Description | Type 


 a| 
sessions
 a| 
Liste des informations de session pour les sessions d'authentification.
 a| 
link:reference_element_api_authsessioninfo.html["AuthSessionInfo"]

|===


== Exemple de demande

Les demandes pour cette méthode sont similaires à l'exemple suivant :

[listing]
----
{
    "method": "ListAuthSessionsByUsername",
    "authMethod": "Cluster",
    "username": "admin"
}
----


== Exemple de réponse

Cette méthode renvoie une réponse similaire à l'exemple suivant :

[listing]
----
{
"sessions": [
      {
        "accessGroupList": [
          "administrator"
        ],
        "authMethod": "Cluster",
        "clusterAdminIDs": [
          1
        ],
        "finalTimeout": "2020-03-14T19:21:24Z",
        "idpConfigVersion": 0,
        "lastAccessTimeout": "2020-03-11T19:51:24Z",
        "sessionCreationTime": "2020-03-11T19:21:24Z",
        "sessionID": "b12bfc64-f233-44df-8b9f-6fb6c011abf7",
        "username": "admin"
      }
    ]
}
----


== Nouveau depuis la version

12.0
