---
permalink: api/reference_element_api_setprotectiondomainlayout.html 
sidebar: sidebar 
keywords: layout,custom,protection domain,protection domains,setting protection domains 
summary: Vous pouvez utiliser la méthode SetProtectionDomainLayout pour attribuer des nœuds aux domaines de protection personnalisés. 
---
= SetProtectionDomainLayout
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez utiliser le `SetProtectionDomainLayout` méthode d'affectation des nœuds à des domaines de protection personnalisés.

Les informations doivent être fournies pour tous les nœuds actifs du cluster et aucune information ne peut être fournie pour les nœuds inactifs. Tous les nœuds d'un châssis donné doivent être affectés au même domaine de protection personnalisé. Le même protectionDomainType doit être fourni pour tous les noeuds. ProtectionDomainTypes qui ne sont pas personnalisées, tels que le nœud et le châssis, ne doit pas être inclus. Si l'un de ces domaines est fourni, les domaines de protection personnalisés sont ignorés et une erreur appropriée est renvoyée.


NOTE: Les domaines de protection personnalisés ne sont pas pris en charge avec les configurations suivantes :

* Clusters de stockage contenant un châssis partagé
* Clusters de stockage à deux nœuds


La méthode renvoie une erreur lorsqu'elle est utilisée sur les clusters de stockage avec ces configurations.



== Paramètre

Cette méthode présente les paramètres d'entrée suivants :

|===
| Nom | Description | Type | Valeur par défaut | Obligatoire 


 a| 
ProtectionDomainLayout
 a| 
Informations sur le domaine de protection pour chaque nœud.
 a| 
Liste JSON de link:reference_element_api_nodeprotectiondomains.html["Domaines de protection des noeuds"] objets.
 a| 
Aucune
 a| 
Oui.

|===


== Retour de valeur

Cette méthode a la valeur de retour suivante :

|===
| Nom | Description | Type 


 a| 
ProtectionDomainLayout
 a| 
Liste des nœuds, chacun avec ses domaines de protection associés.
 a| 
Liste JSON de link:reference_element_api_nodeprotectiondomains.html["Domaines de protection des noeuds"] objets.

|===


== Exemple de demande

Les demandes pour cette méthode sont similaires à l'exemple suivant :

[listing]
----
{
  "id": 1,
  "method": "SetProtectionDomainLayout",
  "params": {
    "protectionDomainLayout": [
      {
        "nodeID": 1,
        "protectionDomains": [
          {
            "protectionDomainName": "Rack-1",
            "protectionDomainType": "custom"
          }
        ]
      },
      {
        "nodeID": 2,
        "protectionDomains": [
          {
            "protectionDomainName": "Rack-1",
            "protectionDomainType": "custom"
          }
        ]
      },
      {
        "nodeID": 3,
        "protectionDomains": [
          {
            "protectionDomainName": "Rack-2",
            "protectionDomainType": "custom"
          }
        ]
      },
      {
        "nodeID": 4,
        "protectionDomains": [
          {
            "protectionDomainName": "Rack-2",
            "protectionDomainType": "custom"
          }
        ]
      }
    ]
  }
}
----


== Exemple de réponse

Cette méthode renvoie une réponse similaire à l'exemple suivant :

[listing]
----

{
  "id": 1,
  "result": {
    "protectionDomainLayout": [
      {
        "nodeID": 1,
        "protectionDomains": [
          {
            "protectionDomainName": "QTFCR2914008D",
            "protectionDomainType": "chassis"
          },
          {
            "protectionDomainName": "Rack-1",
            "protectionDomainType": "custom"
          }
        ]
      },
      {
        "nodeID": 2,
        "protectionDomains": [
          {
            "protectionDomainName": "QTFCR291500EA",
            "protectionDomainType": "chassis"
          },
          {
            "protectionDomainName": "Rack-1",
            "protectionDomainType": "custom"
          }
        ]
      },
      {
        "nodeID": 3,
        "protectionDomains": [
          {
            "protectionDomainName": "QTFCR291500C3",
            "protectionDomainType": "chassis"
          },
          {
            "protectionDomainName": "Rack-2",
            "protectionDomainType": "custom"
          }
        ]
      },
      {
        "nodeID": 4,
        "protectionDomains": [
          {
            "protectionDomainName": "QTFCR291400E6",
            "protectionDomainType": "chassis"
          },
          {
            "protectionDomainName": "Rack-2",
            "protectionDomainType": "custom"
          }
        ]
      }
    ]
  }
}
----


== Nouveau depuis la version

12.0
