---
permalink: api/reference_element_api_listsyncjobs.html 
sidebar: sidebar 
keywords: sync,synchronization,job,jobs,list,get,listing,getting,listsyncjobs 
summary: 'Vous pouvez utiliser la méthode ListSyncJobs pour obtenir des informations sur les tâches de synchronisation exécutées sur un cluster de stockage d"éléments. Cette méthode renvoie des informations sur les tâches de synchronisation par tranche, clone, bloc et distant.' 
---
= ListSyncJobs
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez utiliser le `ListSyncJobs` Méthode pour obtenir des informations sur les tâches de synchronisation exécutées sur un cluster de stockage Element. Cette méthode renvoie des informations sur les tâches de synchronisation par tranche, clone, bloc et distant.



== Paramètres

Cette méthode n'a pas de paramètres d'entrée.



== Retour de valeur

Cette méthode a la valeur de retour suivante :

|===
| Nom | Description | Type 


 a| 
SyncJobs
 a| 
Liste des objets décrivant les processus de synchronisation en cours d'exécution dans le système.
 a| 
xref:reference_element_api_syncjob.adoc[SyncJob] baie

|===


== Exemple de demande

Les demandes pour cette méthode sont similaires à l'exemple suivant :

[listing]
----
{
   "method": "ListSyncJobs",
   "params": { },
   "id" : 1
}
----


== Exemple de réponse

Cette méthode renvoie une réponse similaire à l'exemple suivant :

[listing]
----
{
    "id":1,
    "result":{
      "syncJobs":[
        {
           "bytesPerSecond":275314.8834458956,
           "currentBytes":178257920,
           "dstServiceID":36,
           "elapsedTime":289.4568382049871,
           "percentComplete":8.900523560209423,
           "remainingTime":2962.675921065957,
           "sliceID":5,
           "srcServiceID":16,
           "stage":"whole",
           "totalBytes":2002780160,
           "type":"slice"
       },
       {
           "bytesPerSecond":305461.3198607744,
           "cloneID":1,
           "currentBytes":81788928,
           "dstServiceID":16,
           "dstVolumeID":6,
           "elapsedTime":291.7847648200743,
           "nodeID":1,
           "percentComplete":8.167539267015707,
           "remainingTime":3280.708270981153,
           "sliceID":6,
           "srcServiceID":16,
           "srcVolumeID":5,
           "stage":"whole",
           "totalBytes":1001390080,
           "type":"clone"
        },
        {
           "blocksPerSecond":0,
           "branchType": "snapshot",
           "dstServiceID":8,
           "dstVolumeID":2,
           "elapsedTime":0,
           "percentComplete":0,
           "remainingTime":0,
           "sliceID":2,
           "stage":"metadata",
           "type":"remote"
       }
     ]
   }
}
----


== Nouveau depuis la version

9.6
