---
permalink: api/reference_element_api_listprotocolendpoints.html 
sidebar: sidebar 
keywords: protocol,endpoints,endpoint,list,listing,listprotocolendpoints 
summary: 'Vous pouvez utiliser la méthode ListProtocolEndpoints pour extraire des informations sur tous les noeuds finaux de protocole du cluster. Les terminaux PE régissent l"accès à leurs conteneurs de stockage de volume virtuel associés.' 
---
= ListProtocolEndpoints
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez utiliser le `ListProtocolEndpoints` méthode pour extraire des informations concernant tous les terminaux de protocole du cluster. Les terminaux PE régissent l'accès à leurs conteneurs de stockage de volume virtuel associés.



== Paramètres

Cette méthode dispose du paramètre d'entrée suivant :

|===
| Nom | Description | Type | Valeur par défaut | Obligatoire 


 a| 
ProtocolEndpointID
 a| 
Liste des ID de point de terminaison de protocole pour lesquels récupérer des informations. Si vous omettez ce paramètre, la méthode renvoie des informations sur tous les noeuds finaux du protocole.
 a| 
Tableau UUID protocolEndpointID
 a| 
Aucune
 a| 
Non

|===


== Valeurs de retour

Cette méthode a la valeur de retour suivante :

|===
| Nom | Description | Type 


 a| 
Points protocolEndpoints
 a| 
Liste des objets contenant des informations sur chaque point de terminaison de protocole dans le système.
 a| 
xref:reference_element_api_protocolendpoint.adoc[ProtocolEndpoint] baie

|===


== Exemple de demande

Les demandes pour cette méthode sont similaires à l'exemple suivant :

[listing]
----
{
  "id": 1,
  "method": "ListProtocolEndpoints",
  "params": {}
}
----


== Exemple de réponse

Cette méthode renvoie une réponse similaire à l'exemple suivant :

[listing]
----
{
  "id": 1,
  "result": {
    "protocolEndpoints": [
      {
        "primaryProviderID": 1,
        "protocolEndpointID": "1387e257-d2e3-4446-be6d-39db71583e7b",
        "protocolEndpointState": "Active",
        "providerType": "Primary",
        "scsiNAADeviceID": "6f47acc2000000016970687200000000",
        "secondaryProviderID": 2
      },
      {
        "primaryProviderID": 2,
        "protocolEndpointID": "1f16ed86-3f31-4c76-b004-a1251187700b",
        "protocolEndpointState": "Active",
        "providerType": "Primary",
        "scsiNAADeviceID": "6f47acc2000000026970687200000000",
        "secondaryProviderID": 3
      },
      {
        "primaryProviderID": 4,
        "protocolEndpointID": "c6458dfe-9803-4350-bb4e-68a3feb7e830",
        "protocolEndpointState": "Active",
        "providerType": "Primary",
        "scsiNAADeviceID": "6f47acc2000000046970687200000000",
        "secondaryProviderID": 1
      },
      {
        "primaryProviderID": 3,
        "protocolEndpointID": "f3e7911d-0e86-4776-97db-7468c272213f",
        "protocolEndpointState": "Active",
        "providerType": "Primary",
        "scsiNAADeviceID": "6f47acc2000000036970687200000000",
        "secondaryProviderID": 4
      }
    ]
  }
}
----


== Nouveau depuis la version

9.6
