---
permalink: api/reference_element_api_deleteclusterinterfacepreference.html 
sidebar: sidebar 
keywords: cluster,interface,preferences,delete,deleting,DeleteClusterInterfacePreference 
summary: 'La méthode DeleteClusterInterfacePreference permet aux systèmes intégrés aux clusters de stockage exécutant le logiciel Element de supprimer une préférence d"interface de cluster existante. Cette méthode est destinée à un usage interne.' 
---
= DeleteClusterInterfacePreference
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Le `DeleteClusterInterfacePreference` Méthode qui permet aux systèmes intégrés avec des clusters de stockage exécutant le logiciel Element de supprimer une préférence d'interface de cluster. Cette méthode est destinée à un usage interne.



== Paramètres

Cette méthode dispose du paramètre d'entrée suivant :

|===
| Nom | Description | Type | Valeur par défaut | Obligatoire 


 a| 
nom
 a| 
Nom de l'option d'interface du cluster à supprimer.
 a| 
chaîne
 a| 
Aucune
 a| 
Oui.

|===


== Valeurs de retour

Cette méthode n'a pas de valeur de retour.



== Exemple de demande

Les demandes pour cette méthode sont similaires à l'exemple suivant :

[listing]
----
{
	"method": "DeleteClusterInterfacePreference",
	"params": {
		"name": "prefname"
		},
	"id": 1
}
----


== Exemple de réponse

Cette méthode renvoie une réponse similaire à l'exemple suivant :

[listing]
----
{
    "id": 1,
    "result": {}
}
----


== Nouveau depuis la version

11.0
