---
permalink: api/reference_element_api_setlicensekey.html 
sidebar: sidebar 
keywords: set,setting,license,key 
summary: Sur les clusters de stockage SolidFire Enterprise SDS, vous pouvez utiliser la méthode SetLicenseKey pour définir la clé de licence du cluster de stockage. La clé de licence pour un cluster de stockage se compose du numéro de commande du cluster associé au numéro de série et active le modèle de capacité que vous avez acheté pour le logiciel Element. 
---
= SetLicenseKey
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sur les clusters de stockage SolidFire Enterprise SDS, vous pouvez utiliser le `SetLicenseKey` méthode permettant de définir la clé de licence pour le cluster de stockage. La clé de licence pour un cluster de stockage se compose du numéro de commande du cluster associé au numéro de série et active le modèle de capacité que vous avez acheté pour le logiciel Element.



== Paramètres

Cette méthode présente les paramètres d'entrée suivants :

|===
| Nom | Description | Type | Valeur par défaut | Obligatoire 


 a| 
Numéro d'ordre
 a| 
Le nouveau numéro de commande pour ce cluster de stockage.
 a| 
chaîne
 a| 
Aucune
 a| 
Oui.



 a| 
Numéro de série
 a| 
Le nouveau numéro de série de ce cluster de stockage.
 a| 
chaîne
 a| 
Aucune
 a| 
Oui.

|===


== Valeurs de retour

Cette méthode a les valeurs de retour suivantes :

|===
| Nom | Description | Type 


 a| 
Numéro d'ordre
 a| 
Le nouveau numéro de bon de commande du cluster de stockage.
 a| 
chaîne



 a| 
Numéro de série
 a| 
Le nouveau numéro de série du cluster de stockage.
 a| 
chaîne

|===


== Exemple de demande

Les demandes pour cette méthode sont similaires à l'exemple suivant :

[listing]
----
{
  "method": "SetLicenseKey",
  "params": {
    "orderNumber": "33601",
    "serialNumber": "30G56E3WV"   },
   "id" : 1
}
----


== Exemple de réponse

Cette méthode renvoie une réponse similaire à l'exemple suivant :

[listing]
----
{
   "id" : 1,
   "result" : {
      "serialNumber": "30G56E3WV",
      "orderNumber": "33601"
     }
   }
}
----


== Nouveau depuis la version

12.2
