---
permalink: api/reference_element_api_listprotectiondomainlevels.html 
sidebar: sidebar 
keywords: list,listing,protection,domain,levels,level,listprotectiondomainlevels 
summary: 'Vous pouvez utiliser la méthode ListProtectionDomainLevels pour lister les niveaux de tolérance et de résilience du cluster de stockage. Les niveaux de tolérance indiquent la capacité du cluster à continuer la lecture et l"écriture des données en cas de défaillance, tandis que les niveaux de résilience indiquent la capacité du cluster de stockage à se réparer automatiquement après une ou plusieurs défaillances.' 
---
= ListProtectionDomainLevels
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez utiliser le `ListProtectionDomainLevels` méthode permettant de lister les niveaux de tolérance et de résilience du cluster de stockage. Les niveaux de tolérance indiquent la capacité du cluster à continuer la lecture et l'écriture des données en cas de défaillance. Les niveaux de résilience indiquent que le cluster de stockage est capable de se réparer automatiquement après une ou plusieurs défaillances.



== Paramètre

Cette méthode n'a pas de paramètre d'entrée.



== Valeurs de retour

Cette méthode a les valeurs de retour suivantes :

|===
| Nom | Description | Type 


 a| 
ProtectionDomainLevels
 a| 
Une liste des différents niveaux de domaine de protection, où chacun fournit les informations de tolérance et de résilience du cluster de stockage.
 a| 
xref:reference_element_api_protectiondomainlevel.adoc[ProtectionDomainLevel]

|===


== Exemple de demande

Les demandes pour cette méthode sont similaires à l'exemple suivant :

[listing]
----
{
  "method": "ListProtectionDomainLevels",
  "params": {},
  "id" : 1
}
----


== Exemple de réponse

Cette méthode renvoie une réponse similaire à l'exemple suivant :

[listing]
----
{
	"id": 1,
	"result": {
		"protectionDomainLevels": [
			{
				"protectionDomainType": "node",
				"resiliency": {
					"protectionSchemeResiliencies": [
							{
								"protectionScheme": "doubleHelix",
								"sustainableFailuresForBlockData": 0,
								"sustainableFailuresForMetadata": 1
							}
					],
					"singleFailureThresholdBytesForBlockData": 0,
					"sustainableFailuresForEnsemble": 1
				},
				"tolerance": {
					"protectionSchemeTolerances": [
							{
								"protectionScheme": "doubleHelix",
								"sustainableFailuresForBlockData": 0,
								"sustainableFailuresForMetadata": 1
							}
					],
					"sustainableFailuresForEnsemble": 1
				}
			},
			{
				"protectionDomainType": "chassis",
				"resiliency": {
					"protectionSchemeResiliencies": [
							{
								"protectionScheme": "doubleHelix",
								"sustainableFailuresForBlockData": 0,
								"sustainableFailuresForMetadata": 1
							}
					],
					"singleFailureThresholdBytesForBlockData": 0,
					"sustainableFailuresForEnsemble": 1
				},
				"tolerance": {
					"protectionSchemeTolerances": [
							{
								"protectionScheme": "doubleHelix",
								"sustainableFailuresForBlockData": 0,
								"sustainableFailuresForMetadata": 1
							}
					],
					"sustainableFailuresForEnsemble": 1
				}
			}
		]
	}
}
----


== Nouveau depuis la version

11.0
