---
permalink: api/reference_element_api_setloginsessioninfo.html 
sidebar: sidebar 
keywords: authentication,login,session,info,timeout,setloginsessioninfo 
summary: 'Vous pouvez utiliser la méthode SetLoginSessionInfo pour définir la période pendant laquelle une authentification de connexion pour une session est valide. Une fois la période de connexion écoulée sans activité sur le système, l"authentification expire. Une fois la période de connexion écoulée, de nouveaux identifiants de connexion sont nécessaires pour continuer à accéder au cluster.' 
---
= SetLoginSessionInfo
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez utiliser le `SetLoginSessionInfo` méthode permettant de définir la période pendant laquelle une authentification de connexion pour une session est valide. Une fois la période de connexion écoulée sans activité sur le système, l'authentification expire. Une fois la période de connexion écoulée, de nouveaux identifiants de connexion sont nécessaires pour continuer à accéder au cluster.



== Paramètre

Cette méthode dispose du paramètre d'entrée suivant :

|===
| Nom | Description | Type | Valeur par défaut | Obligatoire 


 a| 
délai dépassé
 a| 
Période d'expiration de l'authentification de cluster. Formaté en HH:mm:ss Par exemple : 01:30:00, 00:90:00, et 00:00:5400 peuvent tous être utilisés pour égaler une période de temporisation de 90 minutes. La valeur minimale de temporisation est de 1 minute. Lorsqu'une valeur n'est pas fournie ou est définie sur zéro, la session de connexion n'a pas de valeur de délai d'attente.
 a| 
chaîne
 a| 
30 minutes
 a| 
Non

|===


== Retour de valeur

Cette méthode n'a pas de valeur de retour.



== Exemple de demande

Les demandes pour cette méthode sont similaires à l'exemple suivant :

[listing]
----
{
  "method": "SetLoginSessionInfo",
  "params": {
    "timeout" : "01:30:00"
   },
   "id" : 1
}
----


== Exemple de réponse

Cette méthode renvoie une réponse similaire à l'exemple suivant :

[listing]
----
{
  "id" : 1,
  "result" : {}
}
----


== Nouveau depuis la version

9.6
