---
permalink: api/reference_element_api_createbackuptarget.html 
sidebar: sidebar 
keywords: create,creating,backup,target,CreateBackupTarget 
summary: 'Vous pouvez utiliser CreateBackupTarget pour créer et stocker les informations de la cible de sauvegarde de sorte que vous n"ayez pas besoin de les saisir à chaque fois qu"une sauvegarde est créée.' 
---
= CreateBackupTarget
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez utiliser `CreateBackupTarget` pour créer et stocker des informations de cible de sauvegarde, vous n'avez pas besoin de les saisir à chaque fois qu'une sauvegarde est créée.



== Paramètres

Cette méthode présente les paramètres d'entrée suivants :

|===
| Nom | Description | Type | Valeur par défaut | Obligatoire 


 a| 
nom
 a| 
Nom de la cible de sauvegarde.
 a| 
chaîne
 a| 
Aucune
 a| 
Oui.



 a| 
attributs
 a| 
Liste des paires nom-valeur au format d'objet JSON.
 a| 
Objet JSON
 a| 
Aucune
 a| 
Oui (mais peut être vide)

|===


== Retour de valeur

Cette méthode a la valeur de retour suivante :

|===


| Nom | Description | Type 


 a| 
BackupTargetID
 a| 
Identifiant unique attribué à la nouvelle cible de sauvegarde.
 a| 
entier

|===


== Exemple de demande

Les demandes pour cette méthode sont similaires à l'exemple suivant :

[listing]
----
{
   "method": "CreateBackupTarget",
   "params": {
      "name": "mytargetbackup"
   },
"id": 1
}
----


== Exemple de réponse

Cette méthode renvoie une réponse similaire à l'exemple suivant :

[listing]
----
{
   "id": 1,
   "result": {
      "backupTargetID": 1
   }
}
----


== Nouveau depuis la version

9.6
