---
permalink: api/reference_element_api_modifyvolumes.html 
sidebar: sidebar 
keywords: volume,volumes,modifying,modify,change,changing,edit,editing,modifyvolumes 
summary: 'Vous pouvez utiliser la méthode Modilyvolumes pour configurer jusqu"à 500 volumes existants à la fois. Les modifications ont lieu immédiatement. Si Modify volumes ne parvient pas à modifier l"un des volumes spécifiés, aucun des volumes spécifiés n"est modifié.' 
---
= Volumes modificatives
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez utiliser le `ModifyVolumes` méthode de configuration d'un maximum de 500 volumes existants à la fois. Les modifications ont lieu immédiatement. Si `ModifyVolumes` impossible de modifier l'un des volumes spécifiés ; aucun des volumes spécifiés n'est modifié.

Si vous ne spécifiez pas de valeurs de QoS lors de la modification des volumes, les valeurs de QoS pour chaque volume restent inchangées. Pour récupérer les valeurs QoS par défaut d'un volume récemment créé, exécutez la `GetDefaultQoS` méthode.

Si vous devez augmenter la taille des volumes en cours de réplication, procédez de la manière suivante afin d'éviter les erreurs de réplication :

. Augmentez la taille du volume grâce à la réplicationaccès cible.
. Augmentez la taille de la source ou du volume avec l'accès ReadWrite.


Assurez-vous que les volumes cible et source sont de la même taille.


NOTE: Si vous définissez l'état d'accès sur verrouillé ou réplicationTarget, toutes les connexions iSCSI existantes sont arrêtées.



== Paramètres

Cette méthode présente les paramètres d'entrée suivants :

|===


| Nom | Description | Type | Valeur par défaut | Obligatoire 


 a| 
l'accès
 a| 
Accès autorisé pour les volumes. Valeurs possibles :

* `readOnly`: Seules les opérations de lecture sont autorisées.
* `readWrite`: Les lectures et les écritures sont autorisées.
* `locked`: Aucune lecture ou écriture n'est autorisée. Si elle n'est pas spécifiée, la valeur d'accès ne change pas.
* `replicationTarget`: Identifier un volume comme volume cible pour un ensemble de volumes appariés. Si le volume n'est pas couplé, l'état d'accès est verrouillé. Si aucune valeur n'est spécifiée, la valeur d'accès ne change pas.

 a| 
chaîne
 a| 
Aucune
 a| 
Non



 a| 
ID compte
 a| 
ID comptable auquel les volumes sont réaffectés. Si aucun n'est spécifié, le nom de compte précédent est utilisé.
 a| 
entier
 a| 
Aucune
 a| 
Non



 a| 
AssociateWithQoSPolicy
 a| 
Associez le volume à la règle de QoS spécifiée. Valeurs possibles :

* True : associez le volume à la règle QoS spécifiée dans le paramètre QoSPolicyID.
* FALSE : n'associez pas le volume à la règle QoS spécifiée dans le paramètre QoSPolicyID. Lorsque la valeur est FALSE, toute association de règles existante est supprimée, que vous spécifiiez ou non une stratégie QoS dans le paramètre QoSPolicy.

 a| 
booléen
 a| 
Aucune
 a| 
Non



 a| 
attributs
 a| 
Liste des paires nom-valeur au format d'objet JSON.
 a| 
Objet JSON
 a| 
Aucune
 a| 
Non



 a| 
CREATETIME
 a| 
Chaîne de date ISO 8601 à définir comme nouvelle date de création du volume. Obligatoire si setCreateTime est défini sur vrai.
 a| 
Chaîne ISO 8601
 a| 
Aucune
 a| 
Non



 a| 
EnableSnapMirror orReplication
 a| 
Détermine si le volume peut être utilisé pour la réplication avec les terminaux SnapMirror. Valeurs possibles :

* `true`
* `false`

 a| 
booléen
 a| 
faux
 a| 
Non



| Fif50 | Spécifie le nombre maximal de snapshots de premier entré en premier sorti (FIFO) pris en charge par le volume. Notez que les instantanés FIFO et non FIFO utilisent tous les deux le même pool d'emplacements de snapshot disponibles sur un volume. Utilisez cette option pour limiter la consommation de snapshot FIFO des emplacements de snapshot disponibles. Notez que vous ne pouvez pas modifier cette valeur pour qu'elle soit inférieure au nombre actuel de snapshots FIFO. | entier | Aucune | Non 


| Taille mini | Spécifie le nombre d'emplacements de snapshot réservés aux snapshots de premier entré, premier sorti uniquement. Puisque les instantanés FIFO et non FIFO partagent le même pool, le paramètre minFifoSize réduit le nombre total d'instantanés non FIFO possibles de la même quantité. Notez que vous ne pouvez pas modifier cette valeur de manière à ce qu'elle entre en conflit avec le nombre de snapshots non FIFO en cours. | entier | Aucune | Non 


 a| 
mode
 a| 
Mode de réplication de volume. Valeurs possibles :

* `asynch`: Attend que le système reconnaisse que les données sont stockées sur la source avant d'écrire sur la cible.
* `sync`: N'attend pas que l'accusé de réception de transmission de données de la source commence à écrire des données sur la cible.

 a| 
chaîne
 a| 
Aucune
 a| 
Non



 a| 
la qos
 a| 
La nouvelle qualité de service des paramètres des volumes. Si ce n'est pas spécifié, les paramètres de QoS ne sont pas modifiés. Valeurs possibles :

* `minIOPS`
* `maxIOPS`
* `burstIOPS`

 a| 
xref:reference_element_api_qos.adoc[La QoS]
 a| 
Aucune
 a| 
Non



 a| 
QosPolicyID
 a| 
ID de la politique dont les paramètres QoS doivent être appliqués aux volumes spécifiés Ce paramètre s'excluent mutuellement avec le paramètre de qos.
 a| 
entier
 a| 
Aucune
 a| 
Non



 a| 
SetCreateTime
 a| 
Réglez sur vrai pour modifier la date d'enregistrement de la création du volume.
 a| 
booléen
 a| 
Aucune
 a| 
Non



 a| 
Taille totale
 a| 
La nouvelle taille des volumes en octets. 1000000000 correspond à 1 Go. La taille est arrondie au mégaoctet le plus proche. Ce paramètre ne peut être utilisé que pour augmenter la taille d'un volume.
 a| 
entier
 a| 
Aucune
 a| 
Non



 a| 
ID de volume
 a| 
Liste des ID de volume à modifier.
 a| 
tableau entier
 a| 
Aucune
 a| 
Oui.

|===


== Retour de valeur

Cette méthode a la valeur de retour suivante :

|===


| Nom | Description | Type 


 a| 
volumétrie
 a| 
Tableau d'objets contenant des informations sur chaque volume récemment modifié.
 a| 
xref:reference_element_api_volume.adoc[volumétrie] baie

|===


== Exemple de demande

Les demandes pour cette méthode sont similaires à l'exemple suivant :

[listing]
----
{
  "method": "ModifyVolumes",
  "params": {
    "volumeIDs": [2,3],
    "attributes": {
      "name1": "value1",
      "name2": "value2",
      "name3": "value3"
    },
    "qos": {
      "minIOPS": 50,
      "maxIOPS": 100,
      "burstIOPS": 150,
      "burstTime": 60
    },
    "access" : "replicationTarget"
  },
  "totalSize": 80000000000,
  "id": 1
}
----


== Exemple de réponse

Cette méthode renvoie une réponse similaire à l'exemple suivant :

[listing]
----
{
  "id": 1,
  "result": {
    "volumes": [
      {
        "access": "replicationTarget",
        "accountID": 1,
        "attributes": {
          "name1": "value1",
          "name2": "value2",
          "name3": "value3"
        },
        "blockSize": 4096,
        "createTime": "2016-04-06T17:25:13Z",
        "deleteTime": "",
        "enable512e": false,
        "iqn": "iqn.2010-01.com.solidfire:jo73.2",
        "name": "doctest1",
        "purgeTime": "",
        "qos": {
          "burstIOPS": 150,
          "burstTime": 60,
          "curve": {
            "4096": 100,
            "8192": 160,
            "16384": 270,
            "32768": 500,
            "65536": 1000,
            "131072": 1950,
            "262144": 3900,
            "524288": 7600,
            "1048576": 15000
          },
          "maxIOPS": 100,
          "minIOPS": 50
        },
        "scsiEUIDeviceID": "6a6f373300000002f47acc0100000000",
        "scsiNAADeviceID": "6f47acc1000000006a6f373300000002",
        "sliceCount": 1,
        "status": "active",
        "totalSize": 1000341504,
        "virtualVolumeID": null,
        "volumeAccessGroups": [],
        "volumeID": 2,
        "volumePairs": []
      },
      {
        "access": "replicationTarget",
        "accountID": 1,
        "attributes": {
          "name1": "value1",
          "name2": "value2",
          "name3": "value3"
        },
        "blockSize": 4096,
        "createTime": "2016-04-06T17:26:31Z",
        "deleteTime": "",
        "enable512e": false,
        "iqn": "iqn.2010-01.com.solidfire:jo73.3",
        "name": "doctest2",
        "purgeTime": "",
        "qos": {
          "burstIOPS": 150,
          "burstTime": 60,
          "curve": {
            "4096": 100,
            "8192": 160,
            "16384": 270,
            "32768": 500,
            "65536": 1000,
            "131072": 1950,
            "262144": 3900,
            "524288": 7600,
            "1048576": 15000
          },
          "maxIOPS": 100,
          "minIOPS": 50
        },
        "scsiEUIDeviceID": "6a6f373300000003f47acc0100000000",
        "scsiNAADeviceID": "6f47acc1000000006a6f373300000003",
        "sliceCount": 1,
        "status": "active",
        "totalSize": 1000341504,
        "virtualVolumeID": null,
        "volumeAccessGroups": [],
        "volumeID": 3,
        "volumePairs": []
      }
    ]
  }
}
----


== Nouveau depuis la version

9.6



== Trouvez plus d'informations

xref:reference_element_api_getdefaultqos.adoc[GetDefaultQoS]
