---
permalink: api/reference_element_api_listgroupsnapshots.html 
sidebar: sidebar 
keywords: snapshot,snapshots,group,list,listing,listgroupsnapshots 
summary: Vous pouvez utiliser la méthode ListGroupsnapshots pour renvoyer des informations sur tous les instantanés de groupe qui ont été créés. 
---
= ListGroupsnapshots
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez utiliser `ListGroupSnapshots` méthode permettant de renvoyer des informations sur tous les instantanés de groupe qui ont été créés.



== Paramètres

Cette méthode présente les paramètres d'entrée suivants :

|===
| Nom | Description | Type | Valeur par défaut | Obligatoire 


 a| 
GroupSnapshotID
 a| 
Récupère les informations relatives à un ID d'instantané de groupe individuel.
 a| 
entier
 a| 
Aucune
 a| 
Non



 a| 
volumes
 a| 
Tableau d'ID de volume uniques à interroger. Si vous ne spécifiez pas ce paramètre, tous les snapshots de groupe du cluster sont inclus.
 a| 
Tableau d'ID de volume
 a| 
Aucune
 a| 
Non

|===


== Retour de valeur

Cette méthode a la valeur de retour suivante :

|===
| Nom | Description | Type 


 a| 
Groupesnapshots
 a| 
Liste d'objets contenant des informations sur chaque instantané de groupe.
 a| 
xref:reference_element_api_groupsnapshot.adoc[GroupSnapshot] baie

|===


== Exemple de demande

Les demandes pour cette méthode sont similaires à l'exemple suivant :

[listing]
----
{
  "method": "ListGroupSnapshots",
  "params": {
  "volumes": [
     31,
     49
    ]
  },
  "id": 1
}
----


== Exemple de réponse

Cette méthode renvoie une réponse similaire à l'exemple suivant :

[listing]
----
{
  "groupSnapshots": [
      {
          "status": "Done",
          "remoteStatuses": [
              {
                "volumePairUUID": "abcdef-1234-5678-90ab-cdef0123",
                "remoteStatus": "Present"
              }
          ],
          "attributes": {},
          "groupSnapshotID": 1,
          "createTime": "2014-06-17T17:35:05Z",
          "members": [
              {
                "snapshotUUID": "abcdef-1234-5678-90ab-cdef0123",
                "expirationReason": "None",
                "virtualVolumeID": "abcdef-1234-5678-90ab-cdef0123",
                "groupID": 1,
                "createTime": "2014-06-17T17:35:05Z",
                "totalSize": 1,
                "snapMirrorLabel": "test1",
                "volumeName": "test1",
                "instanceCreateTime": "2014-06-17T17:35:05Z",
                "volumeID": 1,
                "checksum": "0x0",
                "attributes": {},
                "instanceSnapshotUUID": "abcdef-1234-5678-90ab-cdef0123",
                "snapshotID": 1,
                "status": "Done",
                "groupSnapshotUUID": "abcdef-1234-5678-90ab-cdef0123",
                "expirationTime": "2014-06-17T17:35:05Z",
                "enableRemoteReplication": true,
                "name": "test1",
                "remoteStatuses": [
                      {
                        "volumePairUUID": "abcdef-1234-5678-90ab-cdef0123",
                        "remoteStatus": "Present"
                      }
                  ]
              }
          ],
          "enableRemoteReplication": true,
          "name": "test1",
          "groupSnapshotUUID": "abcdef-1234-5678-90ab-cdef0123"
      }
	]
}
----


== Nouveau depuis la version

9.6
